[package]
name = "maho-ext-webfetch"
version.workspace = true
edition.workspace = true
publish.workspace = true
license = "MIT"

[dependencies]
dom_query = { version = "=0.27.0", default-features = false }
serde_json = "=1.0.149"
futures = "=0.3.34"
tokio = { version = "=1.52.3", features = ["macros", "rt", "sync", "time", "net", "io-util"] }
maho-tools = { path = "../../maho-tools" }
maho-ext-api = { path = "../../maho-ext-api" }
thiserror = "=2.0.18"
reqwest = { version = "=0.13.2", default-features = false, features = ["rustls", "stream"] }
url = "=2.5.8"
regex = "=1.12.3"

[lints]
workspace = true
