[package]
name = "maho-ext-webfetch"
version.workspace = true
edition.workspace = true
publish.workspace = true
license = "MIT"

[dependencies]
futures = "=0.3.34"
tokio = { version = "=1.52.3", features = ["macros", "rt", "sync", "time", "net", "io-util"] }
maho-tools = { path = "../../maho-tools" }
thiserror = "=2.0.18"
reqwest = { version = "=0.13.2", default-features = false, features = ["rustls", "stream"] }
url = "=2.5.8"

[lints]
workspace = true
