use std::sync::{Arc,Mutex,Weak};
use maho_ai::types::BoxFuture;
use maho_agent::harness::context::{Context,BACKGROUND_CONTEXT};
use maho_agent::harness::events::HarnessEvent;
use maho_agent::harness::hooks::HookRegistry;
use maho_agent::harness::agent_harness::DriveOptions;
use maho_agent::harness::runtime::types::*;
use maho_agent::harness::runtime::types::LaneState;
use maho_agent::harness::runtime::restore::{decode_operation_state,restore_lane};
use maho_agent::harness::runtime::drive::{checkpoint::*,generation::*,recovery::*,drive_operation};
use maho_agent::harness::session::memory::MemoryStorage;
use maho_agent::harness::session::session::{SessionError,StorageBackedSession,StorageBackedSessionOptions};
use maho_agent::harness::session::types::*;
use maho_agent::harness::session::commit::insert_entry;
use maho_agent::harness::session::values::*;
use serde_json::json;

struct Lane { own:Weak<Lane>,session:StorageBackedSession,state:Mutex<LaneState>,config:Arc<Config<()>>,models:maho_ai::models::Models,hooks:HookRegistry,events:Mutex<Vec<HarnessEvent>>,cancel_options:Mutex<Vec<maho_ai::types::ProviderRequestOptions>>,cancel_fails:std::sync::atomic::AtomicBool }
struct FauxAuth;
impl maho_ai::models::ModelsAuth for FauxAuth {
    fn resolve<'a>(&'a self,_:&'a dyn maho_ai::models::Provider,_:&'a maho_ai::models::AuthResolutionOverrides)->BoxFuture<'a,Result<Option<maho_ai::models::AuthResolution>,maho_ai::models::ModelsError>> {Box::pin(async {Ok(Some(maho_ai::models::AuthResolution {auth:maho_ai::models::ProviderAuthResult {api_key:Some("fixture".into()),..Default::default()},env:None}))})}
    fn refresh_credential<'a>(&'a self,_:&'a dyn maho_ai::models::Provider,_:Option<&'a maho_ai::models::Credential>,_:&'a maho_ai::utils::abort::AbortSignal)->BoxFuture<'a,Result<Option<maho_ai::models::Credential>,maho_ai::models::ModelsError>>{Box::pin(async {Ok(None)})}
}
impl RuntimeLane for Lane {
    fn name(&self)->&str {"main"} fn session(&self)->&dyn Session {&self.session} fn state(&self)->LaneState {self.state.lock().expect("generation fixture must be valid").clone()} fn publish_state(&self,state:LaneState){*self.state.lock().expect("generation fixture must be valid")=state;} fn emit<'a>(&'a self,events:Vec<HarnessEvent>,_:&'a Context)->BoxFuture<'a,()> {Box::pin(async move {self.events.lock().expect("generation fixture must be valid").extend(events);})}
}
impl RuntimeDriveLane for Lane {
    fn progress_lane(&self)->Arc<dyn RuntimeLane> {self.own.upgrade().expect("generation fixture must be valid")}
    fn config(&self)->Arc<Config<()>>{self.config.clone()} fn hooks(&self)->&HookRegistry{&self.hooks} fn models(&self)->&maho_ai::models::Models{&self.models}
    fn cancel_deferred<'a>(&'a self,_:&'a maho_ai::model::Model,_:&'a maho_ai::types::DeferredHandle,options:maho_ai::types::ProviderRequestOptions)->BoxFuture<'a,Result<(),String>>{Box::pin(async move {self.cancel_options.lock().expect("cancellation options lock").push(options);if self.cancel_fails.load(std::sync::atomic::Ordering::SeqCst){Err("remote cancellation failed".into())}else{Ok(())}})}
    fn prepare_compaction_threshold<'a>(&'a self,_:&'a Drive,_:&'a OperationState)->BoxFuture<'a,Result<ContinueOperationResult<Option<StructuralPreparation>>,SessionError>>{Box::pin(async {Ok(ContinueOperationResult::Result {value:None})})}
    fn prepare_overflow_compaction<'a>(&'a self,_:&'a Drive,_:&'a OperationState)->BoxFuture<'a,Result<Option<StructuralPreparation>,SessionError>>{Box::pin(async {Ok(None)})}
    fn run_tools<'a>(&'a self,_:&'a Drive,_:OperationState)->BoxFuture<'a,Result<ProcedureResult,SessionError>>{Box::pin(async {panic!("unexpected tools")})}
    fn run_structural<'a>(&'a self,_:&'a Drive,_:OperationState)->BoxFuture<'a,Result<ProcedureResult,SessionError>>{Box::pin(async {panic!("unexpected structural")})}
}
async fn fixture()->(Arc<Lane>,Drive,maho_ai::providers::faux::FauxProviderHandle) {
    fixture_with_options(Default::default()).await
}
async fn fixture_with_options(options:maho_ai::providers::faux::RegisterFauxProviderOptions)->(Arc<Lane>,Drive,maho_ai::providers::faux::FauxProviderHandle) {
    let faux=maho_ai::providers::faux::faux_provider(options);let model=faux.get_model(None).expect("generation fixture must be valid");let models=maho_ai::models::create_models(Some(maho_ai::models::CreateModelsOptions {auth:Some(Arc::new(FauxAuth)),..Default::default()}));models.set_provider(faux.provider.clone());
    let configuration=json!({"model":{"provider":model.provider,"modelId":model.id},"thinkingLevel":"off","activeToolNames":[]});
    let operation=Operation {meta:OperationMeta {operation_id:"op".into(),lane:"main".into(),source_tip_id:None,started_at:1,intent:OperationIntent::Run {prompt_entry_ids:vec!["prompt".into()]}},state:decode_operation_state(json!({"at":"starting","control":{"status":"running"},"settings":{"compaction":{"enabled":false,"reserveTokens":1000,"keepRecentTokens":2000},"steeringMode":"all","followUpMode":"all","toolExecution":"parallel"},"latestAssistantEntryId":null})).expect("generation fixture must be valid")};
    let session=StorageBackedSession::new(SessionMetadata {id:"generation".into(),created_at:1,storage_version:1,cwd:None,parent_session_id:None,legacy_parent_session_path:None},Arc::new(MemoryStorage::new(Default::default())),StorageBackedSessionOptions::default());
    let prompt=NewEntry::message("prompt",None,maho_agent::types::AgentMessage::from(maho_ai::types::Message::User(maho_ai::types::UserMessage {content:maho_ai::types::UserContent::Text("question".into()),timestamp:1})));
    let mutation=session.begin_mutation(&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid");mutation.commit(vec![insert_entry(prompt),Write::Value(set_value(&branch_tip("main"),json!("prompt"))),Write::Value(set_value(&lane_config("main"),configuration.clone())),Write::Value(set_value(&lane_state("main"),json!({"currentOperationId":"op","lastOperationId":null,"inbox":[]}))),Write::Value(set_value(&operation_meta("op"),serde_json::to_value(&operation.meta).expect("generation fixture must be valid"))),Write::Value(set_value(&operation_state("op"),serde_json::to_value(&operation.state).expect("generation fixture must be valid")))],&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid");mutation.end(&BACKGROUND_CONTEXT).await;
    let config=Arc::new(Config {tools:vec![],resources:Default::default(),stream_options:Default::default(),retry_policy:maho_ai::utils::retry::RetryPolicy {enabled:true,max_retries:3,base_delay_ms:1,max_agent_delay_ms:Some(30000),random:None},compaction:maho_agent::harness::compaction::compaction::CompactionSettings {enabled:false,reserve_tokens:1000,keep_recent_tokens:2000},steering_mode:maho_agent::types::QueueMode::All,follow_up_mode:maho_agent::types::QueueMode::All,tool_execution:ToolExecutionMode::Parallel,tool_context:None,system_prompt:None,to_provider_messages:Arc::new(|messages,_|Box::pin(async move {messages.into_iter().filter_map(|m|m.try_as_llm().cloned()).collect()})),entry_projectors:Default::default()});
    let lane=Arc::new_cyclic(|own|Lane {own:own.clone(),session,state:Mutex::new(LaneState {tip_id:Some("prompt".into()),configuration:serde_json::from_value(configuration).expect("generation fixture must be valid"),inbox:vec![],last_operation_id:None,operation:Some(operation)}),config,models,hooks:HookRegistry::new(Arc::new(|_,_,_,_|Box::pin(async {}))),events:Mutex::new(vec![]),cancel_options:Mutex::new(vec![]),cancel_fails:std::sync::atomic::AtomicBool::new(false)});
    (lane,Drive::new(&DriveOptions {operation_id:"op".into(),wait_for_retry:None,poll_deferred:None},&BACKGROUND_CONTEXT),faux)
}
fn current(lane:&Lane)->OperationState {lane.state().operation.unwrap_or_else(||panic!("operation ended; events: {:?}",lane.events.lock().expect("generation fixture must be valid"))).state}
async fn submit_deferred(lane:&Lane,drive:&Drive) {
    ready(lane,drive).await;
    let _registration=lane.hooks.on(maho_agent::harness::hooks::HookName::BeforeRequest,Arc::new(|_,_|Box::pin(async {Ok(maho_agent::harness::hooks::HookResult::BeforeRequest {stream_options:maho_agent::harness::types::AgentHarnessStreamOptionsPatch {deferred:Some(Some(maho_ai::types::DeferredOption::Enabled(true))),..Default::default()}})})),None);
    run_generation(lane,drive,&current(lane)).await.expect("submit deferred generation");
    _registration.call();
    assert!(matches!(current(lane),OperationState::DeferredSuspended(_)));
}
fn poll_drive()->Drive {Drive::new(&DriveOptions {operation_id:"op".into(),wait_for_retry:None,poll_deferred:Some(true)},&BACKGROUND_CONTEXT)}
async fn cancel_projection(lane:&Lane) {
    let mut projection=lane.state();let state=&mut projection.operation.as_mut().expect("operation exists").state;
    match state {OperationState::AssistantEffectPending(s)=>s.operation.control=Control::CancelRequested {requested_at:10},OperationState::DeferredSuspended(s)=>s.deferred.operation.control=Control::CancelRequested {requested_at:10},OperationState::DeferredEffectPending(s)=>s.deferred.operation.control=Control::CancelRequested {requested_at:10},_=>panic!("unexpected cancellation fixture")}
    lane.session.set_value(&operation_state("op"),serde_json::to_value(&state).expect("cancelled state"),&BACKGROUND_CONTEXT).await.expect("persist cancellation");lane.publish_state(projection);
}
async fn unknown_poll(lane:&Lane)->OperationState {
    let OperationState::DeferredSuspended(mut s)=current(lane) else {panic!("not suspended")};s.deferred.poll=1;
    let state=OperationState::DeferredEffectPending(DeferredEffectPendingOperation {deferred:s.deferred,response_entry_id:(lane.session.id_generator())(Some(1)),usage_id:(lane.session.id_generator())(Some(1)),at:OperationMarker::DeferredEffectPending});
    let OperationState::DeferredEffectPending(p)=&state else {unreachable!()};
    lane.session.append_list(&pending_assistant_frames("op",&p.response_entry_id),json!({"type":"text_delta","contentIndex":0,"delta":"old"}),&BACKGROUND_CONTEXT).await.expect("old poll frame");
    lane.session.set_value(&operation_state("op"),serde_json::to_value(&state).expect("poll state"),&BACKGROUND_CONTEXT).await.expect("store poll state");
    let mut projection=lane.state();projection.operation.as_mut().expect("open operation").state=state.clone();lane.publish_state(projection);state
}
async fn ready(lane:&Lane,drive:&Drive){start_run(lane,drive,&current(lane)).await.expect("generation fixture must be valid");run_checkpoint(lane,drive,&current(lane)).await.expect("generation fixture must be valid");}
fn answer()->maho_ai::types::AssistantMessage {maho_ai::providers::faux::faux_assistant_message("answer",Default::default())}
async fn response(lane:&Lane,drive:&Drive,message:maho_ai::types::AssistantMessage){let OperationState::AssistantReady(s)=current(lane) else {panic!("not ready")};let at=1;let pending=OperationState::AssistantEffectPending(AssistantEffectPendingOperation {operation:s.operation,assistant:s.assistant,attempt:1,response_entry_id:(lane.session.id_generator())(Some(at)),usage_id:(lane.session.id_generator())(Some(at)),intended_output_limit:100,context_window:1000,at:OperationMarker::AssistantEffectPending});let mut projection=lane.state();projection.operation.as_mut().expect("generation fixture must be valid").state=pending.clone();lane.publish_state(projection);lane.session.set_value(&operation_state("op"),serde_json::to_value(&pending).expect("generation fixture must be valid"),&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid");maho_agent::harness::runtime::drive::response::publish_response(lane,drive,&pending,message,false).await.expect("generation fixture must be valid");}

#[tokio::test] async fn consumes_before_run_and_snapshots_ready_generation(){let(lane,drive,_)=fixture().await;ready(&lane,&drive).await;assert!(matches!(current(&lane),OperationState::AssistantReady(_)));assert_eq!(lane.state(),restore_lane(&lane.session,"main",&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid"));}
#[tokio::test] async fn enters_configuration_failure_without_reserving_ids_or_provider(){let(lane,drive,_)=fixture().await;ready(&lane,&drive).await;let mut state=lane.state();if let OperationState::AssistantReady(s)=&mut state.operation.as_mut().expect("generation fixture must be valid").state{s.assistant.generation_context.configuration.active_tool_names.push("missing".into());}lane.publish_state(state);let outcome=run_generation(lane.as_ref(),&drive,&current(&lane)).await.expect("generation fixture must be valid");assert!(matches!(outcome,ProcedureResult::Settled {..}));assert_eq!(lane.session.get_stats(&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid").message_count,1);}
#[tokio::test] async fn fails_missing_captured_model_before_reserving_ids(){let(lane,drive,_)=fixture().await;ready(&lane,&drive).await;lane.models.clear_providers();run_generation(lane.as_ref(),&drive,&current(&lane)).await.expect("generation fixture must be valid");assert!(lane.state().operation.is_none());assert_eq!(lane.session.get_stats(&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid").message_count,1);}
#[tokio::test] async fn declines_intent_when_cancellation_wins_preparation(){let(lane,drive,_)=fixture().await;ready(&lane,&drive).await;let mut state=lane.state();let op=state.operation.as_mut().expect("generation fixture must be valid");if let OperationState::AssistantReady(s)=&mut op.state{s.operation.control=Control::CancelRequested {requested_at:2};}lane.publish_state(state);assert!(matches!(run_generation(lane.as_ref(),&drive,&current(&lane)).await.expect("generation fixture must be valid"),ProcedureResult::Continue));assert!(matches!(current(&lane),OperationState::AssistantReady(_)));}
#[tokio::test] async fn recovers_orphan_without_frames_into_zero_usage_retry(){let(lane,drive,_)=fixture().await;ready(&lane,&drive).await;response(&lane,&drive,answer()).await;let state=current(&lane);assert!(matches!(state,OperationState::Checkpoint(_)));let OperationState::Checkpoint(s)=state else {unreachable!()};let config=lane.state().configuration;let pending=OperationState::AssistantEffectPending(AssistantEffectPendingOperation {operation:s.operation,assistant:AssistantGenerationScope {generation_context:GenerationContext {step_id:"step".into(),trigger_entry_id:"prompt".into(),configuration:config,stream_options:Default::default(),retry_policy:NormalizedRetryPolicy {max_attempts:2,base_delay_ms:1,max_agent_delay_ms:30000},overflow_recovery_used:false}},attempt:1,response_entry_id:(lane.session.id_generator())(Some(1)),usage_id:(lane.session.id_generator())(Some(1)),intended_output_limit:100,context_window:1000,at:OperationMarker::AssistantEffectPending});let mut state=lane.state();state.operation.as_mut().expect("generation fixture must be valid").state=pending.clone();lane.publish_state(state);recover_assistant_generation(lane.as_ref(),&drive,&pending).await.expect("generation fixture must be valid");assert!(matches!(current(&lane),OperationState::AssistantRetryWait(_)));}
#[tokio::test] async fn finishes_no_tool_run_with_cleanup_and_immutable_record(){let(lane,drive,_)=fixture().await;ready(&lane,&drive).await;response(&lane,&drive,answer()).await;let result=run_checkpoint(lane.as_ref(),&drive,&current(&lane)).await.expect("generation fixture must be valid");assert!(matches!(result,ProcedureResult::Settled {..}));assert!(lane.session.get_value(&operation_state("op"),&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid").is_none());let record=lane.session.get_value(&operation_result("op"),&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid").expect("generation fixture must be valid");assert_eq!(record.value["status"],"completed");assert_eq!(lane.state(),restore_lane(&lane.session,"main",&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid"));}
#[tokio::test] async fn drive_leaves_durable_state_unchanged_when_before_drive_fails(){let(lane,drive,_)=fixture().await;let before=lane.state();let _registration=lane.hooks.on(maho_agent::harness::hooks::HookName::BeforeDrive,Arc::new(|_,_|Box::pin(async {Err("hook failed".into())})),None);assert!(drive_operation(lane.as_ref(),&drive).await.is_err());assert_eq!(lane.state(),before);}

async fn queue(lane:&Lane,id:&str,kind:InboxItemKind,payload:serde_json::Value){lane.session.set_value(&pending_entry(id),payload,&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid");let mut state=lane.state();state.inbox.push(InboxItem {entry_id:id.into(),kind});lane.session.set_value(&lane_state("main"),json!({"currentOperationId":"op","lastOperationId":null,"inbox":state.inbox}),&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid");lane.publish_state(state);}
#[tokio::test]
async fn drains_mixed_writes_separating_leaf_and_generation_trigger(){let(lane,drive,_)=fixture().await;start_run(lane.as_ref(),&drive,&current(&lane)).await.expect("generation fixture must be valid");queue(&lane,"message",InboxItemKind::Write,json!({"type":"message","payload":{"role":"user","content":"projecting","timestamp":3}})).await;queue(&lane,"custom",InboxItemKind::Write,json!({"type":"custom","customType":"display-only","payload":{"value":true}})).await;run_checkpoint(lane.as_ref(),&drive,&current(&lane)).await.expect("generation fixture must be valid");assert_eq!(lane.state().tip_id.as_deref(),Some("custom"));let OperationState::AssistantReady(s)=current(&lane) else {panic!("not ready")};assert_eq!(s.assistant.generation_context.trigger_entry_id,"message");assert!(lane.state().inbox.is_empty());assert_eq!(lane.state(),restore_lane(&lane.session,"main",&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid"));}
#[tokio::test]
async fn preserves_custom_only_checkpoint_routing(){let(lane,drive,_)=fixture().await;start_run(lane.as_ref(),&drive,&current(&lane)).await.expect("generation fixture must be valid");let mut state=lane.state();if let OperationState::Checkpoint(s)=&mut state.operation.as_mut().expect("generation fixture must be valid").state{s.checkpoint.continuation=Continuation::MayFinish {include_final_assistant:false};}lane.publish_state(state);queue(&lane,"custom",InboxItemKind::Write,json!({"type":"custom","customType":"display-only","payload":{}})).await;let _registration=lane.hooks.on(maho_agent::harness::hooks::HookName::BeforeRunEnd,Arc::new(|_,_|Box::pin(async {Ok(maho_agent::harness::hooks::HookResult::BeforeRunEnd {follow_up:"continue".into()})})),None);run_checkpoint(lane.as_ref(),&drive,&current(&lane)).await.expect("generation fixture must be valid");let OperationState::AssistantReady(s)=current(&lane) else {panic!("not ready")};let entry=lane.session.get_entry(&s.assistant.generation_context.trigger_entry_id,&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid").expect("generation fixture must be valid");assert_eq!(entry.parent_id.as_deref(),Some("custom"));assert!(lane.state().inbox.is_empty());}
#[tokio::test]
async fn drops_stale_finish_followup_when_input_arrives_during_hook(){let(lane,drive,_)=fixture().await;start_run(lane.as_ref(),&drive,&current(&lane)).await.expect("generation fixture must be valid");let mut state=lane.state();if let OperationState::Checkpoint(s)=&mut state.operation.as_mut().expect("generation fixture must be valid").state{s.checkpoint.continuation=Continuation::MayFinish {include_final_assistant:false};}lane.publish_state(state);let weak=Arc::downgrade(&lane);let _registration=lane.hooks.on(maho_agent::harness::hooks::HookName::BeforeRunEnd,Arc::new(move |_,_|{let lane=weak.upgrade().expect("generation fixture must be valid");Box::pin(async move {queue(&lane,"arrived",InboxItemKind::Steer,json!({"type":"message","payload":{"role":"user","content":"new input","timestamp":3}})).await;Ok(maho_agent::harness::hooks::HookResult::BeforeRunEnd {follow_up:"stale".into()})})}),None);run_checkpoint(lane.as_ref(),&drive,&current(&lane)).await.expect("generation fixture must be valid");let OperationState::AssistantReady(s)=current(&lane) else {panic!("not ready")};assert_eq!(s.assistant.generation_context.trigger_entry_id,"arrived");assert_eq!(lane.session.get_stats(&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid").message_count,2);}
#[tokio::test]
async fn commits_intent_before_provider_and_settles_reserved_ids(){let(lane,drive,faux)=fixture().await;ready(&lane,&drive).await;let weak=Arc::downgrade(&lane);let model=faux.get_model(None).expect("generation fixture must be valid");faux.set_responses(vec![maho_ai::providers::faux::FauxResponseStep::Factory(Arc::new(move |_,_,_,_|{let lane=weak.upgrade().expect("generation fixture must be valid");let model=model.clone();Box::pin(async move {assert!(matches!(current(&lane),OperationState::AssistantEffectPending(_)));assert_eq!(lane.session.get_value(&operation_state("op"),&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid").expect("generation fixture must be valid").value["at"],"assistant.effect_pending");let mut response=answer();response.api=model.api;response.provider=model.provider;response.model=model.id;response})}))]);run_generation(lane.as_ref(),&drive,&current(&lane)).await.expect("generation fixture must be valid");assert!(matches!(current(&lane),OperationState::Checkpoint(_)));assert_eq!(lane.session.get_stats(&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid").message_count,2);assert_eq!(lane.state(),restore_lane(&lane.session,"main",&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid"));}
#[tokio::test]
async fn ordinary_drive_calls_before_drive_once(){let(lane,drive,faux)=fixture().await;let count=Arc::new(std::sync::atomic::AtomicUsize::new(0));let captured=count.clone();let _registration=lane.hooks.on(maho_agent::harness::hooks::HookName::BeforeDrive,Arc::new(move |_,_|{captured.fetch_add(1,std::sync::atomic::Ordering::SeqCst);Box::pin(async {Ok(maho_agent::harness::hooks::HookResult::None)})}),None);faux.set_responses(vec![answer().into()]);let outcome=drive_operation(lane.as_ref(),&drive).await.expect("generation fixture must be valid");assert!(matches!(outcome,maho_agent::harness::agent_harness::DriveOutcome::Settled {..}));assert_eq!(count.load(std::sync::atomic::Ordering::SeqCst),1);}
#[tokio::test]
async fn durable_retry_wait_without_local_wait_does_not_write(){let(lane,drive,_)=fixture().await;ready(&lane,&drive).await;let mut message=answer();message.stop_reason=maho_ai::types::StopReason::Error;message.error_message=Some("429 rate limit".into());response(&lane,&drive,message).await;let state=current(&lane);assert!(matches!(state,OperationState::AssistantRetryWait(_)));let mut projection=lane.state();if let OperationState::AssistantRetryWait(s)=&mut projection.operation.as_mut().expect("generation fixture must be valid").state{s.retry_wait.not_before=i64::MAX;}lane.publish_state(projection);let before=lane.state();let outcome=run_retry_wait(lane.as_ref(),&drive,&current(&lane)).await.expect("generation fixture must be valid");assert!(matches!(outcome,ProcedureResult::Waiting {..}));assert_eq!(lane.state(),before);}
#[tokio::test]
async fn retry_deadline_commits_ready_and_emits_retry_start(){let(lane,drive,_)=fixture().await;ready(&lane,&drive).await;let mut message=answer();message.stop_reason=maho_ai::types::StopReason::Error;message.error_message=Some("429 rate limit".into());response(&lane,&drive,message).await;let mut projection=lane.state();if let OperationState::AssistantRetryWait(s)=&mut projection.operation.as_mut().expect("generation fixture must be valid").state{s.retry_wait.not_before=0;}lane.publish_state(projection);run_retry_wait(lane.as_ref(),&drive,&current(&lane)).await.expect("generation fixture must be valid");assert!(matches!(current(&lane),OperationState::AssistantReady(_)));assert!(lane.events.lock().expect("generation fixture must be valid").iter().any(|e|e.event_type()=="retry_start"));}

#[tokio::test]
async fn deferred_wait_without_permit_preserves_state(){let(lane,drive,faux)=fixture().await;ready(&lane,&drive).await;let model=faux.get_model(None).expect("generation fixture must be valid");let mut message=answer();message.api=model.api.clone();message.provider=model.provider.clone();message.model=model.id.clone();message.stop_reason=maho_ai::types::StopReason::Deferred;message.deferred=Some(serde_json::from_value(json!({"id":"handle","api":model.api,"provider":model.provider,"modelId":model.id})).expect("generation fixture must be valid"));response(&lane,&drive,message).await;let before=lane.state();assert!(matches!(maho_agent::harness::runtime::drive::deferred::run_deferred(lane.as_ref(),&drive,&current(&lane)).await.expect("generation fixture must be valid"),ProcedureResult::Waiting {..}));assert_eq!(lane.state(),before);}
#[tokio::test]
async fn reconciles_cancelled_checkpoint_without_ordinary_hooks(){let(lane,drive,_)=fixture().await;ready(&lane,&drive).await;let mut projection=lane.state();if let OperationState::AssistantReady(s)=&mut projection.operation.as_mut().expect("generation fixture must be valid").state{s.operation.control=Control::CancelRequested {requested_at:2};}lane.publish_state(projection);let result=maho_agent::harness::runtime::drive::reconcile::reconcile_operation(lane.as_ref(),&drive).await.expect("generation fixture must be valid");let ProcedureResult::Settled {outcome}=result else {panic!("not settled")};assert_eq!(outcome.status,TerminalStatus::Aborted);assert!(lane.state().operation.is_none());}
#[tokio::test]
async fn keeps_deferred_cleanup_signal_separate_from_operation_abort(){let(_,drive,_)=fixture().await;let cancellation=maho_agent::harness::execution::effect_gate::Cancellation::new();cancellation.resolve();drive.begin_abort(cancellation);drive.signal_abort();assert!(drive.gate.signal().aborted());assert!(!drive.close_signal.aborted());drive.close_gate("closed".into());assert!(drive.close_signal.aborted());}

#[tokio::test]
async fn ignores_deferred_provider_cancellation_failure(){let(lane,drive,faux)=fixture().await;faux.set_responses(vec![answer().into()]);submit_deferred(&lane,&drive).await;cancel_projection(&lane).await;lane.cancel_fails.store(true,std::sync::atomic::Ordering::SeqCst);let outcome=drive_operation(lane.as_ref(),&drive).await.expect("reconcile remote failure");assert!(matches!(outcome,maho_agent::harness::agent_harness::DriveOutcome::Settled {..}));assert!(lane.state().operation.is_none());{let options=lane.cancel_options.lock().expect("cancel options");assert_eq!(options.len(),1);assert!(!options[0].signal.as_ref().expect("cleanup signal").aborted());assert!(drive.gate.signal().aborted());}assert_eq!(lane.state(),restore_lane(&lane.session,"main",&BACKGROUND_CONTEXT).await.expect("restore cancelled lane"));}
#[tokio::test]
async fn cancelled_effect_can_resume_between_response_and_terminal_cleanup(){let(lane,drive,faux)=fixture().await;faux.set_responses(vec![answer().into()]);submit_deferred(&lane,&drive).await;let pending=unknown_poll(&lane).await;let OperationState::DeferredEffectPending(p)=pending else {unreachable!()};lane.session.delete_list(&pending_assistant_frames("op",&p.response_entry_id),&BACKGROUND_CONTEXT).await.expect("remove malformed test frame");cancel_projection(&lane).await;assert_eq!(maho_agent::harness::runtime::drive::reconcile::reconcile_operation(lane.as_ref(),&drive).await.expect("settle cancelled effect"),ProcedureResult::Continue);assert!(matches!(current(&lane),OperationState::Checkpoint(_)));let entry=lane.session.get_entry(&p.response_entry_id,&BACKGROUND_CONTEXT).await.expect("response entry").expect("committed response");let Some(maho_ai::types::Message::Assistant(message))=entry.kind.message().and_then(|m|m.try_as_llm()) else {panic!("not assistant")};assert_eq!(message.stop_reason,maho_ai::types::StopReason::Aborted);assert!(lane.session.get_value(&operation_result("op"),&BACKGROUND_CONTEXT).await.expect("no result yet").is_none());let resumed=poll_drive();let result=drive_operation(lane.as_ref(),&resumed).await.expect("resume cleanup");let maho_agent::harness::agent_harness::DriveOutcome::Settled {outcome}=result else {panic!("not settled")};assert_eq!(outcome.status,TerminalStatus::Aborted);assert!(lane.state().operation.is_none());}
#[tokio::test]
async fn deferred_poll_declines_intent_when_cancellation_wins_hook(){let(lane,drive,faux)=fixture().await;faux.set_responses(vec![answer().into()]);submit_deferred(&lane,&drive).await;let started=Arc::new(tokio::sync::Notify::new());let release=Arc::new(tokio::sync::Notify::new());let begun=started.clone();let unblock=release.clone();let _registration=lane.hooks.on(maho_agent::harness::hooks::HookName::BeforeRequest,Arc::new(move |_,_|{let begun=begun.clone();let unblock=unblock.clone();Box::pin(async move {let released=unblock.notified();tokio::pin!(released);released.as_mut().enable();begun.notify_one();released.await;Ok(maho_agent::harness::hooks::HookResult::None)})}),None);let poll=Arc::new(poll_drive());let polling={let lane=lane.clone();let poll=poll.clone();tokio::spawn(async move {maho_agent::harness::runtime::drive::deferred::run_deferred(lane.as_ref(),&poll,&current(&lane)).await})};tokio::time::timeout(std::time::Duration::from_secs(5),started.notified()).await.expect("hook start signal");cancel_projection(&lane).await;release.notify_one();assert_eq!(tokio::time::timeout(std::time::Duration::from_secs(5),polling).await.expect("poll finish signal").expect("poll task").expect("cancelled poll"),ProcedureResult::Continue);assert_eq!(faux.state().deferred_fetch_count,0);assert_eq!(*poll.deferred_permits.lock().expect("permit lock"),1);let OperationState::DeferredSuspended(s)=current(&lane) else {panic!("not suspended")};assert_eq!(s.deferred.operation.control,Control::CancelRequested {requested_at:10});assert_eq!(lane.state(),restore_lane(&lane.session,"main",&BACKGROUND_CONTEXT).await.expect("restore cancelled poll"));}

#[tokio::test]
async fn deferred_poll_consumes_one_permit_and_forces_captured_options(){let(lane,drive,faux)=fixture_with_options(maho_ai::providers::faux::RegisterFauxProviderOptions {deferred:Some(maho_ai::providers::faux::FauxDeferredOptions {pending_fetches:Some(1),poll_after_ms:None}),..Default::default()}).await;faux.set_responses(vec![answer().into()]);submit_deferred(&lane,&drive).await;assert_eq!(faux.state().deferred_fetch_count,0);let poll=poll_drive();let seen=Arc::new(Mutex::new(None));let captured=seen.clone();let _registration=lane.hooks.on(maho_agent::harness::hooks::HookName::BeforeRequest,Arc::new(move |event,_|{*captured.lock().expect("hook options lock")=Some(event.stream_options);Box::pin(async {Ok(maho_agent::harness::hooks::HookResult::None)})}),None);maho_agent::harness::runtime::drive::deferred::run_deferred(lane.as_ref(),&poll,&current(&lane)).await.expect("poll deferred");assert_eq!(*poll.deferred_permits.lock().expect("permit lock"),0);assert_eq!(seen.lock().expect("hook options lock").as_ref().expect("called hook").deferred,Some(maho_ai::types::DeferredOption::Enabled(false)));let OperationState::DeferredSuspended(s)=current(&lane) else {panic!("not suspended")};assert_eq!(s.deferred.poll,1);assert_eq!(faux.state().deferred_fetch_count,1);{let events=lane.events.lock().expect("events lock");assert_eq!(events.iter().rev().take(2).map(|e|e.event_type()).collect::<Vec<_>>(),vec!["run_suspend","turn_end"]);}assert!(matches!(maho_agent::harness::runtime::drive::deferred::run_deferred(lane.as_ref(),&poll,&current(&lane)).await.expect("no second poll"),ProcedureResult::Waiting {..}));assert_eq!(faux.state().deferred_fetch_count,1);assert_eq!(lane.state(),restore_lane(&lane.session,"main",&BACKGROUND_CONTEXT).await.expect("restore poll"));}
#[tokio::test]
async fn deferred_tools_use_poll_identity_and_reserved_id_timestamp(){let(lane,drive,faux)=fixture().await;let message=maho_ai::providers::faux::faux_assistant_message(maho_ai::providers::faux::faux_tool_call("lookup",Default::default(),Some("call")),maho_ai::providers::faux::FauxAssistantMessageOptions {stop_reason:Some(maho_ai::types::StopReason::ToolUse),..Default::default()});faux.set_responses(vec![message.into()]);submit_deferred(&lane,&drive).await;let OperationState::DeferredSuspended(before)=current(&lane) else {panic!("not suspended")};maho_agent::harness::runtime::drive::deferred::run_deferred(lane.as_ref(),&poll_drive(),&current(&lane)).await.expect("poll tools");let OperationState::Tools(s)=current(&lane) else {panic!("not tools")};assert_eq!(s.batch.turn_id,format!("{}:poll:1",before.deferred.step_id));assert_eq!(&s.batch.calls[0].result_entry_id()[..13],&s.operation.latest_assistant_entry_id.expect("assistant id")[..13]);assert_eq!(lane.state(),restore_lane(&lane.session,"main",&BACKGROUND_CONTEXT).await.expect("restore tools"));}
#[tokio::test]
async fn unknown_deferred_poll_replaces_ids_and_deletes_abandoned_frames(){let(lane,drive,faux)=fixture().await;faux.set_responses(vec![answer().into()]);submit_deferred(&lane,&drive).await;let unknown=unknown_poll(&lane).await;let OperationState::DeferredEffectPending(old)=&unknown else {unreachable!()};assert!(matches!(maho_agent::harness::runtime::drive::deferred::run_deferred(lane.as_ref(),&drive,&unknown).await.expect("wait unknown"),ProcedureResult::Waiting {..}));assert_eq!(lane.session.read_list(&pending_assistant_frames("op",&old.response_entry_id),None,&BACKGROUND_CONTEXT).await.expect("read old frames").len(),1);maho_agent::harness::runtime::drive::deferred::run_deferred(lane.as_ref(),&poll_drive(),&unknown).await.expect("recover poll");assert!(matches!(current(&lane),OperationState::Checkpoint(_)));assert!(lane.session.get_entry(&old.response_entry_id,&BACKGROUND_CONTEXT).await.expect("read old entry").is_none());assert!(lane.session.read_list(&pending_assistant_frames("op",&old.response_entry_id),None,&BACKGROUND_CONTEXT).await.expect("read deleted frames").is_empty());assert!(lane.events.lock().expect("events lock").iter().any(|e|e.recovery==Some(true)));assert_eq!(faux.state().deferred_fetch_count,1);}
#[tokio::test]
async fn unknown_deferred_poll_missing_model_keeps_permit_and_cleans_frames(){let(lane,drive,faux)=fixture().await;faux.set_responses(vec![answer().into()]);submit_deferred(&lane,&drive).await;let unknown=unknown_poll(&lane).await;let OperationState::DeferredEffectPending(old)=&unknown else {unreachable!()};lane.models.delete_provider("faux");let poll=poll_drive();assert!(matches!(maho_agent::harness::runtime::drive::deferred::run_deferred(lane.as_ref(),&poll,&unknown).await.expect("configuration failure"),ProcedureResult::Settled {..}));assert_eq!(*poll.deferred_permits.lock().expect("permit lock"),1);assert_eq!(faux.state().deferred_fetch_count,0);assert!(lane.state().operation.is_none());assert!(lane.session.read_list(&pending_assistant_frames("op",&old.response_entry_id),None,&BACKGROUND_CONTEXT).await.expect("deleted frames").is_empty());}

#[tokio::test]
async fn before_run_injected_messages_are_committed_and_published(){let(lane,drive,_)=fixture().await;let _registration=lane.hooks.on(maho_agent::harness::hooks::HookName::BeforeRun,Arc::new(|_,_|Box::pin(async {Ok(maho_agent::harness::hooks::HookResult::BeforeRun {messages:vec![maho_ai::types::Message::User(maho_ai::types::UserMessage {content:maho_ai::types::UserContent::Text("injected".into()),timestamp:2}).into()]})})),None);start_run(lane.as_ref(),&drive,&current(&lane)).await.expect("generation fixture must be valid");assert_eq!(lane.session.get_stats(&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid").message_count,2);assert!(lane.events.lock().expect("generation fixture must be valid").iter().any(|event|event.event_type()=="entry_added"));let OperationState::Checkpoint(s)=current(&lane) else {panic!("not checkpoint")};assert_eq!(Some(s.checkpoint.trigger_entry_id),lane.state().tip_id);}
#[tokio::test]
async fn recovers_committed_frames_without_provider_or_response_hook(){let(lane,drive,_)=fixture().await;ready(&lane,&drive).await;let OperationState::AssistantReady(s)=current(&lane) else {panic!("not ready")};let pending=OperationState::AssistantEffectPending(AssistantEffectPendingOperation {operation:s.operation,assistant:s.assistant,attempt:1,response_entry_id:(lane.session.id_generator())(Some(1)),usage_id:(lane.session.id_generator())(Some(1)),intended_output_limit:100,context_window:1000,at:OperationMarker::AssistantEffectPending});let OperationState::AssistantEffectPending(effect)=&pending else {unreachable!()};let mut partial=answer();partial.stop_reason=maho_ai::types::StopReason::Pending;lane.session.append_list(&pending_assistant_frames("op",&effect.response_entry_id),serde_json::to_value(maho_ai::utils::assistant_message_frame::AssistantMessageFrame::Start {partial:Box::new(partial)}).expect("generation fixture must be valid"),&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid");let mut projection=lane.state();projection.operation.as_mut().expect("generation fixture must be valid").state=pending.clone();lane.publish_state(projection);let count=Arc::new(std::sync::atomic::AtomicUsize::new(0));let captured=count.clone();let _registration=lane.hooks.on(maho_agent::harness::hooks::HookName::AfterResponse,Arc::new(move |_,_|{captured.fetch_add(1,std::sync::atomic::Ordering::SeqCst);Box::pin(async {Ok(maho_agent::harness::hooks::HookResult::None)})}),None);recover_assistant_generation(lane.as_ref(),&drive,&pending).await.expect("generation fixture must be valid");assert_eq!(count.load(std::sync::atomic::Ordering::SeqCst),0);let entry=lane.session.get_entry(&effect.response_entry_id,&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid").expect("generation fixture must be valid");let Some(maho_ai::types::Message::Assistant(message))=entry.kind.message().and_then(|m|m.try_as_llm()) else {panic!("not assistant")};assert_eq!(message.content,answer().content);assert_eq!(message.usage,maho_ai::types::Usage::default());}
#[tokio::test]
async fn retries_live_provider_error_with_durable_wait_event(){let(lane,drive,_)=fixture().await;ready(&lane,&drive).await;let mut message=answer();message.stop_reason=maho_ai::types::StopReason::Error;message.error_message=Some("429 rate limit".into());response(&lane,&drive,message).await;let OperationState::AssistantRetryWait(s)=current(&lane) else {panic!("no retry")};assert_eq!(s.retry_wait.next_attempt,2);assert!(lane.events.lock().expect("generation fixture must be valid").iter().any(|e|e.event_type()=="retry_scheduled"));assert_eq!(lane.state(),restore_lane(&lane.session,"main",&BACKGROUND_CONTEXT).await.expect("generation fixture must be valid"));}
#[tokio::test]
async fn local_retry_wait_is_abort_aware(){let(lane,_,_)=fixture().await;let drive=Drive::new(&DriveOptions {operation_id:"op".into(),wait_for_retry:Some(true),poll_deferred:None},&BACKGROUND_CONTEXT);ready(&lane,&drive).await;let mut message=answer();message.stop_reason=maho_ai::types::StopReason::Error;message.error_message=Some("429 rate limit".into());response(&lane,&drive,message).await;let mut projection=lane.state();if let OperationState::AssistantRetryWait(s)=&mut projection.operation.as_mut().expect("generation fixture must be valid").state{s.retry_wait.not_before=i64::MAX;}lane.publish_state(projection);let cancellation=maho_agent::harness::execution::effect_gate::Cancellation::new();cancellation.resolve();drive.begin_abort(cancellation);drive.signal_abort();assert!(run_retry_wait(lane.as_ref(),&drive,&current(&lane)).await.is_err());assert!(matches!(current(&lane),OperationState::AssistantRetryWait(_)));}
