[package]
name = "maho-ext-history-search"
version.workspace = true
edition.workspace = true
publish.workspace = true
license = "MIT"

[dependencies]
maho-tui = { path = "../../maho-tui" }
maho-interactive = { path = "../../maho-interactive" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
chrono = "=0.4.43"

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
