use super::ask_user_question_state::*;
use crate::theme::{Theme, ThemeColor as C};
pub fn render_title(t:&Theme,label:&str)->String { format!("{}{}",t.fg(C::Accent,&t.bold("Ask user")),if label.is_empty(){String::new()}else{t.fg(C::Muted,&format!(" · {label}"))}) }
pub fn render_tab_labels(t:&Theme,s:&AskUserQuestionState)->Vec<String>{let mut tabs:Vec<_>=s.request.questions.iter().enumerate().map(|(i,q)|{let label=format!("{}{}",q.header,if s.is_answered(&q.id){t.fg(C::Success," ✓")}else{String::new()});if i==s.active_tab_index(){t.fg(C::Accent,&t.bold(&format!("→ {label}")))}else{t.fg(C::Muted,&format!("  {label}"))}}).collect();tabs.push(if s.active_tab_index()==s.request.questions.len(){t.fg(C::Accent,&t.bold("→ Submit"))}else{t.fg(C::Muted,"  Submit")});tabs}
pub fn render_tab_bar(t:&Theme,s:&AskUserQuestionState)->String{render_tab_labels(t,s).join("  ")}
pub fn render_question_line(t:&Theme,q:&Question)->String{t.fg(C::Text,&q.question)}
pub fn render_question_list(t:&Theme,s:&AskUserQuestionState)->Vec<String>{let q=s.active_question();let mut lines=Vec::new();for(i,o)in q.options.iter().enumerate(){let prefix=if i==s.highlight_index&&s.focus==QuestionFocus::Options{t.fg(C::Accent,"→ ")}else{"  ".into()};let marker=if s.is_selected(&q.id,&o.label){t.fg(C::Success," ✓")}else{String::new()};lines.push(format!("{prefix}{}. {}{marker}",i+1,t.fg(C::Text,&o.label)));if let Some(d)=&o.description&& !d.is_empty(){lines.push(t.fg(C::Muted,&format!("     {d}")));}}let prefix=if s.highlight_index==s.own_answer_row_index()&&s.focus==QuestionFocus::Options{t.fg(C::Accent,"→ ")}else{"  ".into()};lines.push(format!("{prefix}{}{}",t.fg(C::Muted,OWN_ANSWER_LABEL),s.text_for(&q.id).map_or(String::new(),|v|t.fg(C::Text,&format!(": {v}")))));lines}
pub fn render_submit_summary(t:&Theme,s:&AskUserQuestionState)->Vec<String>{let answers=s.answers();s.request.questions.iter().enumerate().map(|(i,q)|{let prefix=if s.focus==QuestionFocus::Submit&&s.submit_row_index==i{t.fg(C::Accent,"→ ")}else{"  ".into()};match answers.get(&q.id){None=>format!("{prefix}{}",t.fg(C::Warning,&format!("{}: unanswered",q.header))),Some(a)=>format!("{prefix}{}: {}",q.header,if a.selected.is_empty(){a.text.clone().unwrap_or_default()}else{a.selected.join(", ")})}}).collect()}
pub fn render_own_answer_label(t:&Theme)->String{t.fg(C::Muted,"Your answer (enter to save, ↑↓ back to options, esc to discard)")}
pub fn render_comment_label(t:&Theme)->String{t.fg(C::Muted,COMMENT_LABEL)}
pub fn render_notice(t:&Theme,notice:Option<&str>)->String{notice.map_or(String::new(),|n|t.fg(C::Warning,&format!("! {n}")))}
pub fn render_submit_line(t:&Theme,s:&AskUserQuestionState)->String{let line=t.fg(C::Accent,&t.bold(&format!("Submit ({}/{} answered)",s.answered_count(),s.request.questions.len())));if s.focus==QuestionFocus::Submit{return line;}format!("{line}{}",t.fg(C::Muted,if s.focus==QuestionFocus::Options&&s.active_question().multi_select{" — Enter toggles; Tab to Submit"}else{" — Enter advances"}))}
fn hint(t:&Theme,key:&str,label:&str)->String{format!("{} {}",t.fg(C::Dim,key),t.fg(C::Muted,label))}
pub fn render_hints_line(t:&Theme,s:&AskUserQuestionState)->String{let pairs:Vec<(&str,&str)>=match s.focus{QuestionFocus::Submit=>if s.is_comment_focused(){vec![("enter","submit"),("↑","review answers"),("shift+tab","back"),("tab","next question"),("esc","back")]}else{vec![("enter","edit answer"),("↑↓","move"),("tab","next question"),("esc","back")]},QuestionFocus::OwnAnswer=>vec![("enter","save and next"),("↑↓","back to options"),("tab","next question"),("esc","discard")],QuestionFocus::Options=>vec![("↑↓","move"),("1-9","select"),("space",if s.active_question().multi_select{"toggle"}else{"select"}),("enter",if s.active_question().multi_select{"toggle"}else{"next"}),("tab",if s.active_question().multi_select{"next / Submit"}else{"next question"}),("c","comment"),("esc","cancel")]};pairs.into_iter().map(|(k,l)|hint(t,k,l)).collect::<Vec<_>>().join("  ")}
