use super::{ask_user_question::AskUserQuestionComponent,ask_user_question_state::{QuestionFocus,QuestionStatus}};
use maho_tui::{keybindings::get_keybindings,keys::matches_key,tui::Component};
fn printable(d:&str)->bool{d.encode_utf16().count()==1&&d>=" "&&d!="\x7f"}
pub fn handle_ask_user_key_input(c:&mut AskUserQuestionComponent,d:&str){let kb=get_keybindings();let confirm=kb.matches(d,"tui.select.confirm")||d=="\n";let cancel=kb.matches(d,"tui.select.cancel");let up=kb.matches(d,"tui.select.up");let down=kb.matches(d,"tui.select.down");let tab=matches_key(d,"tab");let backtab=matches_key(d,"shift+tab");if matches_key(d,"ctrl+c"){c.finish(QuestionStatus::Cancelled,None);return;}if matches_key(d,"ctrl+enter"){if c.state.focus==QuestionFocus::OwnAnswer{c.commit_own_answer();}c.attempt_submit();return;}
match c.state.focus{
QuestionFocus::OwnAnswer=>{if confirm{c.commit_own_answer();c.state.advance();}else if cancel{c.own_answer_input.set_value("");let row=c.state.own_answer_row_index();c.state.leave_own_answer(row as isize);}else if up||down||tab||backtab{if !c.own_answer_input.get_value().trim().is_empty(){c.commit_own_answer();}else{c.own_answer_input.set_value("");}if tab||backtab{c.state.switch_tab(if tab{1}else{-1});}else{let row=c.state.own_answer_row_index() as isize;c.state.leave_own_answer(row-if up{1}else{0});}}else if matches_key(d,"backspace")&&c.own_answer_input.get_value().is_empty(){let row=c.state.own_answer_row_index();c.state.leave_own_answer(row as isize);}else{c.own_answer_input.handle_input(d);c.emit_progress();}}
QuestionFocus::Submit=>{if kb.matches(d,"tui.input.submit")||d=="\n"{if c.state.is_comment_focused(){c.attempt_submit();}else{c.state.jump_to_question(c.state.submit_row_index);}}else if cancel{if c.state.request.wait_for_answer{c.state.return_to_options();}else{c.finish(QuestionStatus::Cancelled,None);}}else if up||down{c.state.move_submit_row(if up{-1}else{1});}else if tab||backtab{c.state.switch_tab(if tab{1}else{-1});}else{let has_text=!c.comment_input.get_value().is_empty();if (matches_key(d,"left")||matches_key(d,"right"))&&(!c.state.is_comment_focused()||!has_text){c.state.switch_tab(if matches_key(d,"right"){1}else{-1});}else if matches_key(d,"backspace")&&c.state.is_comment_focused()&&!has_text{c.state.move_submit_row(-1);}else{if !c.state.is_comment_focused(){if !printable(d){return;}c.state.focus_comment();}c.comment_input.handle_input(d);c.state.comment=Some(c.comment_input.get_value().into());c.emit_progress();}}}
QuestionFocus::Options=>{if cancel{if !c.state.request.wait_for_answer||c.state.request_dismiss(){c.finish(QuestionStatus::Cancelled,None);}}else if tab||matches_key(d,"right"){c.state.switch_tab(1);}else if backtab||matches_key(d,"left"){c.state.switch_tab(-1);}else if up||d=="k"{c.state.highlight_index=c.state.highlight_index.saturating_sub(1);}else if down||d=="j"{c.state.highlight_index=(c.state.highlight_index+1).min(c.state.own_answer_row_index());}else if matches_key(d,"backspace"){let id=c.state.active_question().id.clone();c.state.clear_answer(&id);c.emit_progress();}else if d.len()==1&&d>="1"&&d<="9"{let i=usize::from(d.as_bytes()[0]-b'1');let q=c.state.active_question().clone();if let Some(o)=q.options.get(i){c.state.activate_option(&q.id,&o.label);c.emit_progress();if !q.multi_select{if c.state.request.questions.len()==1{c.attempt_submit();}else{c.state.advance();}}}}else if matches_key(d,"space")||confirm{activate_highlighted(c,confirm);}else if d=="c"{c.state.enter_submit();}else if printable(d){c.open_own_answer(Some(d));}}
}}
fn activate_highlighted(c:&mut AskUserQuestionComponent,confirm:bool){let i=c.state.highlight_index;if i==c.state.own_answer_row_index(){c.open_own_answer(None);return;}let q=c.state.active_question().clone();let Some(o)=q.options.get(i)else{return;};c.state.activate_option(&q.id,&o.label);c.emit_progress();if confirm&&!q.multi_select{if c.state.request.questions.len()==1{c.attempt_submit();}else{c.state.advance();}}}
