[package]
name = "maho-ext-api"
version.workspace = true
edition.workspace = true
publish.workspace = true
license = "MIT"

[dependencies]
maho-ai = { path = "../maho-ai" }
maho-agent = { path = "../maho-agent" }
maho-tools = { path = "../maho-tools" }
maho-tui = { path = "../maho-tui" }
serde = "=1.0.228"
serde_json = "=1.0.149"

[lints]
workspace = true
