use maho_ext_pi_goal::goal::{format::*,types::*};
fn goal()->Goal{Goal{id:"goal-1".into(),thread_id:"thread-1".into(),objective:"Port /goal as a pi extension".into(),status:GoalStatus::Active,token_budget:None,tokens_used:0,time_used_seconds:120,created_at:1_777_766_400,updated_at:1_777_766_400,last_started_at:None,completed_at:None,blocked_reason:None,blocked_at:None}}
#[test]fn elapsed_units(){for(value,expected)in[(0.0,"0s"),(59.0,"59s"),(60.0,"1m"),(1800.0,"30m"),(5400.0,"1h 30m"),(7200.0,"2h"),(86399.0,"23h 59m"),(86400.0,"1d 0h 0m"),(258120.0,"2d 23h 42m")]{assert_eq!(format_goal_elapsed_seconds(value),expected);}}
#[test]fn compact_tokens(){assert_eq!(format_tokens_compact(999.0),"999");assert_eq!(format_tokens_compact(1500.0),"1.5K");assert_eq!(format_tokens_compact(2_000_000.0),"2M");}
#[test]fn completed_iso_date_uses_javascript_expanded_year(){let mut g=goal();g.completed_at=Some(253_402_300_800);let text=format_goal_for_tool(Some(&g)).expect("date");assert_eq!(text.lines().last().expect("date line").split_once(": ").expect("date field").1,"+010000-01-01T00:00:00.000Z");g.completed_at=Some(8_640_000_000_000);let text=format_goal_for_tool(Some(&g)).expect("maximum date");assert_eq!(text.lines().last().expect("date line").split_once(": ").expect("date field").1,"+275760-09-13T00:00:00.000Z");g.completed_at=Some(8_640_000_000_001);assert!(format_goal_for_tool(Some(&g)).is_err());}
#[test]fn compact_tokens_binary_halfway_rounds_away_from_zero(){for(value,expected)in[(1250.0,"1.3K"),(-1250.0,"-1.3K"),(1750.0,"1.8K"),(1_250_000.0,"1.3M"),(-1_250_000.0,"-1.3M"),(1150.0,"1.1K"),(1050.0,"1.1K")]{assert_eq!(format_tokens_compact(value),expected);}}
#[test]fn nonfinite_and_negative_zero_numbers_match_javascript(){assert_eq!(format_tokens_compact(f64::NAN),"NaN");assert_eq!(format_tokens_compact(f64::INFINITY),"InfinityM");assert_eq!(format_tokens_compact(f64::NEG_INFINITY),"-InfinityM");assert_eq!(format_tokens_compact(-0.5),"0");assert_eq!(format_goal_elapsed_seconds(f64::NAN),"NaNh NaNm");assert_eq!(format_goal_elapsed_seconds(f64::INFINITY),"Infinityd NaNh NaNm");assert_eq!(format_goal_elapsed_seconds(f64::NEG_INFINITY),"0s");}
#[test]fn tool_display_no_budget(){let mut g=goal();g.tokens_used=1200;g.time_used_seconds=65;let text=format_goal_for_tool(Some(&g)).unwrap();assert!(!text.to_lowercase().contains("budget"));assert!(!text.to_lowercase().contains("remaining"));assert!(text.contains(&format_tokens_compact(1200.0)));}
#[test]fn blocked_display(){let mut g=goal();g.status=GoalStatus::Blocked;g.blocked_reason=Some("Waiting on a product decision".into());g.blocked_at=Some(1_777_766_450);let text=format_goal_for_tool(Some(&g)).unwrap();assert!(text.contains(g.blocked_reason.as_deref().unwrap()));assert!(text.contains(goal_status_label(g.status)));}
#[test]fn machine_snapshot_no_budget(){let mut g=goal();g.status=GoalStatus::Complete;g.tokens_used=3250;g.time_used_seconds=75;g.completed_at=Some(1_777_766_500);let value=serde_json::to_value(goal_tool_response(Some(&g))).unwrap();assert_eq!(value["goal"]["threadId"],"thread-1");assert_eq!(value["goal"]["status"],"complete");assert_eq!(value["goal"]["tokensUsed"],3250);assert_eq!(value["goal"]["timeUsedSeconds"],75);assert_eq!(value["goal"]["createdAt"],1_777_766_400_u64);assert!(value["goal"].get("tokenBudget").is_none());assert!(value["goal"].get("completedAt").is_none());assert!(serde_json::to_value(goal_tool_response(None)).unwrap()["goal"].is_null());}
