use maho_ext_pi_goal::goal::{store::*,types::*};
fn fixture(thread:&str)->(tempfile::TempDir,GoalStoreRef){let temp=tempfile::tempdir().unwrap_or_else(|e|panic!("temp goal store: {e}"));let reference=GoalStoreRef{base_dir:temp.path().join("extensions/pi-goal"),thread_id:thread.into()};(temp,reference)}
#[test]fn reads_invalid_utf8_with_node_replacement(){let(_temp,r)=fixture("utf8");let goal=create_goal_at(&r,"X",10,"id".into()).unwrap();let mut bytes=std::fs::read(goal_file_path(&r)).unwrap();let start=bytes.windows(3).position(|window|window==b"\"X\"").unwrap();bytes[start+1]=0xff;std::fs::write(goal_file_path(&r),bytes).unwrap();let mut expected=goal;expected.objective="\u{fffd}".into();assert_eq!(read_goal(&r).unwrap(),Some(expected));}
#[test]fn store_envelope_preserves_source_field_order(){let(_temp,r)=fixture("order");write_goal(&r,None).expect("write");let raw=std::fs::read_to_string(goal_file_path(&r)).expect("read");let keys=raw.lines().filter_map(|line|line.trim().strip_prefix('"').and_then(|line|line.split_once('"')).map(|(key,_)|key)).collect::<Vec<_>>();assert_eq!(keys,["version","goal"]);}
#[test]fn persists_active_without_budget(){let(_temp,r)=fixture("thread-create");let goal=create_goal_at(&r,"  Ship the extension  ",10,"id".into()).unwrap();assert_eq!(goal.objective,"Ship the extension");assert_eq!(goal.status,GoalStatus::Active);assert!(goal.token_budget.is_none());assert_eq!(read_goal(&r).unwrap(),Some(goal));let value:serde_json::Value=serde_json::from_str(&std::fs::read_to_string(goal_file_path(&r)).unwrap()).unwrap();assert_eq!(value["version"],1);assert!(value["goal"].get("tokenBudget").is_none());}
#[test]fn inert_budget_preserved(){let(_temp,r)=fixture("budget");let mut goal=create_goal_at(&r,"metadata",10,"id".into()).unwrap();goal.token_budget=Some(4096);write_goal(&r,Some(&goal)).unwrap();let done=update_goal_at(&r,&GoalUpdate{status:Some(GoalStatus::Complete),..GoalUpdate::default()},GoalUpdateSource::Model,10,"unused".into()).unwrap();assert_eq!(done.token_budget,Some(4096));let mut value=serde_json::json!({"version":1,"goal":goal});value["goal"]["tokenBudget"]=serde_json::json!(-1);assert_eq!(parse_goal_file(&value.to_string()).unwrap_err().to_string(),"goal store contains an invalid goal");}
#[test]fn spills_exact_oversized_objective(){let(_temp,r)=fixture("thread/oversized objective");let objective="x".repeat(4200);let goal=create_goal_at(&r,&objective,10,"id".into()).unwrap();assert!(goal.objective.chars().count()<=4000);assert_eq!(std::fs::read_to_string(objective_full_text_file_path(&r)).unwrap(),objective);assert_eq!(objective_full_text_file_name(&r),"thread%2Foversized%20objective.objective-full.txt");}
#[test]fn completed_create_archives_one_line(){let(_temp,r)=fixture("complete");create_goal_at(&r,"original",10,"first".into()).unwrap();update_goal_at(&r,&GoalUpdate{status:Some(GoalStatus::Complete),..GoalUpdate::default()},GoalUpdateSource::Model,10,"unused".into()).unwrap();let replacement=create_goal_at(&r,"replacement",12,"second".into()).unwrap();assert_eq!(replacement.id,"second");let history=std::fs::read_to_string(goal_history_file_path(&r)).unwrap();assert_eq!(history.lines().count(),1);let archived:Goal=serde_json::from_str(history.trim()).unwrap();assert_eq!(archived.id,"first");assert_eq!(archived.status,GoalStatus::Complete);}
#[test]fn rejects_create_active(){let(_temp,r)=fixture("active");create_goal_at(&r,"original",10,"first".into()).unwrap();assert_eq!(create_goal_at(&r,"replacement",10,"second".into()).unwrap_err(),"cannot create a new goal because this thread already has a goal");}
#[test]fn rejects_create_paused(){let(_temp,r)=fixture("paused");create_goal_at(&r,"original",10,"first".into()).unwrap();update_goal_at(&r,&GoalUpdate{status:Some(GoalStatus::Paused),..GoalUpdate::default()},GoalUpdateSource::User,10,"unused".into()).unwrap();assert!(create_goal_at(&r,"replacement",10,"second".into()).is_err());assert_eq!(read_goal(&r).unwrap().unwrap().id,"first");}
#[test]fn matching_objective_resumes_same_id(){let(_temp,r)=fixture("same");create_goal_at(&r,"Same",10,"first".into()).unwrap();update_goal_at(&r,&GoalUpdate{status:Some(GoalStatus::Paused),..GoalUpdate::default()},GoalUpdateSource::User,10,"unused".into()).unwrap();let resumed=update_goal_at(&r,&GoalUpdate{objective:Some("Same".into()),..GoalUpdate::default()},GoalUpdateSource::User,10,"unused".into()).unwrap();assert_eq!(resumed.id,"first");assert_eq!(resumed.status,GoalStatus::Active);assert_eq!(resumed.updated_at,12);}
#[test]fn blocked_invariant_boundary(){let(_temp,r)=fixture("invariants");let goal=create_goal_at(&r,"objective",1,"id".into()).unwrap();let mut value=serde_json::json!({"version":1,"goal":goal});assert!(parse_goal_file(&value.to_string()).is_ok());value["goal"]["status"]=serde_json::json!("blocked");assert!(parse_goal_file(&value.to_string()).is_err());value["goal"]["blockedReason"]=serde_json::json!("decision");value["goal"]["blockedAt"]=serde_json::json!(2);assert!(parse_goal_file(&value.to_string()).is_ok());}
#[test]fn replacement_resets_usage_status_preserves(){let(_temp,r)=fixture("replace");create_goal_at(&r,"original",10,"first".into()).unwrap();account_goal_usage_at(&r,&TokenUsageSnapshot{input:23.0,output:2.0,..TokenUsageSnapshot::default()},70.0,GoalAccountingMode::Active,None,10).unwrap();let paused=update_goal_at(&r,&GoalUpdate{status:Some(GoalStatus::Paused),..GoalUpdate::default()},GoalUpdateSource::User,10,"unused".into()).unwrap();assert_eq!((paused.tokens_used,paused.time_used_seconds),(25,70));let next=update_goal_at(&r,&GoalUpdate{objective:Some("replacement".into()),..GoalUpdate::default()},GoalUpdateSource::Model,10,"second".into()).unwrap();assert_eq!(next.id,"second");assert_eq!((next.tokens_used,next.time_used_seconds),(0,0));}
#[test]fn user_resume_clears_blocked(){let(_temp,r)=fixture("resume");create_goal_at(&r,"objective",10,"id".into()).unwrap();for status in [GoalStatus::Paused,GoalStatus::Active]{update_goal_at(&r,&GoalUpdate{status:Some(status),..GoalUpdate::default()},GoalUpdateSource::User,10,"unused".into()).unwrap();}update_goal_at(&r,&GoalUpdate{status:Some(GoalStatus::Blocked),reason:Some("decision".into()),..GoalUpdate::default()},GoalUpdateSource::Model,10,"unused".into()).unwrap();let resumed=update_goal_at(&r,&GoalUpdate{status:Some(GoalStatus::Active),..GoalUpdate::default()},GoalUpdateSource::User,10,"unused".into()).unwrap();assert!(resumed.blocked_reason.is_none());assert!(resumed.blocked_at.is_none());}
#[test]fn repeated_blocked_idempotent(){let(_temp,r)=fixture("blocked");create_goal_at(&r,"objective",10,"id".into()).unwrap();let blocked=update_goal_at(&r,&GoalUpdate{status:Some(GoalStatus::Blocked),reason:Some("decision".into()),..GoalUpdate::default()},GoalUpdateSource::Model,10,"unused".into()).unwrap();let repeated=update_goal_at(&r,&GoalUpdate{status:Some(GoalStatus::Blocked),reason:Some("different".into()),..GoalUpdate::default()},GoalUpdateSource::Model,10,"unused".into()).unwrap();assert_eq!(repeated.blocked_reason,blocked.blocked_reason);assert_eq!(repeated.blocked_at,blocked.blocked_at);assert!(repeated.updated_at>blocked.updated_at);}
#[test]fn counts_only_input_output(){let(_temp,r)=fixture("tokens");create_goal_at(&r,"objective",10,"id".into()).unwrap();let goal=account_goal_usage_at(&r,&TokenUsageSnapshot{input:100.0,output:20.0,cache_read:70.0,total_tokens:999.0,..TokenUsageSnapshot::default()},0.0,GoalAccountingMode::Active,None,10).unwrap().unwrap();assert_eq!(goal.tokens_used,120);}
#[test]fn accounting_never_changes_status(){let(_temp,r)=fixture("volume");create_goal_at(&r,"objective",10,"id".into()).unwrap();let goal=account_goal_usage_at(&r,&TokenUsageSnapshot{input:10_000_000.0,..TokenUsageSnapshot::default()},4.0,GoalAccountingMode::Active,None,10).unwrap().unwrap();assert_eq!(goal.status,GoalStatus::Active);assert_eq!((goal.tokens_used,goal.time_used_seconds),(10_000_000,4));}
#[test]fn paused_not_accounted(){let(_temp,r)=fixture("paused-usage");create_goal_at(&r,"objective",10,"id".into()).unwrap();update_goal_at(&r,&GoalUpdate{status:Some(GoalStatus::Paused),..GoalUpdate::default()},GoalUpdateSource::User,10,"unused".into()).unwrap();let goal=account_goal_usage_at(&r,&TokenUsageSnapshot{input:25.0,..TokenUsageSnapshot::default()},3.0,GoalAccountingMode::Active,None,10).unwrap().unwrap();assert_eq!((goal.tokens_used,goal.time_used_seconds),(0,0));}
fn finalize(status:GoalStatus,mode:GoalAccountingMode){let(_temp,r)=fixture("finalize");create_goal_at(&r,"objective",10,"id".into()).unwrap_or_else(|e|panic!("create: {e}"));update_goal_at(&r,&GoalUpdate{status:Some(status),reason:(status==GoalStatus::Blocked).then(||"decision".into()),..GoalUpdate::default()},GoalUpdateSource::Model,10,"unused".into()).unwrap_or_else(|e|panic!("transition: {e}"));let goal=account_goal_usage_at(&r,&TokenUsageSnapshot{input:25.0,output:5.0,..TokenUsageSnapshot::default()},3.0,mode,None,10).unwrap_or_else(|e|panic!("account: {e}")).unwrap_or_else(||panic!("goal exists"));assert_eq!((goal.tokens_used,goal.time_used_seconds),(30,3));assert_eq!(goal.status,status);}
#[test]fn blocked_finalization(){finalize(GoalStatus::Blocked,GoalAccountingMode::ActiveOrBlocked);}
#[test]fn complete_finalization(){finalize(GoalStatus::Complete,GoalAccountingMode::ActiveOrComplete);}
#[test]fn completes_stamps_timestamp(){let(_temp,r)=fixture("stamp");create_goal_at(&r,"objective",10,"id".into()).unwrap();let goal=update_goal_at(&r,&GoalUpdate{status:Some(GoalStatus::Complete),..GoalUpdate::default()},GoalUpdateSource::Model,10,"unused".into()).unwrap();assert_eq!(goal.completed_at,Some(11));assert!(goal.last_started_at.is_none());}
#[test]fn clear_preserves_version(){let(_temp,r)=fixture("clear");create_goal_at(&r,"objective",10,"id".into()).unwrap();assert!(clear_goal(&r).unwrap());assert!(read_goal(&r).unwrap().is_none());let value:serde_json::Value=serde_json::from_str(&std::fs::read_to_string(goal_file_path(&r)).unwrap()).unwrap();assert_eq!(value["version"],1);}
fn matrix(from:GoalStatus,to:GoalStatus,allowed:bool){let(_temp,r)=fixture("matrix");create_goal_at(&r,"objective",10,"id".into()).unwrap_or_else(|e|panic!("create: {e}"));if from!=GoalStatus::Active{update_goal_at(&r,&GoalUpdate{status:Some(from),reason:(from==GoalStatus::Blocked).then(||"decision".into()),..GoalUpdate::default()},if from==GoalStatus::Paused{GoalUpdateSource::User}else{GoalUpdateSource::Model},10,"unused".into()).unwrap_or_else(|e|panic!("prepare: {e}"));}let result=update_goal_at(&r,&GoalUpdate{status:Some(to),reason:(to==GoalStatus::Blocked).then(||"decision".into()),..GoalUpdate::default()},GoalUpdateSource::Model,10,"unused".into());assert_eq!(result.is_ok(),allowed);if let Ok(goal)=result{assert_eq!(goal.status,to);}}
macro_rules! transition_case{($name:ident,$from:ident,$to:ident,$allowed:expr)=>{#[test]fn $name(){matrix(GoalStatus::$from,GoalStatus::$to,$allowed);}};}
transition_case!(active_active,Active,Active,true);
transition_case!(active_paused,Active,Paused,false);
transition_case!(active_blocked,Active,Blocked,true);
transition_case!(active_complete,Active,Complete,true);
transition_case!(paused_active,Paused,Active,false);
transition_case!(paused_paused,Paused,Paused,true);
transition_case!(paused_blocked,Paused,Blocked,false);
transition_case!(paused_complete,Paused,Complete,false);
transition_case!(blocked_active,Blocked,Active,false);
transition_case!(blocked_paused,Blocked,Paused,false);
transition_case!(blocked_blocked,Blocked,Blocked,true);
transition_case!(blocked_complete,Blocked,Complete,true);
transition_case!(complete_active,Complete,Active,false);
transition_case!(complete_paused,Complete,Paused,false);
transition_case!(complete_blocked,Complete,Blocked,false);
transition_case!(complete_complete,Complete,Complete,true);
