use maho_ext_pi_goal::goal::{transitions::*,types::*};
fn goal(status:GoalStatus)->Goal{Goal{id:"id".into(),thread_id:"thread".into(),objective:"objective".into(),status,token_budget:None,tokens_used:25,time_used_seconds:70,created_at:1,updated_at:1,last_started_at:(status==GoalStatus::Active).then_some(1),blocked_reason:(status==GoalStatus::Blocked).then(||"original".into()),blocked_at:(status==GoalStatus::Blocked).then_some(1),completed_at:(status==GoalStatus::Complete).then_some(1)}}
#[test]fn model_transition_matrix(){let statuses=[GoalStatus::Active,GoalStatus::Paused,GoalStatus::Blocked,GoalStatus::Complete];for from in statuses{for to in statuses{let expected=from==to||matches!((from,to),(GoalStatus::Active,GoalStatus::Blocked|GoalStatus::Complete)|(GoalStatus::Blocked,GoalStatus::Complete));let r=transition_goal_status(&goal(from),to,GoalUpdateSource::Model,(to==GoalStatus::Blocked).then_some("reason"),2);assert_eq!(r.is_ok(),expected,"{from:?} -> {to:?}");}}}
#[test]fn user_transition_matrix(){let statuses=[GoalStatus::Active,GoalStatus::Paused,GoalStatus::Blocked,GoalStatus::Complete];for from in statuses{for to in statuses{let expected=from==to||matches!((from,to),(GoalStatus::Active,GoalStatus::Paused)|(GoalStatus::Paused|GoalStatus::Blocked,GoalStatus::Active));let r=transition_goal_status(&goal(from),to,GoalUpdateSource::User,(to==GoalStatus::Blocked).then_some("reason"),2);assert_eq!(r.is_ok(),expected,"{from:?} -> {to:?}");}}}
#[test]fn blocked_requires_reason(){let r=transition_goal_status(&goal(GoalStatus::Active),GoalStatus::Blocked,GoalUpdateSource::Model,Some("   "),2);assert_eq!(r.unwrap_err(),"reason is required when status is blocked");}
#[test]fn repeated_block_preserves_reason(){let r=transition_goal_status(&goal(GoalStatus::Blocked),GoalStatus::Blocked,GoalUpdateSource::Model,Some("different"),2).unwrap();assert_eq!(r.blocked_reason.as_deref(),Some("original"));assert_eq!(r.blocked_at,Some(1));assert_eq!(r.updated_at,2);}
#[test]fn resume_clears_blocked_fields(){let r=transition_goal_status(&goal(GoalStatus::Blocked),GoalStatus::Active,GoalUpdateSource::User,None,2).unwrap();assert!(r.blocked_reason.is_none());assert!(r.blocked_at.is_none());assert_eq!(r.last_started_at,Some(2));assert_eq!(r.tokens_used,25);}
#[test]fn complete_rejects_reason(){let r=transition_goal_status(&goal(GoalStatus::Active),GoalStatus::Complete,GoalUpdateSource::Model,Some("done"),2);assert_eq!(r.unwrap_err(),"reason must not be provided when status is complete");}
#[test]fn complete_timestamp_idempotent(){let r=transition_goal_status(&goal(GoalStatus::Complete),GoalStatus::Complete,GoalUpdateSource::Model,None,2).unwrap();assert_eq!(r.completed_at,Some(1));assert_eq!(r.last_started_at,None);}
