use std::sync::{Arc,atomic::{AtomicUsize,Ordering}};
use maho_omo_task::completion_bridge::{CompletionObservingStore,CompletionBridgeDeps,create_completion_observing_store};
use senpi_task::{completion::{ParentNotifier,ParentNotifierMessage,ParentState,CompletionNotifierDeps,create_completion_notifier},host::HostError,store::{TaskRecordStore,StateDirConfig},state::{TaskRecord,TaskRecordInput,TaskTransition,TaskStatus,create_task_record}};
struct Parent(Arc<AtomicUsize>); impl ParentNotifier for Parent { fn enqueue(&self,_:&ParentNotifierMessage)->Result<(),HostError> { self.0.fetch_add(1,Ordering::SeqCst); Ok(()) } }
fn fixture(background:bool)->(tempfile::TempDir,CompletionObservingStore,TaskRecord,Arc<AtomicUsize>,Arc<AtomicUsize>) {
    let root=tempfile::tempdir().expect("root"); let backing=TaskRecordStore::new(&StateDirConfig { project_dir:root.path().into(),task_state_dir:None }); let delivered=Arc::new(AtomicUsize::new(0)); let terminal=Arc::new(AtomicUsize::new(0));
    let mut record=create_task_record(TaskRecordInput::default(),Some(1)).expect("record"); record.status=TaskStatus::Running; backing.save(&record).expect("save"); let notifier=create_completion_notifier(CompletionNotifierDeps::new(Arc::new(Parent(delivered.clone())),Arc::new(backing.clone()))); let observed=terminal.clone();
    let store=create_completion_observing_store(backing,CompletionBridgeDeps { notifier:Arc::new(notifier),parent_state:Arc::new(|| ParentState::Idle),was_background:Arc::new(move |_| background),on_terminal:Some(Arc::new(move |_| { observed.fetch_add(1,Ordering::SeqCst); })) });
    (root,store,record,delivered,terminal)
}
fn complete()->TaskTransition { TaskTransition::Complete { timestamp:"1970-01-01T00:00:00.002Z".into(),final_response:"finished".into(),run_stats:None } }
#[test] fn applied_completion_notifies_and_calls_terminal_hook_once() { let (_root,store,record,delivered,terminal)=fixture(true); store.transition(&record.task_id,&complete()).expect("complete"); assert_eq!(delivered.load(Ordering::SeqCst),1); assert_eq!(terminal.load(Ordering::SeqCst),1); store.transition(&record.task_id,&complete()).expect("repeat"); assert_eq!(delivered.load(Ordering::SeqCst),1); assert_eq!(terminal.load(Ordering::SeqCst),1); }
#[test] fn replace_never_recursively_notifies() { let (_root,store,mut record,delivered,terminal)=fixture(true); record.status=TaskStatus::Completed; store.replace(&record).expect("replace"); assert_eq!(delivered.load(Ordering::SeqCst),0); assert_eq!(terminal.load(Ordering::SeqCst),0); }
#[test] fn residency_transition_does_not_notify_terminal_again() { let (_root,store,record,delivered,terminal)=fixture(true); store.transition(&record.task_id,&complete()).expect("complete"); store.transition(&record.task_id,&TaskTransition::Evict { timestamp:"1970-01-01T00:00:00.003Z".into() }).expect("evict"); assert_eq!(delivered.load(Ordering::SeqCst),1); assert_eq!(terminal.load(Ordering::SeqCst),1); }
#[test] fn synchronous_completion_still_runs_liveness_hook_without_parent_push() { let (_root,store,record,delivered,terminal)=fixture(false); store.transition(&record.task_id,&complete()).expect("complete"); assert_eq!(delivered.load(Ordering::SeqCst),0); assert_eq!(terminal.load(Ordering::SeqCst),1); }
