use std::{collections::BTreeMap,sync::{Arc,Mutex}};
use maho_omo_task::{dag_rpc_bridge::create_dag_rpc_bridge,dag_rpc_bridge_contract::{DagBridgeRun,DagRpcBridgeDeps},dag_rpc_handlers::query_dag_rpc,status_ui::StatusUiTimers};
use senpi_task::dag::{manager::{create_dag_manager,DagManagerOptions,DagStartParams,DagManager},journal::{create_dag_journal,DagJournalOptions},store::{create_dag_file_store,DagStoreConfig,DagStoreOptions},types::DagRunEventPayload};
use serde_json::{Value,json};
#[derive(Default)] struct Timers(Mutex<BTreeMap<u64,Box<dyn FnOnce()+Send>>>);
impl StatusUiTimers for Timers { fn set(&self,callback:Box<dyn FnOnce()+Send>,_:u64)->u64 { let mut callbacks=self.0.lock().expect("timers"); let id=callbacks.keys().next_back().copied().unwrap_or(0)+1; callbacks.insert(id,callback); id } fn clear(&self,id:u64) { self.0.lock().expect("timers").remove(&id); } }
fn page(manager:&DagManager,since:u64,through:u64)->Value { let result=query_dag_rpc(manager,Some("parent".into()),"omo.dag.history",&json!({"runId":"run","sinceSeq":since,"throughSeq":through,"limit":37})); assert_eq!(result["ok"],true); result["value"].clone() }
fn apply(events:&[Value],applied:&mut Vec<u64>) { for event in events { let seq=event["seq"].as_u64().expect("sequence"); if seq<=applied.last().copied().unwrap_or(0) { continue; } assert_eq!(seq,applied.last().copied().unwrap_or(0)+1); applied.push(seq); } }
#[test] fn viewer_catchup_recovers_dropped_live_event_without_duplicates() {
    let root=tempfile::tempdir().expect("root"); let store=Arc::new(create_dag_file_store(&DagStoreConfig::new(root.path()),DagStoreOptions { fsync:Some(false),..Default::default() }).expect("store")); let manager=create_dag_manager(DagManagerOptions { store:store.clone(),new_run_id:Some(Arc::new(|| "run".into())),now:Some(Arc::new(|| 1000)),materialize_skills:None,settings:None });
    let definition=senpi_task::dag::graph::DagDefinition { key:"viewer".into(),name:"viewer".into(),nodes:vec![senpi_task::dag::graph::DagNodeInput { id:"a".into(),prompt:"work".into(),target:senpi_task::dag::types::DagNodeTarget::Category("quick".into()),label:None,depends_on:None,task_summary:None,description:None,load_skills:None }] }; manager.start(DagStartParams { definition,parent_session_id:"parent".into(),root_session_id:"root".into() }).expect("run");
    let journal=create_dag_journal(DagJournalOptions { store,run_id:"run".into(),initial_checkpoint:manager.record(&"run".into(),"parent").expect("record"),apply_event:Arc::new(|record,_| record.clone()),subscriber_ring:Some(256),now:Some(Arc::new(|| 1000)) }).expect("journal");
    for _ in 1..150 { journal.append(DagRunEventPayload::RunStarted { generation:1 }).expect("append"); }
    let subscribed=journal.clone(); let live=Arc::new(Mutex::new(Vec::<Value>::new())); let captured=live.clone(); let timers=Arc::new(Timers::default());
    let bridge=create_dag_rpc_bridge(DagRpcBridgeDeps { live_runs:Arc::new(move || { let journal=subscribed.clone(); vec![DagBridgeRun { run_id:"run".into(),status:"running".into(),subscribe:Arc::new(move |listener| journal.subscribe(Arc::new(move |event| listener(&serde_json::to_value(event).expect("event"))))) }] }),run_snapshots:None,parent_session_id:Arc::new(|| Some("parent".into())),emit:Arc::new(move |name,event| { if name!="omo.dag.event" || event["seq"]==176 { return; } let mut live=captured.lock().expect("live"); live.push(event.clone()); if event["seq"]==190 { live.push(event); } }),timers:timers.clone(),now:Arc::new(|| 1000),heartbeat_ms:None,activity_coalesce_ms:None,snapshot_debounce_ms:None });
    bridge.attach(); let handshake=query_dag_rpc(&manager,Some("parent".into()),"omo.dag.subscribe",&json!({"runId":"run","limit":37})); assert_eq!(handshake["ok"],true); assert_eq!(handshake["value"]["highWaterSeq"],150); let mut applied=Vec::new(); let mut current=handshake["value"]["page"].clone();
    for _ in 150..200 { journal.append(DagRunEventPayload::RunStarted { generation:1 }).expect("live append"); }
    loop { apply(current["events"].as_array().expect("events"),&mut applied); if current["hasMore"]!=true { break; } current=page(&manager,current["nextSinceSeq"].as_u64().expect("cursor"),150); }
    journal.when_idle(); let mut events=live.lock().expect("live").clone(); events.sort_by_key(|event| event["seq"].as_u64()); let mut recoveries=Vec::new();
    for event in events { let seq=event["seq"].as_u64().expect("sequence"); let last=applied.last().copied().unwrap_or(0); if seq>last+1 { recoveries.push((last,seq-1)); let recovered=page(&manager,last,seq-1); apply(recovered["events"].as_array().expect("recovered"),&mut applied); } apply(&[event],&mut applied); }
    assert_eq!(recoveries,[(175,176)]); assert_eq!(applied,(1..=200).collect::<Vec<_>>()); assert_eq!(manager.snapshot(&"run".into(),"parent").expect("snapshot").last_seq,200); bridge.forward(&json!({"runId":"run","seq":200})); assert_eq!(live.lock().expect("live").len(),50); bridge.dispose(); assert!(timers.0.lock().expect("timers").is_empty());
}
