use std::sync::{Arc,Mutex};
use maho_omo_task::{dag_runtime::runtime_skill_materializer,task_skill_loader::{create_task_skill_loader,TaskSkillLoaderOptions}};
use senpi_task::dag::{manager::{create_dag_manager,DagManagerOptions,DagStartParams},store::{create_dag_file_store,DagStoreConfig,DagStoreOptions}};
#[test] fn shared_skill_loader_materializes_once_at_current_runtime_cwd() {
    let root=tempfile::tempdir().expect("root"); let store=Arc::new(create_dag_file_store(&DagStoreConfig::new(root.path()),DagStoreOptions::default()).expect("store")); let cwd=Arc::new(Mutex::new(root.path().to_string_lossy().into_owned())); let current=cwd.clone(); let fixtures=std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures"); let loader=create_task_skill_loader(TaskSkillLoaderOptions { agent_dir:fixtures.join("agent"),home_dir:root.path().join("home"),plugin_skills_dirs:vec![fixtures.join("skills")] });
    let manager=create_dag_manager(DagManagerOptions { store:store.clone(),new_run_id:Some(Arc::new(|| "skills".into())),now:Some(Arc::new(|| 1000)),materialize_skills:Some(runtime_skill_materializer(store.clone(),Arc::new(move || current.lock().expect("cwd").clone()),loader)),settings:None });
    let definition=senpi_task::dag::graph::DagDefinition { key:"skills".into(),name:"skills".into(),nodes:vec![senpi_task::dag::graph::DagNodeInput { id:"a".into(),prompt:"work".into(),target:senpi_task::dag::types::DagNodeTarget::Category("quick".into()),label:None,depends_on:None,task_summary:None,description:None,load_skills:Some(vec!["sample".into(),"missing".into()]) }] }; let params=DagStartParams { definition:definition.clone(),parent_session_id:"parent".into(),root_session_id:"root".into() }; manager.start(params).expect("start"); let manifest=senpi_task::dag::skills::read_dag_skill_manifest(&store,"skills").expect("manifest"); assert_eq!(manifest.cwd,*cwd.lock().expect("cwd")); assert_eq!(manifest.nodes[0].prompt,"work"); assert_eq!(manifest.nodes[0].resolved[0].name,"sample"); assert_eq!(manifest.nodes[0].missing,["missing"]); assert_ne!(manifest.nodes[0].effective_prompt,"work");
    *cwd.lock().expect("cwd")=root.path().join("changed").to_string_lossy().into_owned(); manager.start(DagStartParams { definition,parent_session_id:"parent".into(),root_session_id:"root".into() }).expect("reuse"); assert_eq!(senpi_task::dag::skills::read_dag_skill_manifest(&store,"skills").expect("retained"),manifest);
}
