use maho_omo_task::member_liveness::{liveness_details,liveness_delivery_keys,liveness_delivery_keys_from_session_text};
use senpi_task::state::{TaskRecordInput,TaskStatus,ResidencyState,create_task_record};
use serde_json::json;
fn record() -> senpi_task::state::TaskRecord { let mut record = create_task_record(TaskRecordInput { name: Some("team:11111111-1111-4111-8111-111111111111:alpha".into()), ..Default::default() },Some(1)).expect("member task record"); record.status = TaskStatus::Error; record }
#[test] fn abnormal_member_has_structured_liveness_details() { let mut record = record(); record.error_message = Some("crashed".into()); record.killed = Some(true); let details = liveness_details(&record).unwrap(); assert_eq!(details["memberName"],"alpha"); assert_eq!(details["lastKnownState"],"error"); assert_eq!(details["reason"],"crashed"); assert_eq!(details["killed"],true); }
#[test] fn suspended_members_never_report_death() { for residency in [ResidencyState::PersistedOnly,ResidencyState::RpcDetached] { let mut record = record(); record.residency_state = residency; assert!(liveness_details(&record).is_none()); } }
#[test] fn healthy_member_has_no_liveness_notification() { let mut record = record(); record.status = TaskStatus::Completed; assert!(liveness_details(&record).is_none()); }
#[test] fn ordinary_task_has_no_member_liveness() { let mut record = record(); record.name = Some("worker".into()); assert!(liveness_details(&record).is_none()); }
#[test] fn killed_cancelled_member_reports_death() { let mut record = record(); record.status = TaskStatus::Cancelled; record.killed = Some(true); assert!(liveness_details(&record).is_some()); }
#[test] fn direct_message_extracts_exact_delivery_key() { assert_eq!(liveness_delivery_keys(&json!({"message":{"customType":"senpi-task.team-member-liveness","details":{"deliveryKey":"team-member-liveness:st_1:0"}}})),["team-member-liveness:st_1:0"]); }
#[test] fn wake_envelope_extracts_and_deduplicates_keys() { let detail = json!({"customType":"senpi-task.team-member-liveness","details":{"deliveryKey":"team-member-liveness:st_1:0"}}); assert_eq!(liveness_delivery_keys(&json!({"message":{"customType":"omo-senpi:wake","details":[detail,detail]}})),["team-member-liveness:st_1:0"]); }
#[test] fn session_marker_parser_ignores_invalid_json_and_other_entries() { let message = json!({"type":"custom_message","customType":"senpi-task.team-member-liveness","details":{"deliveryKey":"team-member-liveness:st_1:0"}}); let text = format!("bad json\n{}\n{{\"type\":\"message\"}}\n",message); assert_eq!(liveness_delivery_keys_from_session_text(&text),["team-member-liveness:st_1:0"]); }
#[test] fn foreign_key_prefix_is_not_acknowledged() { assert!(liveness_delivery_keys(&json!({"message":{"customType":"senpi-task.team-member-liveness","details":{"deliveryKey":"other:st_1"}}})).is_empty()); }
