use maho_omo_task::task_rpc_codec::{task_snapshot,bounded_task_output};
use senpi_task::{state::{TaskRecordInput,create_task_record}, tools::output::types::TaskOutputDetails};
#[test] fn task_snapshot_bounds_text_and_sets_truncation_flags() { let mut record = create_task_record(TaskRecordInput::default(),Some(1)).unwrap(); record.description = Some("x".repeat(32001)); record.final_response = Some("x".repeat(32001)); record.error_message = Some("x".repeat(32001)); let snapshot = task_snapshot(&record,None,None).unwrap(); for key in ["description","final_response","error_message"] { assert_eq!(snapshot[key].as_str().unwrap().len(),32000); assert_eq!(snapshot[format!("{key}_truncated")],true); } }
#[test] fn missing_task_output_does_not_disclose_known_tasks() { let value = bounded_task_output(&TaskOutputDetails::NotFound { reason:"private".into(),known_tasks:vec!["private".into()] }).unwrap(); assert_eq!(value,serde_json::json!({"kind":"not_found","reason":"Task not found."})); }
#[test] fn invalid_output_arguments_remain_machine_readable() { let value = bounded_task_output(&TaskOutputDetails::InvalidArguments { reason:"invalid".into() }).unwrap(); assert_eq!(value["reason"],"invalid"); }
#[test] fn task_snapshot_child_identity_is_bounded() { let mut record = create_task_record(TaskRecordInput::default(),Some(1)).unwrap(); record.child_session_id = Some("a".repeat(257)); let snapshot = task_snapshot(&record,None,None).unwrap(); assert_eq!(snapshot["child_session_id"].as_str().unwrap().len(),256); }
#[test] fn transcript_output_bounds_utf16_and_preserves_existing_truncation() {
    use senpi_task::tools::output::{snapshot::build_task_snapshot,types::{TranscriptMode,TranscriptSource}};
    let record=create_task_record(TaskRecordInput::default(),Some(1)).expect("record"); let snapshot=build_task_snapshot(&record,"/tmp",1000);
    let details=TaskOutputDetails::Transcript { mode:TranscriptMode::Full,source:TranscriptSource::EventLog,transcript:"🦀".repeat(16001),truncated:false,snapshot:snapshot.clone() }; let value=bounded_task_output(&details).expect("output"); assert_eq!(value["transcript"].as_str().expect("transcript").encode_utf16().count(),32000); assert_eq!(value["truncated"],true);
    let details=TaskOutputDetails::Transcript { mode:TranscriptMode::Tail,source:TranscriptSource::EventLog,transcript:"short".into(),truncated:true,snapshot }; assert_eq!(bounded_task_output(&details).expect("output")["truncated"],true);
}
#[test] fn output_snapshot_bounds_lineage_and_loss_breadcrumbs_without_discarding_pid() {
    use senpi_task::{state::{TaskStatus,ResidencyState},tools::output::{snapshot::build_task_snapshot,types::SuspendedDetails}};
    let mut record=create_task_record(TaskRecordInput::default(),Some(1)).expect("record"); record.parent_session_id="p".repeat(257); record.root_session_id="r".repeat(257); record.status=TaskStatus::Lost; record.pid=Some(42); record.residency_state=ResidencyState::PersistedOnly; let mut snapshot=build_task_snapshot(&record,"/tmp",1000); let lost=snapshot.lost.as_mut().expect("lost"); lost.explanation="e".repeat(32001); lost.session_dir="s".repeat(32001); snapshot.suspended=Some(SuspendedDetails { explanation:"x".repeat(32001) });
    let value=bounded_task_output(&TaskOutputDetails::Status { snapshot }).expect("output"); for field in ["parent_session_id","root_session_id"] { assert_eq!(value["snapshot"][field].as_str().expect("lineage").len(),256); } for field in ["explanation","session_dir"] { assert_eq!(value["snapshot"]["lost"][field].as_str().expect("breadcrumb").len(),32000); } assert_eq!(value["snapshot"]["lost"]["pid"],42); assert_eq!(value["snapshot"]["suspended"]["explanation"].as_str().expect("suspended").len(),32000);
}
#[test] fn absent_optional_snapshot_fields_are_not_invented() { let record=create_task_record(TaskRecordInput::default(),Some(1)).expect("record"); let value=task_snapshot(&record,None,None).expect("snapshot"); for field in ["child_session_id","final_response","error_message","run_stats","live_progress","description_truncated"] { assert!(value.get(field).is_none(),"{field}"); } }
