#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum PromptPresetName {
 #[default]
 Auto,
 ClaudeFable5,
 ClaudeFable51,
 ClaudeOpus55,
 ClaudeOpus5,
 ClaudeOpus48,
 ClaudeOpus47,
 ClaudeOpus46,
 ClaudeOpus45,
 DeepseekV4Flash,
 DeepseekV4Flash0731,
 DeepseekV41Flash,
 DeepseekV4Pro,
 Glm52,
 Glm53,
 Grok45,
 Grok46,
 Grok47,
 KimiK3,
 KimiK28,
 KimiK27,
 KimiK26,
 Gpt5,
 Gpt52,
 Gpt53Codex,
 Gpt54,
 Gpt55,
 Gpt56,
 Gpt6Astra,
}
impl PromptPresetName {
 pub const fn as_str(self) -> &'static str { match self {
 Self::Auto => "auto",
 Self::ClaudeFable5 => "claude-fable-5",
 Self::ClaudeFable51 => "claude-fable-5-1",
 Self::ClaudeOpus55 => "claude-opus-5-5",
 Self::ClaudeOpus5 => "claude-opus-5",
 Self::ClaudeOpus48 => "claude-opus-4-8",
 Self::ClaudeOpus47 => "claude-opus-4-7",
 Self::ClaudeOpus46 => "claude-opus-4-6",
 Self::ClaudeOpus45 => "claude-opus-4-5",
 Self::DeepseekV4Flash => "deepseek-v4-flash",
 Self::DeepseekV4Flash0731 => "deepseek-v4-flash-0731",
 Self::DeepseekV41Flash => "deepseek-v4-1-flash",
 Self::DeepseekV4Pro => "deepseek-v4-pro",
 Self::Glm52 => "glm-5.2",
 Self::Glm53 => "glm-5.3",
 Self::Grok45 => "grok-4.5",
 Self::Grok46 => "grok-4.6",
 Self::Grok47 => "grok-4.7",
 Self::KimiK3 => "kimi-k3",
 Self::KimiK28 => "kimi-k2-8",
 Self::KimiK27 => "kimi-k2-7",
 Self::KimiK26 => "kimi-k2-6",
 Self::Gpt5 => "gpt-5",
 Self::Gpt52 => "gpt-5.2",
 Self::Gpt53Codex => "gpt-5.3-codex",
 Self::Gpt54 => "gpt-5.4",
 Self::Gpt55 => "gpt-5.5",
 Self::Gpt56 => "gpt-5.6",
 Self::Gpt6Astra => "gpt-6-astra",
 } }
}
pub fn parse_prompt_preset(value: Option<&str>) -> Option<PromptPresetName> {
 match value? {
"auto" => Some(PromptPresetName::Auto),
"claude-fable-5" => Some(PromptPresetName::ClaudeFable5),
"claude-fable-5-1" => Some(PromptPresetName::ClaudeFable51),
"claude-opus-5-5" => Some(PromptPresetName::ClaudeOpus55),
"claude-opus-5" => Some(PromptPresetName::ClaudeOpus5),
"claude-opus-4-8" => Some(PromptPresetName::ClaudeOpus48),
"claude-opus-4-7" => Some(PromptPresetName::ClaudeOpus47),
"claude-opus-4-6" => Some(PromptPresetName::ClaudeOpus46),
"claude-opus-4-5" => Some(PromptPresetName::ClaudeOpus45),
"deepseek-v4-flash" => Some(PromptPresetName::DeepseekV4Flash),
"deepseek-v4-flash-0731" => Some(PromptPresetName::DeepseekV4Flash0731),
"deepseek-v4-1-flash" => Some(PromptPresetName::DeepseekV41Flash),
"deepseek-v4-pro" => Some(PromptPresetName::DeepseekV4Pro),
"glm-5.2" => Some(PromptPresetName::Glm52),
"glm-5.3" => Some(PromptPresetName::Glm53),
"grok-4.5" => Some(PromptPresetName::Grok45),
"grok-4.6" => Some(PromptPresetName::Grok46),
"grok-4.7" => Some(PromptPresetName::Grok47),
"kimi-k3" => Some(PromptPresetName::KimiK3),
"kimi-k2-8" => Some(PromptPresetName::KimiK28),
"kimi-k2-7" => Some(PromptPresetName::KimiK27),
"kimi-k2-6" => Some(PromptPresetName::KimiK26),
"gpt-5" => Some(PromptPresetName::Gpt5),
"gpt-5.2" => Some(PromptPresetName::Gpt52),
"gpt-5.3-codex" => Some(PromptPresetName::Gpt53Codex),
"gpt-5.4" => Some(PromptPresetName::Gpt54),
"gpt-5.5" => Some(PromptPresetName::Gpt55),
"gpt-5.6" => Some(PromptPresetName::Gpt56),
"gpt-6-astra" => Some(PromptPresetName::Gpt6Astra),
 _ => None,
 }
}
pub fn load_prompt_preset_settings(project: Option<&str>, global: Option<&str>) -> PromptPresetName { parse_prompt_preset(project).or_else(|| parse_prompt_preset(global)).unwrap_or_default() }
