use serde::{Deserialize,Serialize};
use super::{account::*,base::*,catalogs::*,collaboration_mode::*,config::*,fuzzy_search::*,models::*,thread::*,thread_parity::*,turn::*};
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]
#[serde(tag="method")]
pub enum ClientRequest {
    #[serde(rename="initialize")]Initialize {id:RequestId,params:InitializeParams},
    #[serde(rename="account/read")]AccountRead {id:RequestId,params:AccountReadParams},
    #[serde(rename="account/providerAccounts/read")]ProviderAccountsRead {id:RequestId,params:ProviderAccountsReadParams},
    #[serde(rename="account/providerAccounts/pin")]ProviderAccountsPin {id:RequestId,params:ProviderAccountsPinParams},
    #[serde(rename="account/providerAccounts/remove")]ProviderAccountsRemove {id:RequestId,params:ProviderAccountsRemoveParams},
    #[serde(rename="account/rateLimits/read")]AccountRateLimitsRead {id:RequestId,#[serde(default,skip_serializing_if="Option::is_none")]params:Option<AccountRateLimitsReadParams>},
    #[serde(rename="account/usage/read")]AccountUsageRead {id:RequestId,#[serde(default,skip_serializing_if="Option::is_none")]params:Option<AccountUsageReadParams>},
    #[serde(rename="collaborationMode/list")]CollaborationModeList {id:RequestId,params:CollaborationModeListParams},
    #[serde(rename="config/read")]ConfigRead {id:RequestId,params:ConfigReadParams},
    #[serde(rename="configRequirements/read")]ConfigRequirementsRead {id:RequestId,#[serde(default,skip_serializing_if="Option::is_none")]params:Option<ConfigRequirementsReadParams>},
    #[serde(rename="experimentalFeature/list")]ExperimentalFeatureList {id:RequestId,params:ExperimentalFeatureListParams},
    #[serde(rename="fuzzyFileSearch")]FuzzyFileSearch {id:RequestId,params:FuzzyFileSearchParams},
    #[serde(rename="fuzzyFileSearch/sessionStart")]FuzzyFileSearchSessionStart {id:RequestId,params:FuzzyFileSearchSessionStartParams},
    #[serde(rename="fuzzyFileSearch/sessionStop")]FuzzyFileSearchSessionStop {id:RequestId,params:FuzzyFileSearchSessionStopParams},
    #[serde(rename="fuzzyFileSearch/sessionUpdate")]FuzzyFileSearchSessionUpdate {id:RequestId,params:FuzzyFileSearchSessionUpdateParams},
    #[serde(rename="mcpServerStatus/list")]McpServerStatusList {id:RequestId,params:McpServerStatusListParams},
    #[serde(rename="model/list")]ModelList {id:RequestId,params:ModelListParams},
    #[serde(rename="permissionProfile/list")]PermissionProfileList {id:RequestId,params:PermissionProfileListParams},
    #[serde(rename="remoteControl/client/list")]RemoteControlClientList {id:RequestId,params:RemoteControlClientListParams},
    #[serde(rename="remoteControl/status/read")]RemoteControlStatusRead {id:RequestId,#[serde(default,skip_serializing_if="Option::is_none")]params:Option<RemoteControlStatusReadParams>},
    #[serde(rename="skills/list")]SkillsList {id:RequestId,params:SkillsListParams},
    #[serde(rename="thread/compact/start")]ThreadCompactStart {id:RequestId,params:ThreadCompactStartParams},
    #[serde(rename="thread/goal/clear")]ThreadGoalClear {id:RequestId,params:ThreadGoalClearParams},
    #[serde(rename="thread/goal/get")]ThreadGoalGet {id:RequestId,params:ThreadGoalGetParams},
    #[serde(rename="thread/goal/set")]ThreadGoalSet {id:RequestId,params:ThreadGoalSetParams},
    #[serde(rename="thread/items/list")]ThreadItemsList {id:RequestId,params:ThreadItemsListParams},
    #[serde(rename="thread/metadata/update")]ThreadMetadataUpdate {id:RequestId,params:ThreadMetadataUpdateParams},
    #[serde(rename="thread/search")]ThreadSearch {id:RequestId,params:ThreadSearchParams},
    #[serde(rename="thread/searchOccurrences")]ThreadSearchOccurrences {id:RequestId,params:ThreadSearchOccurrencesParams},
    #[serde(rename="thread/settings/update")]ThreadSettingsUpdate {id:RequestId,params:ThreadSettingsUpdateParams},
    #[serde(rename="thread/turns/list")]ThreadTurnsList {id:RequestId,params:ThreadTurnsListParams},
    #[serde(rename="thread/unarchive")]ThreadUnarchive {id:RequestId,params:ThreadUnarchiveParams},
    #[serde(rename="thread/start")]ThreadStart {id:RequestId,params:ThreadStartParams},
    #[serde(rename="thread/resume")]ThreadResume {id:RequestId,params:ThreadResumeParams},
    #[serde(rename="thread/read")]ThreadRead {id:RequestId,params:ThreadReadParams},
    #[serde(rename="thread/list")]ThreadList {id:RequestId,params:ThreadListParams},
    #[serde(rename="thread/loaded/list")]ThreadLoadedList {id:RequestId,params:ThreadLoadedListParams},
    #[serde(rename="thread/fork")]ThreadFork {id:RequestId,params:ThreadForkParams},
    #[serde(rename="thread/name/set")]ThreadNameSet {id:RequestId,params:ThreadSetNameParams},
    #[serde(rename="thread/archive")]ThreadArchive {id:RequestId,params:ThreadArchiveParams},
    #[serde(rename="thread/delete")]ThreadDelete {id:RequestId,params:ThreadDeleteParams},
    #[serde(rename="thread/unsubscribe")]ThreadUnsubscribe {id:RequestId,params:ThreadUnsubscribeParams},
    #[serde(rename="turn/start")]TurnStart {id:RequestId,params:TurnStartParams},
    #[serde(rename="turn/steer")]TurnSteer {id:RequestId,params:TurnSteerParams},
    #[serde(rename="turn/interrupt")]TurnInterrupt {id:RequestId,params:TurnInterruptParams},
}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]
pub struct ServerRequest {pub method:String,pub id:RequestId,#[serde(default,skip_serializing_if="Option::is_none")]pub params:Option<JsonValue>}
