use std::path::Path;
use memory_core::{facts::{FactsFailureReason,payload_cap::FactsPayload,extraction::{FactsExtractionRecord,parse_facts_extraction_jsonl},recovery::find_facts_batch_receipt},git::{GitMemoryRepo,errors::GitError}};
use crate::{facts_runner_types::{FactsRunLedger,FactsLaunchResult,FactsTerminalOutcome},facts_terminal_writes::{FactsTerminalWrites,FactsTerminalError,FactsFailureWrite},worker::run_artifacts::{ArtifactError,RunOutcome,read_run_json},facts_batch_apply::Applied};
#[derive(Debug)]pub enum FactsFinalizeError{Git(GitError),Artifact(ArtifactError),Terminal(FactsTerminalError)}
pub fn finalize_claimed_facts_run(run_dir:&Path,repo:&GitMemoryRepo,ledger:&FactsRunLedger,terminal:&mut FactsTerminalWrites<'_>,apply:&mut impl FnMut(&[FactsExtractionRecord])->Result<Option<Applied>,String>)->Result<FactsLaunchResult,FactsFinalizeError>{
    let receipt=find_facts_batch_receipt(repo,&ledger.batch_id).map_err(FactsFinalizeError::Git)?;
    let payload:FactsPayload=read_run_json(&run_dir.join("facts-payload.json")).map_err(FactsFinalizeError::Artifact)?;let targets=crate::facts_failure_recording::ledger_targets(&ledger.queued);
    if let Some(receipt)=receipt{terminal.succeed(run_dir,&ledger.run_id,FactsTerminalOutcome::Committed,&payload.entries,&targets,Some(&receipt.sha)).map_err(FactsFinalizeError::Terminal)?;return Ok(FactsLaunchResult::Committed{run_id:ledger.run_id.clone(),sha:receipt.sha});}
    let fail=|terminal:&mut FactsTerminalWrites<'_>,reason,detail:&str,outcome|terminal.fail(&FactsFailureWrite{run_dir,run_id:&ledger.run_id,batch_id:&ledger.batch_id,targets:&targets,reason,detail,outcome}).map_err(FactsFinalizeError::Terminal);
    let outcome:RunOutcome=read_run_json(&run_dir.join("outcome.json")).map_err(FactsFinalizeError::Artifact)?;
    if outcome.timed_out||outcome.child_exit.code!=Some(0){fail(terminal,if outcome.timed_out{FactsFailureReason::DeadlineExceeded}else{FactsFailureReason::ChildExit},"facts child did not exit successfully",None)?;return Ok(FactsLaunchResult::Failed{run_id:ledger.run_id.clone()});}
    let records=match std::fs::read(run_dir.join("extraction.jsonl")).map_err(|error|error.to_string()).and_then(|raw|parse_facts_extraction_jsonl(&String::from_utf8_lossy(&raw)).map_err(|error|error.to_string())){Ok(records)=>records,Err(error)=>{fail(terminal,FactsFailureReason::InvalidExtraction,&error,None)?;return Ok(FactsLaunchResult::Failed{run_id:ledger.run_id.clone()});}};
    if records.is_empty(){terminal.succeed(run_dir,&ledger.run_id,FactsTerminalOutcome::NoFacts,&payload.entries,&targets,None).map_err(FactsFinalizeError::Terminal)?;return Ok(FactsLaunchResult::NoFacts{run_id:ledger.run_id.clone()});}
    let applied=match apply(&records){Ok(applied)=>applied,Err(error)=>{fail(terminal,FactsFailureReason::InvalidExtraction,&error,None)?;return Ok(FactsLaunchResult::Failed{run_id:ledger.run_id.clone()});}};
    match applied{
        None=>{fail(terminal,FactsFailureReason::MemoryWriteLockExhausted,"memory-write lock exhausted",None)?;Ok(FactsLaunchResult::Failed{run_id:ledger.run_id.clone()})},
        Some(Applied::ParentDirty{detail})=>{fail(terminal,FactsFailureReason::ParentDirty,detail.as_deref().unwrap_or("memory repository contains foreign state"),Some(FactsTerminalOutcome::ParentDirty))?;Ok(FactsLaunchResult::ParentDirty{run_id:ledger.run_id.clone()})},
        Some(Applied::Committed{sha})=>{terminal.succeed(run_dir,&ledger.run_id,FactsTerminalOutcome::Committed,&payload.entries,&targets,Some(&sha)).map_err(FactsFinalizeError::Terminal)?;Ok(FactsLaunchResult::Committed{run_id:ledger.run_id.clone(),sha})},
    }
}
#[cfg(test)]mod tests{
    use super::*;
    use memory_core::facts::{FactsQueueEntry,failures_store::{FactsFailureStore,FactsFailureStoreOptions}};
    #[test]fn extraction_replaces_non_utf8_bytes_before_parsing(){
        let root=tempfile::tempdir().unwrap();let (repo,ledger,failures)=setup(root.path(),false,0);
        let mut raw=b"{\"scope\":\"project\",\"text\":\"".to_vec();raw.push(0xff);raw.extend_from_slice(b"\",\"date\":\"2026-08-12\"}");std::fs::write(root.path().join("extraction.jsonl"),raw).unwrap();
        let mut io=Io{consumed:0};let mut applied=false;
        let result=finalize_claimed_facts_run(root.path(),&repo,&ledger,&mut FactsTerminalWrites{failures:&failures,io:&mut io},&mut |records|{assert_eq!(records.len(),1);applied=true;Ok(Some(Applied::Committed{sha:"fixture-sha".into()}))}).unwrap();
        assert!(applied);assert!(matches!(result,FactsLaunchResult::Committed{..}));assert!(root.path().join("final.json").exists());
    }
    struct Io{consumed:usize}
    impl crate::facts_terminal_writes::FactsTerminalIo for Io{fn now(&self)->String{"2026-08-12T00:00:00.000Z".into()}fn mark_consumed(&mut self,entries:&[FactsQueueEntry])->std::io::Result<()>{self.consumed+=entries.len();Ok(())}fn warn(&mut self,_:&str,_:&str){}}
    fn setup(root:&Path,timed_out:bool,code:i32)->(GitMemoryRepo,FactsRunLedger,FactsFailureStore){let paths=memory_core::identity::layout::build_identity_paths(root,"agent");let engine=crate::engine_session::prepare_memory_engine_session("agent",&paths,Default::default()).unwrap();let failures=FactsFailureStore::new(FactsFailureStoreOptions{identity_paths:paths,now:Some(std::sync::Arc::new(||0)),lock_wait_ms:None});let ledger:FactsRunLedger=serde_json::from_value(serde_json::json!({"version":1,"runId":"run","kind":"facts","startedAt":"now","hardDeadlineAt":1,"terminationGraceMs":1,"deadlineAt":2,"batchId":"c04edbea-90ea-4c67-9c22-1a9beb207535","queued":[{"conversationId":"session","end_message_id":"m1","end_snapshot_line":1}]})).unwrap();crate::worker::run_artifacts::write_run_json_atomic(&root.join("facts-payload.json"),&serde_json::json!({"version":1,"identity":"agent","today":"2026-08-12","knownPeople":[],"primaryHuman":{"slug":"human","aliases":[]},"entries":[]}),0o600).unwrap();crate::worker::run_artifacts::write_run_json_atomic(&root.join("outcome.json"),&RunOutcome{version:1,run_id:"run".into(),attempt:None,finished_at:"now".into(),child_exit:crate::worker::run_artifacts::ChildExit{code:Some(code),signal:None},timed_out},0o600).unwrap();(engine.repo,ledger,failures)}
    #[test]fn actual_failure_ledger_recorded_once_across_sentinel_crash_replay(){let root=tempfile::tempdir().unwrap();let (repo,ledger,failures)=setup(root.path(),false,1);std::fs::create_dir(root.path().join("final.json")).unwrap();let mut io=Io{consumed:0};let mut terminal=FactsTerminalWrites{failures:&failures,io:&mut io};let mut apply=|_:&[FactsExtractionRecord]|panic!("failed child must not apply");assert!(finalize_claimed_facts_run(root.path(),&repo,&ledger,&mut terminal,&mut apply).is_err());assert!(root.path().join("facts-payload.json").exists());let before=failures.read_failures().unwrap();assert_eq!(before.entries.len(),1);std::fs::remove_dir(root.path().join("final.json")).unwrap();assert!(matches!(finalize_claimed_facts_run(root.path(),&repo,&ledger,&mut terminal,&mut apply).unwrap(),FactsLaunchResult::Failed{..}));let after=failures.read_failures().unwrap();assert_eq!(before.entries,after.entries);assert!(!root.path().join("facts-payload.json").exists());let final_record:serde_json::Value=read_run_json(&root.path().join("final.json")).unwrap();assert_eq!(final_record["outcome"],"failed");}
    #[test]fn empty_extraction_consumes_and_publishes_no_facts(){let root=tempfile::tempdir().unwrap();let (repo,ledger,failures)=setup(root.path(),false,0);std::fs::write(root.path().join("extraction.jsonl"),"\n").unwrap();let mut io=Io{consumed:0};assert!(matches!(finalize_claimed_facts_run(root.path(),&repo,&ledger,&mut FactsTerminalWrites{failures:&failures,io:&mut io},&mut |_|panic!("empty must not apply")).unwrap(),FactsLaunchResult::NoFacts{..}));assert!(failures.read_failures().unwrap().entries.is_empty());assert!(!root.path().join("facts-payload.json").exists());}
    #[test]fn invalid_extraction_and_writer_exhaustion_are_durable(){for (raw,exhausted) in [("invalid",false),(r#"{"scope":"project","text":"fact","date":"2026-08-12"}"#,true)]{let root=tempfile::tempdir().unwrap();let (repo,ledger,failures)=setup(root.path(),false,0);std::fs::write(root.path().join("extraction.jsonl"),raw).unwrap();let mut io=Io{consumed:0};assert!(matches!(finalize_claimed_facts_run(root.path(),&repo,&ledger,&mut FactsTerminalWrites{failures:&failures,io:&mut io},&mut |_|Ok(None)).unwrap(),FactsLaunchResult::Failed{..}));let entries=failures.read_failures().unwrap().entries;assert_eq!(entries.len(),1);assert_eq!(entries[0].last_reason,if exhausted{FactsFailureReason::MemoryWriteLockExhausted}else{FactsFailureReason::InvalidExtraction});}}
}
