use std::path::Path;
use memory_core::{facts::{extraction::{FactsBatch,FactsExtractionError,FactsExtractionRecord,validate_facts_recovery},mutation_plan::{MutationPlanError,plan_facts_mutation},person_routing::FactsPeopleRouting,recovery::{FactsRecoveryResult,apply_facts_recovery}},git::{GitMemoryRepo,GitCommitAuthor,errors::GitError}};
use crate::{facts_runner_types::FactsRunLedger,worker::run_artifacts::{ArtifactError,update_run_ledger}};
#[derive(Debug)]pub enum FactsApplyError{Git(GitError),Plan(MutationPlanError),Extraction(FactsExtractionError),Recovery(memory_core::facts::recovery::FactsRecoveryError),Artifact(ArtifactError)}
#[derive(Debug,PartialEq,Eq)]pub enum Applied{Committed{sha:String},ParentDirty{detail:Option<String>}}
pub fn apply_claimed(run_dir:&Path,ledger:&FactsRunLedger,repo:&GitMemoryRepo,records:&[FactsExtractionRecord],people:&FactsPeopleRouting,identity:&str)->Result<Applied,FactsApplyError>{
    if let Some(receipt)=repo.log(None).map_err(FactsApplyError::Git)?.into_iter().find(|entry|entry.trailers.get("Omo-Facts-Batch")==Some(&ledger.batch_id)){return Ok(Applied::Committed{sha:receipt.sha});}
    let batch=FactsBatch{batch_id:ledger.batch_id.clone(),records:records.to_vec()};
    let recovery=if let Some(recovery)=&ledger.apply_recovery{validate_facts_recovery(recovery,&batch).map_err(FactsApplyError::Extraction)?;recovery.clone()}else{
        let recovery=match plan_facts_mutation(repo,&batch,Some(people),None){Ok(recovery)=>recovery,Err(MutationPlanError::ParentDirty(_))=>return Ok(Applied::ParentDirty{detail:None}),Err(error)=>return Err(FactsApplyError::Plan(error))};
        let fields=serde_json::json!({"headBeforeApply":recovery.head_before_apply,"applyRecovery":recovery});update_run_ledger(&run_dir.join("ledger.json"),fields.as_object().expect("JSON object")).map_err(FactsApplyError::Artifact)?;recovery
    };
    match apply_facts_recovery(repo,&recovery,records.len(),&GitCommitAuthor{agent_id:identity.into(),author_name:"Facts Extractor".into(),author_email:None}).map_err(FactsApplyError::Recovery)?{FactsRecoveryResult::Committed{sha,..}=>Ok(Applied::Committed{sha}),FactsRecoveryResult::ParentDirty{detail}=>Ok(Applied::ParentDirty{detail})}
}
#[cfg(test)]mod tests{
    use super::*;
    fn ledger()->FactsRunLedger{serde_json::from_value(serde_json::json!({"version":1,"runId":"run","kind":"facts","startedAt":"now","hardDeadlineAt":1,"terminationGraceMs":1,"deadlineAt":2,"batchId":"c04edbea-90ea-4c67-9c22-1a9beb207535","queued":[]})).unwrap()}
    #[test]fn durable_recovery_precedes_commit_and_receipt_makes_replay_idempotent(){let root=tempfile::tempdir().unwrap();let paths=memory_core::identity::layout::build_identity_paths(root.path(),"agent");let engine=crate::engine_session::prepare_memory_engine_session("agent",&paths,Default::default()).unwrap();let run=root.path().join("run");std::fs::create_dir(&run).unwrap();let ledger=ledger();crate::worker::run_artifacts::write_run_json_atomic(&run.join("ledger.json"),&ledger,0o600).unwrap();let records=vec![FactsExtractionRecord::Project{text:"Project uses a durable journal".into(),date:"2026-08-12".into()}];let people=FactsPeopleRouting{enabled:true,max_entries:40,max_entry_chars:200};let first=apply_claimed(&run,&ledger,&engine.repo,&records,&people,"agent").unwrap();let persisted:FactsRunLedger=crate::worker::run_artifacts::read_run_json(&run.join("ledger.json")).unwrap();assert!(persisted.apply_recovery.is_some());assert!(persisted.head_before_apply.is_some());let sha=engine.repo.head().unwrap();let second=apply_claimed(&run,&persisted,&engine.repo,&records,&people,"agent").unwrap();assert_eq!(first,second);assert_eq!(engine.repo.head().unwrap(),sha);assert!(engine.repo.status(&[] as &[&str]).unwrap().trim().is_empty());}
    #[test]fn foreign_dirty_worktree_is_retained(){let root=tempfile::tempdir().unwrap();let paths=memory_core::identity::layout::build_identity_paths(root.path(),"agent");let engine=crate::engine_session::prepare_memory_engine_session("agent",&paths,Default::default()).unwrap();let foreign=paths.repo.join("foreign.txt");std::fs::write(&foreign,"user change").unwrap();let records=vec![FactsExtractionRecord::Project{text:"fact".into(),date:"2026-08-12".into()}];let people=FactsPeopleRouting{enabled:true,max_entries:40,max_entry_chars:200};assert_eq!(apply_claimed(root.path(),&ledger(),&engine.repo,&records,&people,"agent").unwrap(),Applied::ParentDirty{detail:None});assert_eq!(std::fs::read_to_string(foreign).unwrap(),"user change");assert!(!root.path().join("ledger.json").exists());}
}
