use std::path::{Path,PathBuf};
use memory_core::{facts::FactsQueueEntry,locks::{AcquireLockOptions,CreateLockRecordOptions,ProcessLiveness,create_lock_record,facts_runs_lock_path,get_pid_liveness,get_process_start_identity,with_lock}};
use crate::{facts_failure_recording::FactsQueuedKey,facts_runner_types::{FactsFinalRecord,FactsLaunchResult,FactsRunLedger,FactsTerminalOutcome},worker::run_artifacts::{ArtifactError,write_run_json_atomic}};
#[derive(Debug)]
pub enum FactsStorageError{Artifact(ArtifactError),LockRecord(memory_core::locks::LockRecordError),Lock(memory_core::locks::WithLockError<ArtifactError>),InvalidTimestamp,SequenceExhausted}
impl std::fmt::Display for FactsStorageError{fn fmt(&self,f:&mut std::fmt::Formatter<'_>)->std::fmt::Result{match self{Self::Artifact(error)=>error.fmt(f),Self::LockRecord(error)=>error.fmt(f),Self::Lock(error)=>error.fmt(f),Self::InvalidTimestamp=>f.write_str("Invalid facts launch timestamp"),Self::SequenceExhausted=>f.write_str("facts run sequence exhausted")}}}
impl std::error::Error for FactsStorageError{}
pub struct ReserveFactsRunDirOptions<'a>{pub facts_dir:&'a Path,pub locks_dir:&'a Path,pub entries:&'a [FactsQueueEntry],pub batch_id:&'a str,pub launched_at:i64,pub deadline_ms:Option<i64>,pub termination_grace_ms:Option<i64>,pub lock_wait_ms:Option<u64>}
pub fn queue_keys(entries:&[FactsQueueEntry])->Vec<FactsQueuedKey>{entries.iter().map(|entry|FactsQueuedKey{conversation_id:entry.conversation_id.clone(),end_message_id:entry.range.end_message_id.clone(),end_snapshot_line:entry.range.end_snapshot_line}).collect()}
fn next_attempt(runs:&Path,digest:&str)->u64{let prefix=format!("facts-{digest}-");std::fs::read_dir(runs).into_iter().flatten().filter_map(Result::ok).filter_map(|entry|{let name=entry.file_name().to_string_lossy().into_owned();let name=name.strip_prefix(".prune-").unwrap_or(&name);let rest=name.strip_prefix(&prefix)?;let end=rest.find(|character:char|!character.is_ascii_digit()).unwrap_or(rest.len());if end==0||!rest[end..].is_empty()&&!rest[end..].starts_with('-'){return None;}rest[..end].parse::<u64>().ok()}).max().unwrap_or(0)+1}
pub fn reserve_facts_run_dir(options:&ReserveFactsRunDirOptions<'_>)->Result<Option<PathBuf>,FactsStorageError>{
    let record=create_lock_record("facts-runs",CreateLockRecordOptions{run_id:Some(options.batch_id.into())}).map_err(FactsStorageError::LockRecord)?;
    let result=with_lock(&facts_runs_lock_path(options.locks_dir),&record,&AcquireLockOptions{wait_timeout_ms:Some(options.lock_wait_ms.unwrap_or(2000)),..Default::default()},||{
        let runs=options.facts_dir.join("runs");let mut builder=std::fs::DirBuilder::new();builder.recursive(true);#[cfg(unix)]{use std::os::unix::fs::DirBuilderExt;builder.mode(0o700);}builder.create(&runs)?;
        let keys=queue_keys(options.entries);let digest=memory_core::support::sha256::sha256_hex(serde_json::to_string(&keys)?.as_bytes());
        let started=chrono::DateTime::from_timestamp_millis(options.launched_at).ok_or_else(||ArtifactError::Io(std::io::Error::new(std::io::ErrorKind::InvalidInput,"Invalid facts launch timestamp")))?.to_rfc3339_opts(chrono::SecondsFormat::Millis,true);
        for attempt in next_attempt(&runs,&digest[..12])..10000{
            let dir=runs.join(format!("facts-{}-{attempt}",&digest[..12]));let mut builder=std::fs::DirBuilder::new();#[cfg(unix)]{use std::os::unix::fs::DirBuilderExt;builder.mode(0o700);}
            match builder.create(&dir){Ok(())=>{let grace=options.termination_grace_ms.unwrap_or(5000);let deadline=options.launched_at+options.deadline_ms.unwrap_or(900000);let ledger=serde_json::json!({"version":1,"runId":dir.file_name().unwrap_or_default().to_string_lossy(),"kind":"facts","startedAt":started,"hardDeadlineAt":deadline,"terminationGraceMs":grace,"deadlineAt":deadline+grace,"batchId":options.batch_id,"queued":keys});if let Err(error)=write_run_json_atomic(&dir.join("ledger.json"),&ledger,0o600){std::fs::remove_dir_all(&dir)?;return Err(error);}return Ok(Some(dir));},Err(error) if error.kind()==std::io::ErrorKind::AlreadyExists=>{if !crate::facts_run_cleanup::is_terminal_run_dir(&dir){return Ok(None);}},Err(error)=>return Err(error.into())}
        }
        Err(ArtifactError::Io(std::io::Error::other("facts run sequence exhausted")))
    }).map_err(FactsStorageError::Lock)?;
    Ok(result)
}
pub fn final_result(record:&FactsFinalRecord)->FactsLaunchResult{match record.outcome{FactsTerminalOutcome::Committed if record.sha.is_some()=>FactsLaunchResult::Committed{run_id:record.run_id.clone(),sha:record.sha.clone().expect("checked sha")},FactsTerminalOutcome::NoFacts=>FactsLaunchResult::NoFacts{run_id:record.run_id.clone()},FactsTerminalOutcome::ParentDirty=>FactsLaunchResult::ParentDirty{run_id:record.run_id.clone()},_=>FactsLaunchResult::Failed{run_id:record.run_id.clone()}}}
pub fn run_liveness_with(ledger:&FactsRunLedger,liveness:impl Fn(u32)->ProcessLiveness,start:impl Fn(u32)->Option<String>)->ProcessLiveness{let mut unknown=false;for (pid,recorded) in [(ledger.pid,ledger.process_start.as_deref()),(ledger.child_pid,ledger.child_process_start.as_deref())]{let Some(pid)=pid else{unknown=true;continue;};match liveness(pid){ProcessLiveness::Dead=>{},ProcessLiveness::Unknown=>unknown=true,ProcessLiveness::Alive=>{let Some(recorded)=recorded else{unknown=true;continue;};match start(pid){Some(actual) if actual==recorded=>return ProcessLiveness::Alive,None=>unknown=true,_=>{}}}}}if unknown{ProcessLiveness::Unknown}else{ProcessLiveness::Dead}}
pub fn run_liveness(ledger:&FactsRunLedger)->ProcessLiveness{run_liveness_with(ledger,get_pid_liveness,get_process_start_identity)}
pub fn write_facts_final(dir:&Path,run_id:&str,outcome:FactsTerminalOutcome,finished_at:&str,detail:Option<&str>,sha:Option<&str>,warn:&mut dyn FnMut(&str,&Path,&std::io::Error))->Result<(),ArtifactError>{let mut record=serde_json::json!({"version":1,"runId":run_id,"outcome":outcome,"finishedAt":finished_at});
    if let Some(detail)=detail{record["detail"]=detail.into();}
    if let Some(sha)=sha{record["sha"]=sha.into();}
    write_run_json_atomic(&dir.join("final.json"),&record,0o600)?;crate::facts_run_cleanup::cleanup_terminal_facts_run(dir,&mut crate::facts_run_cleanup::remove_run_artifact,warn);Ok(())}
#[cfg(test)]
mod tests{
    use super::*;
    #[test]fn reserves_monotonic_names_with_tombstone_high_water(){let root=tempfile::tempdir().unwrap();let options=ReserveFactsRunDirOptions{facts_dir:&root.path().join("facts"),locks_dir:&root.path().join("locks"),entries:&[],batch_id:"batch",launched_at:0,deadline_ms:None,termination_grace_ms:None,lock_wait_ms:None};let first=reserve_facts_run_dir(&options).unwrap().unwrap();assert!(first.file_name().unwrap().to_string_lossy().ends_with("-1"));let ledger:serde_json::Value=crate::worker::run_artifacts::read_run_json(&first.join("ledger.json")).unwrap();assert_eq!(ledger["deadlineAt"],905000);let second=reserve_facts_run_dir(&options).unwrap().unwrap();assert!(second.file_name().unwrap().to_string_lossy().ends_with("-2"));let tombstone=second.with_file_name(format!(".prune-{}-uuid",second.file_name().unwrap().to_string_lossy()));std::fs::rename(second,tombstone).unwrap();let third=reserve_facts_run_dir(&options).unwrap().unwrap();assert!(third.file_name().unwrap().to_string_lossy().ends_with("-3"));assert!(!facts_runs_lock_path(options.locks_dir).exists());}
    #[test]fn final_sentinel_precedes_disposable_cleanup(){let root=tempfile::tempdir().unwrap();std::fs::write(root.path().join("facts-payload.json"),"payload").unwrap();write_facts_final(root.path(),"run",FactsTerminalOutcome::NoFacts,"now",None,None,&mut |_,_,_|panic!("warn")).unwrap();assert!(root.path().join("final.json").exists());assert!(!root.path().join("facts-payload.json").exists());}
    #[test]fn committed_without_sha_degrades_to_failed(){assert_eq!(final_result(&FactsFinalRecord{version:1,run_id:"run".into(),outcome:FactsTerminalOutcome::Committed,sha:None}),FactsLaunchResult::Failed{run_id:"run".into()});}
}
