use std::{collections::BTreeMap,path::{Path,PathBuf}};
use super::sandbox_contracts::{SandboxError,SandboxPolicy,SandboxTransform};
pub struct PathSandboxInput<'a>{pub surface:&'a str,pub policy:SandboxPolicy,pub platform:&'a str,pub writable_dirs:&'a [PathBuf],pub lock_paths:&'a [PathBuf],pub payload_paths:&'a [PathBuf],pub fallback_dir:&'a Path,pub foreign_roots:&'a [PathBuf],pub command:&'a str,pub env:&'a BTreeMap<String,String>}
fn identity(warning:Option<String>)->SandboxTransform{SandboxTransform{was_sandboxed:false,warning,executable:None,inner_command:String::new(),profile:None,temp_dir:None,writable_dirs:vec![]}}
fn unavailable(input:&PathSandboxInput<'_>,reason:String)->Result<SandboxTransform,SandboxError>{if input.policy==SandboxPolicy::Required{Err(SandboxError::Unavailable{platform:input.platform.into(),reason})}else{Ok(identity(Some(format!("{} sandbox unavailable on {}: {reason}; running unsandboxed because policy is auto",input.surface,input.platform))))}}
fn canonical(path:&Path)->Result<PathBuf,SandboxError>{path.canonicalize().map_err(SandboxError::Io)}
pub fn build_path_sandbox_transform(input:&PathSandboxInput<'_>,which:&dyn Fn(&str)->Option<String>)->Result<SandboxTransform,SandboxError>{
    if input.policy==SandboxPolicy::Off{return Ok(identity(None));}
    let tool=match input.platform{"darwin"=>"sandbox-exec","linux"=>"bwrap",_=>return unavailable(input,"platform is unsupported".into())};
    let Some(executable)=which(tool)else{return unavailable(input,format!("{tool} not found"));};
    if input.platform!="darwin"&&!input.lock_paths.is_empty(){return unavailable(input,format!("{} sandbox cannot grant the agent lockfile paths ({}); bwrap has no minimal grant for entries that do not exist yet",input.platform,input.lock_paths.iter().map(|path|path.to_string_lossy()).collect::<Vec<_>>().join(", ")));}
    let writable_dirs=input.writable_dirs.iter().map(|path|canonical(path)).collect::<Result<Vec<_>,_>>()?;
    let (profile,temp_dir)=if input.platform=="darwin"{
        let payloads=input.payload_paths.iter().map(|path|canonical(path)).collect::<Result<Vec<_>,_>>()?;let foreign=input.foreign_roots.iter().map(|path|canonical(path)).collect::<Result<Vec<_>,_>>()?;
        let mut locks=vec![];let mut absent=vec![];for lock in input.lock_paths{let parent=lock.parent().unwrap_or(Path::new("."));if parent.exists(){locks.push(canonical(parent)?.join(lock.file_name().unwrap_or_default()));}else if !absent.contains(&parent){absent.push(parent);}}
        if !absent.is_empty(){return unavailable(input,format!("lock parent directories do not exist ({})",absent.iter().map(|path|path.to_string_lossy()).collect::<Vec<_>>().join(", ")));}
        let fallback;let first=if let Some(first)=payloads.first(){first}else{fallback=canonical(input.fallback_dir)?;&fallback};let temp=first.parent().unwrap_or(Path::new(".")).join(".sandbox-tmp");let mut builder=std::fs::DirBuilder::new();builder.recursive(true);
        #[cfg(unix)]{use std::os::unix::fs::DirBuilderExt;builder.mode(0o700);}
        builder.create(&temp).map_err(SandboxError::Io)?;
        let quote=|path:&Path|serde_json::Value::String(path.to_string_lossy().into_owned()).to_string();let mut lines=vec!["(version 1)".into(),"(allow default)".into(),"(deny file-write*)".into()];for path in writable_dirs.iter().chain(std::iter::once(&temp)){lines.push(format!("(allow file-write* (subpath {}))",quote(path)));}for path in locks{lines.push(format!("(allow file-write* (literal {}) (subpath {}))",quote(&path),quote(&path)));}lines.extend(["(allow file-write* (literal \"/dev/null\"))".into(),"(allow file-write* (literal \"/dev/tty\"))".into()]);for path in payloads{lines.push(format!("(allow file-read* (literal {}))",quote(&path)));}for path in foreign{lines.push(format!("(deny file-read* (subpath {}))",quote(&path)));}(Some(lines.join("\n")),Some(temp))
    }else{(None,None)};
    let inner=if Path::new(input.command).is_absolute(){Some(input.command.into())}else{input.env.get("PATH").and_then(|path|std::env::split_paths(path).filter(|entry|!entry.as_os_str().is_empty()).map(|entry|entry.join(input.command)).find(|path|is_executable(path))).map(|path|path.to_string_lossy().into_owned())};
    let Some(inner_command)=inner else{return Ok(identity(Some(format!("{} sandbox unavailable: inner command \"{}\" is not absolute and could not be resolved; running unsandboxed",input.surface,input.command))));};
    Ok(SandboxTransform{was_sandboxed:true,warning:None,executable:Some(executable),inner_command,profile,temp_dir,writable_dirs})
}
fn is_executable(path:&Path)->bool{
    #[cfg(unix)]{use std::os::unix::fs::PermissionsExt;std::fs::metadata(path).is_ok_and(|metadata|metadata.permissions().mode()&0o111!=0)}
    #[cfg(not(unix))]{path.exists()}
}
#[cfg(test)]mod tests{
    use super::*;use crate::sandbox_contracts::SandboxSpawnArgs;
    fn input<'a>(root:&'a Path,env:&'a BTreeMap<String,String>)->PathSandboxInput<'a>{PathSandboxInput{surface:"reflection",policy:SandboxPolicy::Required,platform:"linux",writable_dirs:&[],lock_paths:&[],payload_paths:&[],fallback_dir:root,foreign_roots:&[],command:"/bin/sh",env}}
    #[test]fn off_skips_detection(){let root=tempfile::tempdir().unwrap();let env=BTreeMap::new();let mut input=input(root.path(),&env);input.policy=SandboxPolicy::Off;let transform=build_path_sandbox_transform(&input,&|_|panic!("must not detect")).unwrap();assert!(!transform.was_sandboxed);assert!(transform.warning.is_none());}
    #[test]fn linux_wraps_command_and_preserves_environment(){let root=tempfile::tempdir().unwrap();let env=BTreeMap::new();let dirs=vec![root.path().to_owned()];let mut input=input(root.path(),&env);input.writable_dirs=&dirs;let transform=build_path_sandbox_transform(&input,&|_|Some("/usr/bin/bwrap".into())).unwrap();let original=SandboxSpawnArgs{command:"/bin/sh".into(),args:vec!["-c".into(),"exit 0".into()],cwd:root.path().into(),env:env.clone()};let result=transform.apply(original);assert!(transform.was_sandboxed);assert_eq!(result.command,"/usr/bin/bwrap");assert_eq!(&result.args[result.args.len()-4..],["--","/bin/sh","-c","exit 0"]);assert_eq!(result.env,env);assert!(result.args.contains(&"--bind".into()));}
    #[test]fn required_and_auto_missing_or_unsupported(){let root=tempfile::tempdir().unwrap();let env=BTreeMap::new();let mut input=input(root.path(),&env);assert!(matches!(build_path_sandbox_transform(&input,&|_|None),Err(SandboxError::Unavailable{..})));input.policy=SandboxPolicy::Auto;assert!(!build_path_sandbox_transform(&input,&|_|None).unwrap().was_sandboxed);input.platform="win32";assert!(build_path_sandbox_transform(&input,&|_|panic!("must not detect")).unwrap().warning.unwrap().contains("unsupported"));}
    #[test]fn unresolved_inner_degrades_even_required(){let root=tempfile::tempdir().unwrap();let env=BTreeMap::new();let mut input=input(root.path(),&env);input.command="missing";let transform=build_path_sandbox_transform(&input,&|_|Some("bwrap".into())).unwrap();assert!(!transform.was_sandboxed);assert!(transform.warning.unwrap().contains("could not be resolved"));}
    #[test]fn darwin_grants_only_absent_lock_entries(){let root=tempfile::tempdir().unwrap();let env=BTreeMap::new();let locks=vec![root.path().join("settings.json.lock")];let payloads=vec![root.path().join("payload.json")];std::fs::write(&payloads[0],"{}").unwrap();let mut input=input(root.path(),&env);input.platform="darwin";input.lock_paths=&locks;input.payload_paths=&payloads;let transform=build_path_sandbox_transform(&input,&|_|Some("sandbox-exec".into())).unwrap();let profile=transform.profile.unwrap();assert!(profile.contains("settings.json.lock"));assert!(!profile.contains("(allow file-write* (subpath /"));assert_eq!(transform.temp_dir.unwrap(),root.path().join(".sandbox-tmp"));}
    #[test]fn linux_cannot_grant_absent_lock_entry(){let root=tempfile::tempdir().unwrap();let env=BTreeMap::new();let locks=vec![root.path().join("settings.json.lock")];let mut input=input(root.path(),&env);input.lock_paths=&locks;assert!(matches!(build_path_sandbox_transform(&input,&|_|Some("bwrap".into())),Err(SandboxError::Unavailable{..})));}
}
