use maho_ext_pi_websearch::websearch::{config::*,types::*};
use serde_json::json;
#[test]fn invalid_utf8_config_string_uses_node_replacement(){let temp=tempfile::tempdir().unwrap();std::fs::create_dir(temp.path().join(".pi")).unwrap();let mut raw=br#"{"providers":[{"provider":"duckduckgo-html","id":"X"}]}"#.to_vec();let index=raw.windows(3).position(|bytes|bytes==b"\"X\"").unwrap();raw[index+1]=0xff;std::fs::write(temp.path().join(".pi/websearch.json"),raw).unwrap();let(config,_)=success(load_websearch_config(temp.path(),temp.path()).unwrap());assert_eq!(config.providers[0].config.id.as_deref(),Some("\u{fffd}"));}
fn success(result:ConfigLoadResult)->(WebsearchConfig,String){match result{ConfigLoadResult::Success{config,source}=>(config,source),ConfigLoadResult::Failure{message,..}=>panic!("unexpected config failure: {message}")}}
fn missing_key(provider:SearchProvider){let entry:SearchProviderEntry=serde_json::from_value(json!({"provider":provider})).unwrap_or_else(|error|panic!("provider fixture: {error}"));assert!(matches!(validate_provider_config(entry),ProviderValidationResult::Failure{reason:ProviderValidationFailureReason::MissingApiKey,..}));}
fn load_project(value:serde_json::Value)->WebsearchConfig{let temp=tempfile::tempdir().expect("temp");std::fs::create_dir(temp.path().join(".pi")).expect("config directory");let path=temp.path().join(".pi/websearch.json");std::fs::write(&path,value.to_string()).expect("config");let (config,source)=success(load_websearch_config(temp.path(),temp.path()).expect("load"));assert_eq!(source,path.to_string_lossy());config}
#[test]fn non_boolean_auto_rejected(){let value=json!({"strategy":"priority","fallback":true,"auto":"yes","providers":[{"provider":"exa","apiKey":"fixture"}]});assert!(matches!(validate_websearch_config_value(&value),Err((ConfigLoadFailureReason::InvalidConfig,_))));}
#[test]fn exa_missing_key(){missing_key(SearchProvider::Exa);}
#[test]fn tavily_missing_key(){missing_key(SearchProvider::Tavily);}
#[test]fn zai_missing_key(){missing_key(SearchProvider::Zai);}
#[test]fn xai_missing_key(){missing_key(SearchProvider::Xai);}
#[test]fn kimi_missing_key(){missing_key(SearchProvider::Kimi);}
#[test]fn codex_missing_key(){missing_key(SearchProvider::Codex);}
#[test]fn openai_missing_key(){missing_key(SearchProvider::Openai);}
#[test]fn anthropic_missing_key(){missing_key(SearchProvider::Anthropic);}
#[test]fn exa_key_accepted(){let entry:SearchProviderEntry=serde_json::from_value(json!({"provider":"exa","apiKey":"fixture"})).unwrap();assert!(matches!(validate_provider_config(entry),ProviderValidationResult::Success{..}));}
#[test]fn perplexity_key_accepted(){let entry:SearchProviderEntry=serde_json::from_value(json!({"provider":"perplexity","apiKey":"fixture"})).unwrap();assert!(matches!(validate_provider_config(entry),ProviderValidationResult::Success{..}));}
#[test]fn kimi_key_accepted(){let entry:SearchProviderEntry=serde_json::from_value(json!({"provider":"kimi","apiKey":"fixture"})).unwrap();assert!(matches!(validate_provider_config(entry),ProviderValidationResult::Success{..}));}
#[test]fn localhost_rejected(){let entry:SearchProviderEntry=serde_json::from_value(json!({"provider":"exa","baseUrl":"https://localhost/search"})).unwrap();assert!(matches!(validate_provider_config(entry),ProviderValidationResult::Failure{reason:ProviderValidationFailureReason::InvalidConfig,..}));}
#[test]fn private_ipv6_rejected(){for url in ["https://[::1]/search","https://[fd00::1]/search","https://[fe80::1]/search","https://[febf::1]/search","https://[::ffff:127.0.0.1]/search"]{let entry:SearchProviderEntry=serde_json::from_value(json!({"provider":"exa","baseUrl":url})).unwrap();assert!(matches!(validate_provider_config(entry),ProviderValidationResult::Failure{reason:ProviderValidationFailureReason::InvalidConfig,..}));}}
#[test]fn codex_command_does_not_supply_key(){let temp=tempfile::tempdir().unwrap();std::fs::create_dir(temp.path().join(".pi")).unwrap();std::fs::write(temp.path().join(".pi/websearch.json"),r#"{"provider":"codex","codexCommand":"codex"}"#).unwrap();assert!(matches!(load_websearch_config(temp.path(),temp.path()).unwrap(),ConfigLoadResult::Failure{reason:ConfigLoadFailureReason::MissingApiKey,..}));}
#[test]fn missing_config_uses_free_default(){let temp=tempfile::tempdir().unwrap();let (config,source)=success(load_websearch_config(temp.path(),temp.path()).unwrap());assert_eq!(source,"default:duckduckgo-html");assert_eq!(config.providers[0].config.provider,SearchProvider::DuckduckgoHtml);assert_eq!(config.providers[0].config.max_results,Some(10.0));}
#[test]fn project_overrides_global(){let temp=tempfile::tempdir().unwrap();std::fs::create_dir(temp.path().join(".pi")).unwrap();std::fs::write(temp.path().join(".pi/websearch.json"),r#"{"provider":"exa","apiKey":"fixture-project"}"#).unwrap();std::fs::write(temp.path().join("websearch.json"),r#"{"provider":"tavily","apiKey":"fixture-global"}"#).unwrap();let (config,_)=success(load_websearch_config(temp.path(),temp.path()).unwrap());assert_eq!(config.providers[0].config.provider,SearchProvider::Exa);}
#[test]fn backend_alias_is_preserved(){let config=load_project(json!({"backend":"brave","apiKey":"fixture"}));assert_eq!(config.providers[0].config.provider,SearchProvider::Brave);}
#[test]fn routing_policy_is_preserved(){let config=load_project(json!({"strategy":"round-robin","providers":[{"provider":"anthropic","apiKey":"fixture","weight":2},{"provider":"exa","apiKey":"fixture","priority":10}]}));assert_eq!(config.strategy,RoutingStrategy::RoundRobin);assert_eq!(config.providers.len(),2);assert_eq!(config.providers[0].weight,Some(2.0));}
#[test]fn legacy_auto_false(){assert!(!load_project(json!({"provider":"exa","apiKey":"fixture","auto":false})).auto);}
#[test]fn multi_provider_auto_false(){assert!(!load_project(json!({"providers":[{"provider":"exa","apiKey":"fixture"}],"auto":false})).auto);}
#[test]fn empty_providers_rejected(){let temp=tempfile::tempdir().expect("temp");std::fs::create_dir(temp.path().join(".pi")).expect("directory");std::fs::write(temp.path().join(".pi/websearch.json"),r#"{"providers":[]}"#).expect("config");assert!(matches!(load_websearch_config(temp.path(),temp.path()).expect("load"),ConfigLoadResult::Failure{reason:ConfigLoadFailureReason::InvalidConfig,..}));}
#[test]fn timeout_is_preserved(){let config=load_project(json!({"providers":[{"provider":"exa","apiKey":"fixture","timeoutMs":15000}]}));assert_eq!(config.providers[0].config.timeout_ms,Some(15000.0));}
#[test]fn zero_timeout_rejected(){let entry:SearchProviderEntry=serde_json::from_value(json!({"provider":"exa","apiKey":"fixture","timeoutMs":0})).unwrap();assert!(matches!(validate_provider_config(entry),ProviderValidationResult::Failure{reason:ProviderValidationFailureReason::InvalidConfig,..}));}
#[test]fn conflicting_domains_rejected(){let entry:SearchProviderEntry=serde_json::from_value(json!({"provider":"brave","apiKey":"fixture","allowedDomains":[],"blockedDomains":[]})).unwrap();assert!(matches!(validate_provider_config(entry),ProviderValidationResult::Failure{reason:ProviderValidationFailureReason::InvalidConfig,..}));}
#[test]fn google_requires_engine_id(){let entry:SearchProviderEntry=serde_json::from_value(json!({"provider":"google-cse","apiKey":"fixture"})).unwrap();assert!(matches!(validate_provider_config(entry),ProviderValidationResult::Failure{reason:ProviderValidationFailureReason::MissingApiKey,..}));}
#[test]fn unsafe_base_url_rejected(){let entry:SearchProviderEntry=serde_json::from_value(json!({"provider":"tavily","apiKey":"fixture","baseUrl":"http://127.0.0.1:8080"})).unwrap();assert!(matches!(validate_provider_config(entry),ProviderValidationResult::Failure{reason:ProviderValidationFailureReason::InvalidConfig,..}));}
#[test]fn public_base_url_accepted(){let entry:SearchProviderEntry=serde_json::from_value(json!({"provider":"tavily","apiKey":"fixture","baseUrl":"https://search-gateway.example.com/tavily"})).unwrap();assert!(matches!(validate_provider_config(entry),ProviderValidationResult::Success{..}));}
#[test]fn credentials_in_url_rejected(){let entry:SearchProviderEntry=serde_json::from_value(json!({"provider":"tavily","apiKey":"fixture","baseUrl":"https://user:pass@search-gateway.example.com/tavily"})).unwrap();assert!(matches!(validate_provider_config(entry),ProviderValidationResult::Failure{reason:ProviderValidationFailureReason::InvalidConfig,..}));}
