use maho_ext_pi_websearch::websearch::{providers::*,types::*};
use serde_json::{Value,json};
fn config(value:Value)->SearchProviderConfig{serde_json::from_value(value).expect("provider fixture")}
fn request(query:&str,max:f64)->SearchRequest{SearchRequest{query:query.into(),max_results:max,allowed_domains:None,blocked_domains:None}}
fn body(config:Value,request:SearchRequest)->Value{js_numbers(json!(build_search_request(&self::config(config),&request).expect("valid endpoint").body.expect("POST body")))}
// JavaScript has one numeric type. Compare parsed JSON numbers by value,
// without conflating serde_json's integer/float storage distinction with parity.
fn js_numbers(value:Value)->Value{match value{Value::Number(number)=>{let float=number.as_f64().expect("JSON number");if float.fract()==0.0{float.to_string().parse().expect("integral JSON number")}else{Value::Number(number)}},Value::Array(values)=>Value::Array(values.into_iter().map(js_numbers).collect()),Value::Object(values)=>Value::Object(values.into_iter().map(|(key,value)|(key,js_numbers(value))).collect()),other=>other}}
fn normalized(provider:SearchProvider,payload:Value)->Value{json!(normalize_search_response(provider,&payload))}
#[test]fn overridden_endpoints(){for provider in ["exa","tavily","brave","serper","google-cse","z-ai","openai","codex","anthropic","perplexity","xai","kimi"]{let endpoint=format!("https://gateway.example.com/{provider}");let config=config(json!({"provider":provider,"baseUrl":endpoint}));assert!(build_search_request(&config,&request("override endpoint",4.0)).expect("endpoint").url.starts_with(&endpoint));}}
#[test]fn exa_request(){let config=config(json!({"provider":"exa","apiKey":"exa-test"}));let built=build_search_request(&config,&request("pi extension",4.0)).expect("endpoint");assert_eq!(built.url,"https://api.exa.ai/search");assert_eq!(built.init.method,HttpMethod::Post);assert_eq!(built.init.headers["x-api-key"],"exa-test");assert_eq!(js_numbers(json!(built.body)),json!({"query":"pi extension","numResults":4}));}
#[test]fn tavily_request(){let config=config(json!({"provider":"tavily","apiKey":"tvly-test"}));let built=build_search_request(&config,&request("current docs",5.0)).expect("endpoint");assert_eq!(built.url,"https://api.tavily.com/search");assert_eq!(built.init.headers["Authorization"],"Bearer tvly-test");assert_eq!(js_numbers(json!(built.body)),json!({"query":"current docs","max_results":5}));}
#[test]fn brave_request_allowlist(){let config=config(json!({"provider":"brave","apiKey":"brave-test"}));let mut request=request("node fetch",2.0);request.allowed_domains=Some(vec!["nodejs.org".into()]);let built=build_search_request(&config,&request).expect("endpoint");assert!(built.url.contains("site%3Anodejs.org"));assert_eq!(built.init.headers["X-Subscription-Token"],"brave-test");}
#[test]fn duckduckgo_request(){let config=config(json!({"provider":"duckduckgo-html"}));let mut request=request("zero config search",4.0);request.blocked_domains=Some(vec!["spam.example.com".into()]);let built=build_search_request(&config,&request).expect("endpoint");assert!(built.url.contains("q=zero+config+search+-site%3Aspam.example.com"));assert_eq!(built.init.method,HttpMethod::Get);assert_eq!(built.init.headers["Accept"],"text/html");assert!(built.body.is_none());}
#[test]fn config_allowlist_request_allowlist(){let mut request=request("sdk docs",3.0);request.allowed_domains=Some(vec!["api.example.com".into(),"other.example.com".into()]);assert_eq!(body(json!({"provider":"exa","allowedDomains":["docs.example.com","api.example.com"]}),request),json!({"query":"sdk docs","numResults":3,"includeDomains":["api.example.com"]}));}
#[test]fn config_allowlist_request_blocklist(){let mut request=request("sdk docs",3.0);request.blocked_domains=Some(vec!["docs.example.com".into()]);assert_eq!(body(json!({"provider":"exa","allowedDomains":["docs.example.com","api.example.com"]}),request),json!({"query":"sdk docs","numResults":3,"includeDomains":["api.example.com"]}));}
#[test]fn config_blocklist_cannot_be_reintroduced(){let config=config(json!({"provider":"brave","apiKey":"brave-test","blockedDomains":["blocked.example.com"]}));let mut request=request("node fetch",2.0);request.allowed_domains=Some(vec!["blocked.example.com".into(),"nodejs.org".into()]);let built=build_search_request(&config,&request).expect("endpoint");assert!(!built.url.contains("blocked.example.com"));assert!(built.url.contains("site%3Anodejs.org"));}
#[test]fn zai_direct_request(){let config=config(json!({"provider":"z-ai","apiKey":"zai-test"}));let built=build_search_request(&config,&request("financial news",15.0)).expect("endpoint");assert_eq!(built.url,"https://api.z.ai/api/paas/v4/web_search");assert_eq!(built.init.headers["Authorization"],"Bearer zai-test");assert_eq!(js_numbers(json!(built.body)),json!({"search_engine":"search-prime","search_query":"financial news","count":15}));}
#[test]fn responses_cached_request(){let config=config(json!({"provider":"openai","apiKey":"openai-test","model":"gpt-5.5","codexMode":"cached","searchContextSize":"high"}));let built=build_search_request(&config,&request("latest OpenAI web search docs",5.0)).expect("endpoint");assert_eq!(built.url,"https://api.openai.com/v1/responses");assert_eq!(built.init.headers["Authorization"],"Bearer openai-test");let body=built.body.expect("body");assert_eq!(body["tools"],json!([{"type":"web_search","external_web_access":false,"search_context_size":"high"}]));assert_eq!(body["include"],json!(["web_search_call.action.sources"]));assert_eq!(body["tool_choice"],"required");}
#[test]fn codex_blocklist(){let body=body(json!({"provider":"codex","apiKey":"openai-test","blockedDomains":["spam.example.com"]}),request("latest docs",5.0));assert!(body["input"].as_str().expect("input").ends_with("latest docs -site:spam.example.com"));assert_eq!(body["tools"],json!([{"type":"web_search","external_web_access":true}]));}
#[test]fn perplexity_direct_request(){assert_eq!(body(json!({"provider":"perplexity","apiKey":"pplx-test","allowedDomains":["docs.example.com"]}),request("search api docs",25.0)),json!({"query":"search api docs","max_results":20,"search_domain_filter":["docs.example.com"]}));}
#[test]fn perplexity_chat_request(){assert_eq!(body(json!({"provider":"perplexity","apiKey":"pplx-test","baseUrl":"https://api.perplexity.ai/chat/completions","model":"sonar-pro","allowedDomains":["docs.example.com"]}),request("search api docs",25.0)),json!({"model":"sonar-pro","messages":[{"role":"user","content":"search api docs"}],"search_domain_filter":["docs.example.com"]}));}
#[test]fn xai_request(){assert_eq!(body(json!({"provider":"xai","apiKey":"xai-test","model":"grok-4.3","blockedDomains":["spam.example.com"]}),request("current xai docs",5.0)),json!({"model":"grok-4.3","input":"current xai docs","tools":[{"type":"web_search","filters":{"excluded_domains":["spam.example.com"]}}],"tool_choice":"required"}));}
#[test]fn anthropic_request(){assert_eq!(body(json!({"provider":"anthropic","apiKey":"anthropic-test","baseUrl":"https://anthropic.gateway.example.com/v1/messages","model":"claude-sonnet-4-5-20250929","allowedDomains":["docs.example.com"]}),request("current anthropic search docs",5.0)),json!({"model":"claude-sonnet-4-5-20250929","max_tokens":1024,"messages":[{"role":"user","content":"current anthropic search docs"}],"tools":[{"type":"web_search_20250305","name":"web_search","max_uses":8,"allowed_domains":["docs.example.com"]}]}));}
#[test]fn zai_chat_request(){assert_eq!(body(json!({"provider":"z-ai","apiKey":"zai-test","baseUrl":"https://api.z.ai/chat/completions","model":"glm-4.6","allowedDomains":["docs.example.com"]}),request("financial news",15.0)),json!({"model":"glm-4.6","messages":[{"role":"user","content":"financial news"}],"tools":[{"type":"web_search","web_search":{"enable":true,"search_engine":"search-prime","search_result":true,"count":15,"search_domain_filter":"docs.example.com"}}]}));}
#[test]fn kimi_request(){assert_eq!(body(json!({"provider":"kimi","apiKey":"kimi-test"}),request("current docs",5.0)),json!({"text_query":"current docs","limit":5,"enable_page_crawling":false,"timeout_seconds":30}));}
#[test]fn duckduckgo_response(){assert_eq!(normalized(SearchProvider::DuckduckgoHtml,json!({"html":r#"<a class="result__a" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fdocs.example.com%2Fpi&amp;rut=abc">Pi Docs</a><a class="result__snippet">Useful docs snippet</a>"#})),json!([{"title":"Pi Docs","url":"https://docs.example.com/pi","snippet":"Useful docs snippet"}]));}
#[test]fn tavily_response(){assert_eq!(normalized(SearchProvider::Tavily,json!({"results":[{"title":"Docs","url":"https://docs.example.com","content":"Useful docs","score":0.9}],"response_time":1.25})),json!([{"title":"Docs","url":"https://docs.example.com","snippet":"Useful docs","score":0.9}]));}
#[test]fn serper_response(){assert_eq!(normalized(SearchProvider::Serper,json!({"organic":[{"title":"Result","link":"https://example.com","snippet":"Snippet","position":1}]})),json!([{"title":"Result","url":"https://example.com","snippet":"Snippet"}]));}
#[test]fn zai_response(){assert_eq!(normalized(SearchProvider::Zai,json!({"search_result":[{"title":"Z Result","link":"https://z.example.com","content":"Z snippet","media":"Example"}]})),json!([{"title":"Z Result","url":"https://z.example.com","snippet":"Z snippet","source":"Example"}]));}
#[test]fn codex_annotations(){assert_eq!(normalized(SearchProvider::Codex,json!({"output":[{"type":"message","content":[{"type":"output_text","text":"Answer with source","annotations":[{"type":"url_citation","url":"https://openai.com","title":"OpenAI","start_index":0,"end_index":6}]}]}]})),json!([{"title":"OpenAI","url":"https://openai.com","snippet":"Answer with source"}]));}
#[test]fn openai_text_url(){assert_eq!(normalized(SearchProvider::Openai,json!({"output":[{"type":"web_search_call","status":"completed","action":{"type":"search","queries":["oh my openagent"]}},{"type":"message","content":[{"type":"output_text","text":"https://ohmyopenagent.com/","annotations":[]}]}]})),json!([{"title":"https://ohmyopenagent.com/","url":"https://ohmyopenagent.com/","snippet":"https://ohmyopenagent.com/"}]));}
#[test]fn perplexity_response(){assert_eq!(normalized(SearchProvider::Perplexity,json!({"results":[{"title":"Perplexity","url":"https://docs.perplexity.ai","snippet":"Search docs","date":"2026-01-01"}]})),json!([{"title":"Perplexity","url":"https://docs.perplexity.ai","snippet":"Search docs","publishedAt":"2026-01-01"}]));}
#[test]fn perplexity_chat_response(){assert_eq!(normalized(SearchProvider::Perplexity,json!({"choices":[{"message":{"content":"Answer with sources"}}],"search_results":[{"title":"Perplexity","url":"https://docs.perplexity.ai","snippet":"Search docs","date":"2026-01-01"}]})),json!([{"title":"Perplexity","url":"https://docs.perplexity.ai","snippet":"Search docs","publishedAt":"2026-01-01"}]));}
#[test]fn xai_citations(){assert_eq!(normalized(SearchProvider::Xai,json!({"output":[{"type":"message","content":[{"type":"output_text","text":"Answer from Grok","annotations":[]}]}],"citations":["https://x.ai"]})),json!([{"title":"https://x.ai","url":"https://x.ai","snippet":"Answer from Grok"}]));}
#[test]fn anthropic_response(){assert_eq!(normalized(SearchProvider::Anthropic,json!({"content":[{"type":"text","text":"Answer with Anthropic source"},{"type":"web_search_tool_result","content":[{"type":"web_search_result","title":"Anthropic","url":"https://docs.anthropic.com","page_age":"2026-01-01"}]}]})),json!([{"title":"Anthropic","url":"https://docs.anthropic.com","snippet":"2026-01-01"}]));}
#[test]fn zai_chat_response(){assert_eq!(normalized(SearchProvider::Zai,json!({"choices":[{"message":{"content":"Answer with Z.ai source"}}],"web_search":[{"title":"Z Result","link":"https://z.example.com","content":"Z snippet","media":"Example"}]})),json!([{"title":"Z Result","url":"https://z.example.com","snippet":"Z snippet","source":"Example"}]));}
#[test]fn kimi_response(){assert_eq!(normalized(SearchProvider::Kimi,json!({"answer":"Synthesized answer","search_results":[{"title":"Kimi Result","url":"https://kimi.example.com","summary":"Kimi snippet","content":"Full content"}]})),json!([{"title":"Kimi Result","url":"https://kimi.example.com","snippet":"Kimi snippet"}]));}
