use maho_ext_pi_websearch::websearch::{search::*,types::*};
use tokio::{io::{AsyncReadExt,AsyncWriteExt},net::TcpListener};
use tokio_util::sync::CancellationToken;
async fn serve_responses(responses:Vec<(u16,String)>)->(String,tokio::task::JoinHandle<()>){
    let listener=TcpListener::bind("127.0.0.1:0").await.expect("bind");let address=listener.local_addr().expect("address");let task=tokio::spawn(async move{for (status,body) in responses{let (mut stream,_)=listener.accept().await.expect("accept");let mut bytes=Vec::new();loop{let mut buffer=[0;1024];let count=stream.read(&mut buffer).await.expect("read");assert_ne!(count,0);bytes.extend_from_slice(&buffer[..count]);if bytes.windows(4).any(|window|window==b"\r\n\r\n"){break;}}let response=format!("HTTP/1.1 {status} Fixture\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",body.len());stream.write_all(response.as_bytes()).await.expect("write");}});(format!("http://{address}"),task)
}
async fn scenario(responses:Vec<(u16,String)>,fallback:bool)->SearchDetails{
    let count=responses.len();let (base,server)=serve_responses(responses).await;let config=WebsearchConfig{strategy:RoutingStrategy::Priority,fallback,auto:true,providers:(0..count).map(|index|serde_json::from_value(serde_json::json!({"provider":"exa","id":format!("route{index}"),"baseUrl":format!("{base}/{index}")})).expect("provider")).collect()};let request=SearchRequest{query:"test".into(),max_results:2.0,allowed_domains:None,blocked_domains:None};let mut state=create_search_routing_state(count);let result=tokio::time::timeout(std::time::Duration::from_secs(5),perform_search(&reqwest::Client::new(),&config,&request,None,&mut state,None)).await.expect("scenario timeout").expect("search");server.await.expect("server");result
}
#[tokio::test]async fn nested_http_error(){let result=scenario(vec![(400,serde_json::json!({"error":{"message":"max_tokens must be at least 1024"}}).to_string())],false).await;assert_eq!(result.error.as_deref(),Some("Search failed with HTTP 400: max_tokens must be at least 1024"));}
#[tokio::test]async fn string_http_error(){let result=scenario(vec![(400,serde_json::json!({"error":"Bad Request"}).to_string())],false).await;assert_eq!(result.error.as_deref(),Some("Search failed with HTTP 400: Bad Request"));}
#[tokio::test]async fn raw_http_error(){let result=scenario(vec![(530,"error code: 530".into())],false).await;assert_eq!(result.error.as_deref(),Some("Search failed with HTTP 530: error code: 530"));}
#[tokio::test]async fn empty_http_error(){let result=scenario(vec![(502,String::new())],false).await;assert_eq!(result.error.as_deref(),Some("Search failed with HTTP 502"));}
#[tokio::test]async fn long_http_error(){let result=scenario(vec![(400,serde_json::json!({"error":{"message":"x".repeat(2000)}}).to_string())],false).await;let error=result.error.expect("error");assert_eq!(error,"Search failed with HTTP 400: ".to_owned()+&"x".repeat(499)+"…");}
#[tokio::test]async fn empty_primary_falls_back(){let result=scenario(vec![(200,"{\"results\":[]}".into()),(200,serde_json::json!({"results":[{"title":"Fallback","url":"https://fallback.example.com"}]}).to_string())],true).await;assert_eq!(result.entry_id.as_deref(),Some("route1"));assert_eq!(result.results.len(),1);assert_eq!(result.attempts.expect("attempts").len(),2);}
#[tokio::test]async fn all_empty_aggregates_errors(){let result=scenario(vec![(200,"{\"results\":[]}".into()),(200,"{\"results\":[]}".into())],true).await;assert!(result.error.is_some());assert_eq!(result.attempts.expect("attempts").len(),2);assert!(result.results.is_empty());}
#[tokio::test]async fn no_fallback_stops_on_empty(){let result=scenario(vec![(200,"{\"results\":[]}".into())],false).await;assert!(result.error.is_some());assert_eq!(result.attempts.expect("attempts").len(),1);}
#[tokio::test]async fn aggregate_http_failures_keeps_each_detail(){let result=scenario(vec![(400,"{\"error\":{\"message\":\"model not supported\"}}".into()),(530,"origin unreachable".into())],true).await;let attempts=result.attempts.expect("attempts");assert_eq!(attempts[0].error.as_deref(),Some("Search failed with HTTP 400: model not supported"));assert_eq!(attempts[1].error.as_deref(),Some("Search failed with HTTP 530: origin unreachable"));assert!(result.error.expect("aggregate error").contains("exa/route1"));}
#[tokio::test]
async fn real_http_primary_failure_falls_back_and_reports_attempts(){
    let listener=TcpListener::bind("127.0.0.1:0").await.unwrap_or_else(|error|panic!("bind: {error}"));let address=listener.local_addr().unwrap_or_else(|error|panic!("address: {error}"));
    let server=tokio::spawn(async move{
        for (status,body) in [("503 Service Unavailable",r#"{"error":"down"}"#),("200 OK",r#"{"results":[{"title":"Fallback","url":"https://fallback.example.com","text":"result"}]}"#)]{
            let (mut stream,_)=listener.accept().await.unwrap_or_else(|error|panic!("accept: {error}"));let mut bytes=Vec::new();
            loop{let mut buffer=[0;1024];let read=stream.read(&mut buffer).await.unwrap_or_else(|error|panic!("read: {error}"));assert_ne!(read,0);bytes.extend_from_slice(&buffer[..read]);if bytes.windows(4).any(|window|window==b"\r\n\r\n"){break;}}
            let response=format!("HTTP/1.1 {status}\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",body.len());stream.write_all(response.as_bytes()).await.unwrap_or_else(|error|panic!("write: {error}"));
        }
    });
    let providers=["primary","fallback"].into_iter().map(|id|serde_json::from_value(serde_json::json!({"provider":"exa","id":id,"baseUrl":format!("http://{address}/{id}")})).unwrap_or_else(|error|panic!("config: {error}"))).collect();
    let config=WebsearchConfig{strategy:RoutingStrategy::Priority,fallback:true,auto:true,providers};let request=SearchRequest{query:"route test".into(),max_results:3.0,allowed_domains:None,blocked_domains:None};let mut state=create_search_routing_state(2);
    let details=tokio::time::timeout(std::time::Duration::from_secs(5),perform_search(&reqwest::Client::new(),&config,&request,None,&mut state,None)).await.unwrap_or_else(|error|panic!("search timeout: {error}")).unwrap_or_else(|error|panic!("search: {error}"));
    assert_eq!(details.entry_id.as_deref(),Some("fallback"));assert_eq!(details.results.len(),1);let attempts=details.attempts.unwrap_or_else(||panic!("missing attempts"));assert_eq!(attempts.len(),2);assert_eq!(attempts[0].error.as_deref(),Some("Search failed with HTTP 503: down"));assert_eq!(state.success_counts,vec![0.0,1.0]);server.await.unwrap_or_else(|error|panic!("server: {error}"));
}
#[tokio::test]
async fn preaborted_search_propagates_without_network(){
    let signal=CancellationToken::new();signal.cancel();let config:SearchProviderEntry=serde_json::from_value(serde_json::json!({"provider":"exa"})).unwrap_or_else(|error|panic!("config: {error}"));let request=SearchRequest{query:"abort".into(),max_results:1.0,allowed_domains:None,blocked_domains:None};
    assert!(perform_provider_search(&reqwest::Client::new(),&config,&request,Some(&signal)).await.is_err());
}
#[tokio::test]
async fn hanging_provider_times_out_and_falls_through(){
    let listener=TcpListener::bind("127.0.0.1:0").await.expect("bind");let address=listener.local_addr().expect("address");let server=tokio::spawn(async move{let (mut hanging,_)=listener.accept().await.expect("hang accept");let mut bytes=Vec::new();loop{let mut buffer=[0;1024];let count=hanging.read(&mut buffer).await.expect("headers");if count==0{break;}bytes.extend_from_slice(&buffer[..count]);if bytes.windows(4).any(|window|window==b"\r\n\r\n"){break;}}let (mut quick,_)=listener.accept().await.expect("fallback accept");let mut bytes=Vec::new();loop{let mut buffer=[0;1024];let count=quick.read(&mut buffer).await.expect("fallback headers");assert_ne!(count,0);bytes.extend_from_slice(&buffer[..count]);if bytes.windows(4).any(|window|window==b"\r\n\r\n"){break;}}let body=r#"{"results":[{"title":"Quick","url":"https://quick.example.com"}]}"#;quick.write_all(format!("HTTP/1.1 200 OK\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",body.len()).as_bytes()).await.expect("write");});
    let config=WebsearchConfig{strategy:RoutingStrategy::Priority,fallback:true,auto:false,providers:vec![serde_json::from_value(serde_json::json!({"provider":"exa","id":"hang","baseUrl":format!("http://{address}/hang"),"timeoutMs":50})).expect("hang provider"),serde_json::from_value(serde_json::json!({"provider":"exa","id":"quick","baseUrl":format!("http://{address}/quick")})).expect("quick provider")]};let request=SearchRequest{query:"timeout route".into(),max_results:1.0,allowed_domains:None,blocked_domains:None};let mut state=create_search_routing_state(2);let result=tokio::time::timeout(std::time::Duration::from_secs(5),perform_search(&reqwest::Client::new(),&config,&request,None,&mut state,None)).await.expect("outer timeout").expect("search");assert_eq!(result.entry_id.as_deref(),Some("quick"));assert_eq!(result.attempts.expect("attempts")[0].error.as_deref(),Some("Search timed out after 50ms"));server.await.expect("server");
}
#[tokio::test]
async fn abort_during_request_propagates_and_disconnects_socket(){
    let listener=TcpListener::bind("127.0.0.1:0").await.expect("bind");let address=listener.local_addr().expect("address");let (ready_tx,ready_rx)=tokio::sync::oneshot::channel();let server=tokio::spawn(async move{let (mut stream,_)=listener.accept().await.expect("accept");let mut bytes=Vec::new();loop{let mut buffer=[0;1024];let count=stream.read(&mut buffer).await.expect("read");assert_ne!(count,0);bytes.extend_from_slice(&buffer[..count]);if bytes.windows(4).any(|window|window==b"\r\n\r\n"){break;}}ready_tx.send(()).expect("ready");let mut buffer=[0;1024];loop{if stream.read(&mut buffer).await.expect("disconnect")==0{break;}}});
    let signal=CancellationToken::new();let search_signal=signal.clone();let search=tokio::spawn(async move{let config:SearchProviderEntry=serde_json::from_value(serde_json::json!({"provider":"exa","baseUrl":format!("http://{address}")})).expect("provider");let request=SearchRequest{query:"abort".into(),max_results:1.0,allowed_domains:None,blocked_domains:None};perform_provider_search(&reqwest::Client::new(),&config,&request,Some(&search_signal)).await});
    tokio::time::timeout(std::time::Duration::from_secs(5),ready_rx).await.expect("request timeout").expect("ready");signal.cancel();assert!(tokio::time::timeout(std::time::Duration::from_secs(5),search).await.expect("search timeout").expect("search join").is_err());tokio::time::timeout(std::time::Duration::from_secs(5),server).await.expect("disconnect timeout").expect("server join");
}
#[tokio::test]
async fn fill_first_replaces_duplicate_without_reordering_and_reports_progress(){
    let listener=TcpListener::bind("127.0.0.1:0").await.expect("bind");let address=listener.local_addr().expect("address");
    let server=tokio::spawn(async move{for body in [r#"{"results":[{"title":"Shared","url":"https://shared.example.com","text":"first"}]}"#,r#"{"results":[{"title":"Shared duplicate","url":"https://shared.example.com","text":"duplicate"},{"title":"Second","url":"https://second.example.com","text":"second"}]}"#]{let (mut stream,_)=listener.accept().await.expect("accept");let mut bytes=Vec::new();loop{let mut buffer=[0;1024];let count=stream.read(&mut buffer).await.expect("read");assert_ne!(count,0);bytes.extend_from_slice(&buffer[..count]);if bytes.windows(4).any(|window|window==b"\r\n\r\n"){break;}}let response=format!("HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",body.len());stream.write_all(response.as_bytes()).await.expect("write");}});
    let config=WebsearchConfig{strategy:RoutingStrategy::FillFirst,fallback:true,auto:true,providers:["one","two"].into_iter().map(|id|serde_json::from_value(serde_json::json!({"provider":"exa","id":id,"baseUrl":format!("http://{address}/{id}")})).expect("provider")).collect()};let request=SearchRequest{query:"fill".into(),max_results:2.0,allowed_domains:None,blocked_domains:None};let mut state=create_search_routing_state(2);let mut updates=Vec::new();let mut listener=|label:&str,attempts:&[SearchAttempt],routes:&[String]|updates.push((label.to_owned(),attempts.len(),routes.to_vec()));
    let details=tokio::time::timeout(std::time::Duration::from_secs(5),perform_search(&reqwest::Client::new(),&config,&request,None,&mut state,Some(&mut listener))).await.expect("search timeout").expect("search");assert_eq!(details.results.iter().map(|item|item.url.as_str()).collect::<Vec<_>>(),vec!["https://shared.example.com","https://second.example.com"]);assert_eq!(details.results[0].title,"Shared duplicate");assert_eq!(details.entry_id.as_deref(),Some("two"));assert!(details.truncated);assert_eq!(state.success_counts,vec![1.0,1.0]);assert_eq!(updates,vec![("exa/one".into(),0,vec!["exa/one".into(),"exa/two".into()]),("exa/two".into(),1,vec!["exa/one".into(),"exa/two".into()])]);server.await.expect("server");
}
