use maho_ext_pi_websearch::websearch::{tool::*,types::*};
#[tokio::test]
async fn conflicting_filters_precede_configuration_failure(){
    let mut tool=WebSearchTool::default();let loaded=ConfigLoadResult::Failure{reason:ConfigLoadFailureReason::MissingConfig,message:"missing".into(),source:None};let params=SearchParams{query:"query".into(),allowed_domains:Some(vec!["a.example".into()]),blocked_domains:Some(vec!["b.example".into()])};
    let result=tool.execute(&reqwest::Client::new(),loaded,params,None,None,None).await.expect("execute");let SearchRenderDetails::Error(details)=result.details else{panic!("expected typed error")};assert!(details.reason.is_none());assert_eq!(details.query,"query");
}
#[tokio::test]
async fn configuration_failure_preserves_reason_without_progress(){
    let mut tool=WebSearchTool::default();let loaded=ConfigLoadResult::Failure{reason:ConfigLoadFailureReason::ProviderNativeBypass,message:"native bypass".into(),source:None};let params=SearchParams{query:"query".into(),allowed_domains:None,blocked_domains:None};let mut updates=0;let mut update=|_:SearchToolResult|updates+=1;
    let result=tool.execute(&reqwest::Client::new(),loaded,params,None,None,Some(&mut update)).await.expect("execute");let SearchRenderDetails::Error(details)=result.details else{panic!("expected typed error")};assert!(matches!(details.reason,Some(ConfigLoadFailureReason::ProviderNativeBypass)));assert_eq!(updates,0);
}
#[tokio::test]
async fn tool_round_robin_state_persists_and_progress_is_typed(){
    use tokio::{io::{AsyncReadExt,AsyncWriteExt},net::TcpListener};
    let listener=TcpListener::bind("127.0.0.1:0").await.expect("bind");let address=listener.local_addr().expect("address");let server=tokio::spawn(async move{let mut paths=Vec::new();for _ in 0..2{let (mut stream,_)=listener.accept().await.expect("accept");let mut bytes=Vec::new();loop{let mut buffer=[0;1024];let count=stream.read(&mut buffer).await.expect("read");assert_ne!(count,0);bytes.extend_from_slice(&buffer[..count]);if bytes.windows(4).any(|window|window==b"\r\n\r\n"){break;}}let request=String::from_utf8_lossy(&bytes);paths.push(request.lines().next().expect("request line").split_whitespace().nth(1).expect("path").to_owned());let body=r#"{"results":[{"title":"Manual","url":"https://manual.example.com"}]}"#;let response=format!("HTTP/1.1 200 OK\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",body.len());stream.write_all(response.as_bytes()).await.expect("write");}paths});
    let config=WebsearchConfig{strategy:RoutingStrategy::RoundRobin,fallback:true,auto:false,providers:["one","two"].into_iter().map(|id|serde_json::from_value(serde_json::json!({"provider":"exa","id":id,"baseUrl":format!("http://{address}/{id}"),"maxResults":4})).expect("provider")).collect()};let mut tool=WebSearchTool::default();let mut updates=Vec::new();let client=reqwest::Client::new();
    for expected in ["one","two"]{let mut update=|result:SearchToolResult|updates.push(result.details);let loaded=ConfigLoadResult::Success{config:config.clone(),source:"fixture".into()};let params=SearchParams{query:"route progress".into(),allowed_domains:None,blocked_domains:None};let result=tokio::time::timeout(std::time::Duration::from_secs(5),tool.execute(&client,loaded,params,None,None,Some(&mut update))).await.expect("timeout").expect("execute");let SearchRenderDetails::Result(details)=result.details else{panic!("result details")};assert_eq!(details.entry_id.as_deref(),Some(expected));}
    assert_eq!(server.await.expect("server"),vec!["/one","/two"]);assert_eq!(updates.len(),4);let SearchRenderDetails::Progress(progress)=&updates[0]else{panic!("initial progress")};assert_eq!(progress.max_results,4.0);assert_eq!(progress.provider_labels,vec!["exa/one","exa/two"]);let SearchRenderDetails::Progress(progress)=&updates[3]else{panic!("route progress")};assert_eq!(progress.current_provider.as_deref(),Some("exa/two"));assert_eq!(progress.route_labels,Some(vec!["exa/two".into(),"exa/one".into()]));
}
