[package]
name = "maho-ext-builtin-loose"
version.workspace = true
edition.workspace = true
publish.workspace = true
license = "MIT"

[dependencies]
serde_json.workspace = true
maho-ext-api = { path = "../../maho-ext-api" }
maho-agent = { path = "../../maho-agent" }
maho-ai = { path = "../../maho-ai" }

[lints]
workspace = true
