use maho_ext_pi_webfetch::webfetch::content::decode_html_entities;
#[test]fn explicit_article_selector_priority_and_noise_removal(){use maho_ext_pi_webfetch::webfetch::content::extract_explicit_article;let article=extract_explicit_article("<title>Fallback</title><h1>Preferred</h1><div class='entry-content'>Second article content long enough to qualify.</div><div class='article_view'><p>First article content long enough to qualify.</p><aside>noise</aside></div>").expect("article");assert_eq!(article.title,"Preferred");assert!(!article.has_heading);assert_eq!(article.content,"<p>First article content long enough to qualify.</p>");}
#[test]fn explicit_article_threshold_counts_utf16(){use maho_ext_pi_webfetch::webfetch::content::extract_explicit_article;let html=format!("<div class='entry-content'>{}</div>","\u{1f600}".repeat(15));assert!(extract_explicit_article(&html).is_some());assert!(extract_explicit_article("<div class='entry-content'>short</div>").is_none());}
#[test]fn html_fragment_dom_removes_noise_and_separates_blocks(){use maho_ext_pi_webfetch::webfetch::content::html_fragment_to_plain_text;assert_eq!(html_fragment_to_plain_text("<script>noise</script><p>a&nbsp;b<br>c</p><div>d</div><table><tr><td>e</td><td>f</td></tr></table>"),"a b\nc\n\nd\n\ne\nf");}
#[test]fn html_fragment_dom_decodes_full_named_entities(){use maho_ext_pi_webfetch::webfetch::content::html_fragment_to_plain_text;assert_eq!(html_fragment_to_plain_text("<p>&copy; &eacute; &amp;lt;</p>"),"\u{a9} \u{e9} &lt;");}
#[test]fn named_entities_decode_without_double_decoding(){assert_eq!(decode_html_entities("&amp;lt; &AMP; &unknown;"),"&lt; & &unknown;");}
#[test]fn numeric_entities_decode_unicode(){assert_eq!(decode_html_entities("&#128512; &#x1f600;"),"😀 😀");}
#[test]fn malformed_entities_remain_literal(){assert_eq!(decode_html_entities("&bad&copy; &#X41; &unterminated"),"&bad&copy; &#X41; &unterminated");}
#[test]fn out_of_range_codepoint_is_empty(){assert_eq!(decode_html_entities("before&#1114112;after"),"beforeafter");}
#[test]fn plain_text_collapses_horizontal_whitespace_and_preserves_cr(){use maho_ext_pi_webfetch::webfetch::content::normalize_plain_text;assert_eq!(normalize_plain_text("\u{feff} a\t\u{000b}\u{00a0}b  \n  c\n\n\n\n d\r\ne "),"a b\nc\n\nd\r\ne");}
#[test]fn markdown_normalizes_cr_without_collapsing_inline_spacing(){use maho_ext_pi_webfetch::webfetch::content::normalize_markdown;assert_eq!(normalize_markdown("  # Title\r\n\r\n\r\n  a  b \t\r c\t "),"# Title\n\na  b\nc");}
