//! Port of senpi packages/coding-agent/src/core/generated-shim-banner.ts.

use std::sync::OnceLock;

use crate::config::app_name;

/// Banner written at the top of the generated global-default extension shim. A rebranded install
/// writes its own product name; every historical spelling stays recognised so existing shims keep
/// loading instead of looking user-authored.
pub fn generated_shim_banner() -> String {
    format!(
        "// Generated by {}. Delete this file to stop loading the default global extension.\n",
        app_name()
    )
}

pub const HISTORICAL_SHIM_BANNERS: [&str; 2] = [
    "// Generated by senpi. Delete this file to stop loading the default global extension.\n",
    "// Generated by pi-coding-agent. Delete this file to stop loading the default global extension.\n",
];

/// Every banner spelling that identifies a generated shim, current brand first.
pub fn accepted_shim_banners() -> Vec<String> {
    let mut banners = vec![generated_shim_banner()];
    for banner in HISTORICAL_SHIM_BANNERS {
        let owned = banner.to_owned();
        if !banners.contains(&owned) {
            banners.push(owned);
        }
    }
    banners
}

fn accepted_shim_banner_prefixes() -> &'static Vec<String> {
    static PREFIXES: OnceLock<Vec<String>> = OnceLock::new();
    PREFIXES.get_or_init(|| {
        let mut prefixes: Vec<String> = Vec::new();
        for banner in accepted_shim_banners() {
            let head = banner.split('.').next().unwrap_or(&banner);
            let prefix = format!("{head}.");
            if !prefixes.contains(&prefix) {
                prefixes.push(prefix);
            }
        }
        prefixes
    })
}

/// Whether the given file content was generated by this product or a previous brand of it.
pub fn has_generated_shim_banner(content: &str) -> bool {
    accepted_shim_banner_prefixes().iter().any(|prefix| content.starts_with(prefix))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_current_banner_names_the_product() {
        assert!(generated_shim_banner().starts_with("// Generated by maho."));
    }

    #[test]
    fn historical_banners_are_accepted() {
        assert!(has_generated_shim_banner(&generated_shim_banner()));
        for banner in HISTORICAL_SHIM_BANNERS {
            assert!(has_generated_shim_banner(banner));
        }
    }

    #[test]
    fn a_user_authored_file_is_not_a_shim() {
        assert!(!has_generated_shim_banner("// my own extension\n"));
        assert!(!has_generated_shim_banner(""));
    }

    #[test]
    fn prefixes_carry_the_generated_marker() {
        assert!(accepted_shim_banner_prefixes().iter().all(|prefix| prefix.ends_with('.')));
    }
}
