[package]
name = "maho-omo-task"
version.workspace = true
edition.workspace = true
publish.workspace = true
license = "LicenseRef-SUL-1.0"

[dependencies]
senpi-task = { package = "maho-senpi-task", path = "../../senpi-task" }
maho-ext-api = { path = "../../../maho-ext-api" }
maho-tui = { path = "../../../maho-tui" }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.149"
chrono = "=0.4.43"
team-core = { package = "maho-team-core", path = "../../team-core" }
regex = "=1.12.3"
utils = { package = "maho-utils", path = "../../utils" }

[dev-dependencies]
tempfile = "=3.27.0"
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
