use maho_ext_compaction::checkpoint_state::*;
use serde_json::json;
#[test] fn capture_serializes_identity_model_tools_and_timestamp() {let c=capture_agent_checkpoint(Some("momus"),Some(&json!({"provider":"anthropic","modelId":"claude"})),&["read".into(),"edit".into()],None,1000.);let p=serialize_checkpoint(&c);assert_eq!(p["agentName"],"momus");assert_eq!(p["data"],c);assert_eq!(p["timestamp"],1000.);}
#[test] fn restoration_without_fallback_returns_directive() {assert_eq!(inject_restoration_directive(None,Some(&json!({})),None),RESTORATION_DIRECTIVE);}
#[test] fn latest_roundtrip_preserves_checkpoint() {let c=capture_agent_checkpoint(Some("momus"),Some(&json!({"provider":"anthropic","modelId":"claude"})),&["read".into()],None,1000.);let entries=[json!({"type":"custom","customType":CHECKPOINT_CUSTOM_TYPE,"data":serialize_checkpoint(&c)})];assert_eq!(get_latest_checkpoint(&entries),Some(c));}
#[test] fn degraded_checkpoint_can_use_fallback_model() {let d=inject_restoration_directive(None,Some(&json!({})),Some(&json!({"modelId":"claude"})));assert!(d.contains("claude"));}
#[test] fn legacy_latest_selects_highest_timestamp() {let checkpoints=[json!({"timestamp":1000}),json!({"timestamp":3000}),json!({"timestamp":2000})];assert_eq!(latest_legacy_checkpoint(&checkpoints,&[]),Some(checkpoints[1].clone()));}
#[test] fn directive_is_delivered_once_per_checkpoint() {let mut state=RestorationDirectiveState::default();let c=json!({"timestamp":1000,"agentName":"momus"});assert!(attach_restoration_directive(&mut state,Some(&c),None).is_some());assert!(attach_restoration_directive(&mut state,Some(&c),None).is_none());let c=json!({"timestamp":2000});assert!(attach_restoration_directive(&mut state,Some(&c),None).is_some());}
#[test] fn non_string_payload_is_preserved() {let mut state=RestorationDirectiveState::default();let message=json!({"content":[{"type":"text","text":"restore"}]});assert_eq!(attach_restoration_directive(&mut state,Some(&json!({"timestamp":1000})),Some(message.clone())),Some(message));}
