use maho_ext_compaction::retained_message_safety::has_unsafe_retained_content;
use serde_json::{Value,json};
fn assistant()->Value {json!({"role":"assistant","content":[{"type":"text","text":"ok"}],"api":"faux-completion","provider":"faux","model":"m","usage":{"input":0,"output":0,"cacheRead":0,"cacheWrite":0,"totalTokens":0,"cost":{"input":0,"output":0,"cacheRead":0,"cacheWrite":0,"total":0}},"stopReason":"stop","timestamp":1})}
#[test] fn text_user_is_safe_but_user_image_is_not() {assert!(!has_unsafe_retained_content(&[json!({"role":"user","content":"hello","timestamp":1})]));assert!(has_unsafe_retained_content(&[json!({"role":"user","content":[{"type":"image","mimeType":"image/png","data":"image"}],"timestamp":1})]));}
#[test] fn assistant_requires_complete_envelope() {assert!(!has_unsafe_retained_content(&[assistant()]));for key in ["api","provider","model","usage","stopReason","timestamp","content"] {let mut v=assistant();v.as_object_mut().expect("object").remove(key);assert!(has_unsafe_retained_content(&[v]),"{key}");}}
#[test] fn google_signatures_require_bounded_base64() {for (sig,unsafe_value) in [("YWJj",false),("bad!",true),("",true),("abc",true)] {let mut v=assistant();v["provider"]=json!("google");v["content"][0]["textSignature"]=json!(sig);assert_eq!(has_unsafe_retained_content(&[v]),unsafe_value);}}
#[test] fn redacted_thinking_requires_signature() {let mut v=assistant();v["content"]=json!([{"type":"thinking","thinking":"","redacted":true}]);assert!(has_unsafe_retained_content(&[v.clone()]));v["content"][0]["thinkingSignature"]=json!("opaque");assert!(!has_unsafe_retained_content(&[v]));}
#[test] fn incomplete_false_is_rejected_and_true_is_allowed() {let mut v=assistant();v["content"]=json!([{"type":"toolCall","id":"call","name":"read","arguments":{},"incomplete":false}]);assert!(has_unsafe_retained_content(&[v.clone()]));v["content"][0]["incomplete"]=json!(true);assert!(!has_unsafe_retained_content(&[v]));}
#[test] fn tool_images_require_mime_and_data() {let mut v=json!({"role":"toolResult","toolCallId":"call","toolName":"read","content":[{"type":"image","mimeType":"image/png","data":"opaque"}],"isError":false,"timestamp":1});assert!(!has_unsafe_retained_content(&[v.clone()]));v["content"][0]["data"]=json!("");assert!(has_unsafe_retained_content(&[v]));}
#[test] fn supported_custom_bash_and_summary_envelopes_are_safe() {assert!(!has_unsafe_retained_content(&[json!({"role":"custom","customType":"restore","display":false,"timestamp":1,"content":"restore"}),json!({"role":"bashExecution","command":"ls","output":"file","cancelled":false,"truncated":false,"timestamp":1}),json!({"role":"compactionSummary","summary":"summary","tokensBefore":100,"timestamp":1})]));}
#[test] fn unknown_role_and_provider_native_content_are_unsafe() {assert!(has_unsafe_retained_content(&[json!({"role":"unknown"})]));let mut v=assistant();v["content"]=json!([{"type":"providerNative","raw":{}}]);assert!(has_unsafe_retained_content(&[v]));}
