use crate::detectors::LoopGuardDetection;
pub const LOOP_GUARD_NOTICE_CUSTOM_TYPE: &str = "loop-guard:notice";
pub const LOOP_GUARD_ESCALATION_CUSTOM_TYPE: &str = "loop-guard:escalation";
pub const LOOP_GUARD_RECOVERY_CUSTOM_TYPE: &str = "loop-guard:recovery";
pub type LoopGuardNoticeDetails = LoopGuardDetection;
pub struct LoopGuardEscalationDetails { pub tool_name: String, pub blocked_call_count: usize }
pub fn build_loop_guard_block_reason(tool_name: &str, blocked_call_count: usize) -> String {
    let recovery = if matches!(tool_name, "bash_output" | "task_output") { "Stop polling this target. If you need to wait for a change, arm a monitor or rely on a completion notification when this mode supports it; otherwise re-plan or choose a different tool." } else { "Reuse the existing result, stop repeating this call, and re-plan from the current goal or choose a different tool." };
    format!("Loop guard blocked repeated call {blocked_call_count} to `{tool_name}` with arguments that already triggered two identical-call warnings. {recovery}")
}
pub fn build_loop_guard_hard_stop_warning(tool_name: &str, blocked_call_count: usize) -> String { format!("Loop guard interrupted the turn after blocking {blocked_call_count} repeated calls to {tool_name}.") }
pub fn build_loop_guard_hard_stop_steer(tool_name: &str) -> String { format!("The loop guard stopped the previous turn because you kept calling `{tool_name}` with arguments that had already been blocked. Do not repeat that call. Re-plan from the current goal and use a different tool or deliberately changed arguments.") }
pub fn build_loop_guard_reminder(detection: &LoopGuardDetection) -> String {
    match detection {
        LoopGuardDetection::Identical { tool_name, count, .. } => format!("<system-reminder>\nLOOP GUARD - IDENTICAL TOOL CALLS: you called `{tool_name}` {count} times in a row with the EXACT same arguments. This is the tool-call stream, not consecutive text - another tool ran between these calls and it changed nothing about your plan. Re-issuing the same call returns the same result. Snap out of it:\n- reuse the result you already received from this exact call;\n- if you were re-checking for new output or state, switch to the monitor/watch tool or change one parameter deliberately (filter, offset, query);\n- if nothing is actually changing, stop calling this tool, state what is blocking you, and try a different tool or ask the user.\nDo not call `{tool_name}` again with identical arguments.\n</system-reminder>"),
        LoopGuardDetection::Similar { tool_name, count, similarity, .. } => { let percent = (similarity * 100.0).round(); format!("<system-reminder>\nLOOP GUARD - NEAR-IDENTICAL TOOL CALLS: your last {count} calls to `{tool_name}` had arguments about {percent}% identical (bigram similarity over canonical args). This may be legitimate batch work - or it may be a lazy loop that only LOOKS like progress. Attention check:\n- if these calls target genuinely different inputs (distinct files, queries, offsets), continue deliberately - but consider batching or widening the scope instead of one call per tiny variation;\n- if you are scanning output incrementally (reads, peeks, polls), widen the window once or use the monitor/watch tool rather than nudging parameters;\n- if the results keep saying the same thing, change strategy now - a different tool, a wider query, or asking the user beats a sixth near-copy.\n</system-reminder>") },
        LoopGuardDetection::Cycle { period, count, cycle_tools, .. } => { let pattern = cycle_tools.join(" -> "); format!("<system-reminder>\nLOOP GUARD - REPEATING TOOL-CALL PATTERN: your recent tool calls repeat the cycle [{pattern}] {count} times (period {period}), with other calls possibly interleaved between repetitions. A fixed rotation usually means waiting, guessing, or searching without a discriminator:\n- if this is a wait/poll rotation (spawn then peek, write then check), replace the rotation with the monitor/watch tool and react to the decisive event instead;\n- if this is a search rotation, change ONE axis decisively: broader query, different tool, or a different source - repeating the same rotation at the same parameters will not find new information;\n- if the cycle is genuinely progressing (each rotation moves distinct work forward), keep going - but say what each rotation accomplished so the next rotation can end.\n</system-reminder>") },
    }
}
