//! todo 33 selector and dialog coverage, driven by the pinned-senpi golden
//! tests/golden/task33-selectors.json (generated by tools/golden/interactive-33.mjs).

use std::rc::Rc;
use std::sync::Arc;

use maho_core::session_manager::SessionTreeNode;
use maho_interactive::components::config_selector::{
    ConfigWriteScope, build_groups, ConfigSelectorComponent, ResourceItem,
};
use maho_interactive::components::extension_input::{ExtensionInputComponent, ExtensionInputOptions};
use maho_interactive::components::extension_selector::{
    ExtensionSelectorComponent, ExtensionSelectorOptions,
};
use maho_interactive::components::favorite_models_selector::{
    FavoriteModelsCallbacks, FavoriteModelsConfig, FavoriteModelsSelectorComponent,
};
use maho_interactive::components::favorite_model_ids::{
    clear_favorite_models, favorite_models, get_sorted_favorite_model_ids, move_favorite_model,
    toggle_favorite_model,
};
use maho_interactive::components::keybinding_hints::{format_key_text, key_hint, raw_key_hint};
use maho_interactive::components::model_selector::{ModelEntry, ModelSelectorComponent, ModelSelectorFavoriteOptions};
use maho_interactive::components::oauth_selector::{
    AuthSelectorAuthType, AuthSelectorMode, AuthSelectorProvider, OAuthSelectorComponent,
    format_auth_selector_provider_type,
};
use maho_interactive::components::session_selector::{
    build_session_tree, build_tree_prefix, flatten_session_tree, format_session_date, SessionList,
    SessionScope, SessionSelectorComponent,
};
use maho_interactive::components::session_selector_search::{
    filter_and_sort_sessions, has_session_name, match_session, parse_search_query, NameFilter,
    SessionInfo, SortMode,
};
use maho_interactive::components::settings_selector::{
    format_http_idle_timeout_ms, SettingsConfig, SettingsSelectorComponent,
};
use maho_interactive::components::theme_selector::ThemeSelectorComponent;
use maho_interactive::components::tree_selector::{FilterMode, TreeSelectorComponent};
use maho_interactive::theme::{ColorMode, Theme};
use maho_interactive::theme::theme::ThemeColor;
use maho_tui::keybindings::KeybindingsManager;
use maho_tui::tui::Component;
use serde_json::Value;

fn golden() -> Value {
    serde_json::from_str(include_str!("golden/task33-selectors.json")).expect("golden parses")
}

/// The manager the selector components see in the app: TUI ids plus the app.* ids from maho-core.
fn full_keybindings() -> Arc<KeybindingsManager> {
    Arc::new(KeybindingsManager::new(
        maho_core::keybindings::keybindings().clone(),
        maho_tui::keybindings::KeybindingsConfig::default(),
    ))
}

fn theme() -> Theme {
    Theme::builtin("dark", ColorMode::Truecolor).expect("builtin dark theme")
}

fn models_from_golden(value: &Value) -> Vec<ModelEntry> {
    value["models"]
        .as_array()
        .expect("models array")
        .iter()
        .map(|model| ModelEntry {
            provider: model["provider"].as_str().unwrap_or_default().to_owned(),
            id: model["id"].as_str().unwrap_or_default().to_owned(),
            name: model["name"].as_str().unwrap_or_default().to_owned(),
        })
        .collect()
}

fn sessions_from_golden(value: &Value) -> Vec<SessionInfo> {
    value["sessions"]
        .as_array()
        .expect("sessions array")
        .iter()
        .map(|session| SessionInfo {
            path: session["path"].as_str().unwrap_or_default().to_owned(),
            id: session["id"].as_str().unwrap_or_default().to_owned(),
            cwd: session["cwd"].as_str().unwrap_or_default().to_owned(),
            name: session["name"].as_str().map(str::to_owned),
            parent_session_path: None,
            modified_ms: session["modifiedMs"].as_i64().unwrap_or_default(),
            message_count: session["messageCount"].as_u64().unwrap_or_default() as usize,
            first_message: session["firstMessage"].as_str().unwrap_or_default().to_owned(),
            all_messages_text: session["allMessagesText"].as_str().unwrap_or_default().to_owned(),
        })
        .collect()
}

fn expected_ids(entry: &Value) -> Vec<String> {
    entry
        .as_array()
        .expect("expected rows")
        .iter()
        .map(|id| id.as_str().unwrap_or_default().to_owned())
        .collect()
}

/// The model selector's filtered rows equal the pinned senpi ranking for every golden query.
#[test]
fn model_selector_rows_match_pinned_senpi_ranking() {
    let golden = golden();
    let models = models_from_golden(&golden);
    let favorites: Vec<String> = golden["favoriteIds"]
        .as_array()
        .expect("favoriteIds")
        .iter()
        .map(|id| id.as_str().unwrap_or_default().to_owned())
        .collect();
    let theme = theme();
    let keybindings = full_keybindings();

    for case in golden["modelSelector"].as_array().expect("modelSelector") {
        let query = case["query"].as_str().unwrap_or_default();
        if query.is_empty() {
            // An empty query shows the component's own sort (current, favorites, provider/id);
            // the ranking function's empty-query order is covered by task33_search.rs.
            continue;
        }
        let expected = expected_ids(&case["rows"]);
        let selector = ModelSelectorComponent::new(
            &theme,
            keybindings.clone(),
            1,
            &models,
            None,
            Vec::new(),
            Box::new(|_| {}),
            Box::new(|| {}),
            Some(query),
            ModelSelectorFavoriteOptions {
                favorite_model_ids: Some(favorites.clone()),
                on_favorite_change: None,
            },
            None,
        );
        assert_eq!(selector.filtered_model_ids(), expected, "query {query:?}");
        // A non-empty query highlights the first row, an empty one keeps the opening position.
        if !query.is_empty() {
            assert_eq!(selector.selected_index(), 0, "query {query:?}");
        }
    }
}

/// The model selector renders the search hint, the provider badge and the favorite marker.
#[test]
fn model_selector_renders_senpi_row_chrome() {
    let golden = golden();
    let models = models_from_golden(&golden);
    let theme = theme();
    let mut selector = ModelSelectorComponent::new(
        &theme,
        full_keybindings(),
        1,
        &models,
        Some(models[2].clone()),
        Vec::new(),
        Box::new(|_| {}),
        Box::new(|| {}),
        Some("gpt"),
        ModelSelectorFavoriteOptions {
            favorite_model_ids: Some(vec![models[3].full_id()]),
            on_favorite_change: None,
        },
        Some(40),
    );
    let rendered = selector.render(80).join("\n");
    assert!(rendered.contains("[openai]"), "{rendered}");
    assert!(rendered.contains("✓"), "{rendered}");
    assert!(rendered.contains("→ "), "{rendered}");
    assert!(rendered.contains("Only showing models from configured providers"), "{rendered}");
}

/// Every pinned session-search case keeps senpi's order for all three sort modes.
#[test]
fn session_search_matches_pinned_senpi() {
    let golden = golden();
    let sessions = sessions_from_golden(&golden);
    for case in golden["sessionSearch"].as_array().expect("sessionSearch") {
        let query = case["query"].as_str().unwrap_or_default();
        let parsed = parse_search_query(query);
        assert_eq!(
            parsed.error.is_some(),
            !case["parsedError"].is_null(),
            "error presence for {query:?}"
        );
        for (key, mode) in [("recent", SortMode::Recent), ("relevance", SortMode::Relevance)] {
            let ids: Vec<String> = filter_and_sort_sessions(&sessions, query, mode, NameFilter::All)
                .into_iter()
                .map(|session| session.id)
                .collect();
            assert_eq!(ids, expected_ids(&case[key]), "{key} for {query:?}");
        }
        let named: Vec<String> = filter_and_sort_sessions(&sessions, query, SortMode::Recent, NameFilter::Named)
            .into_iter()
            .map(|session| session.id)
            .collect();
        assert_eq!(named, expected_ids(&case["named"]), "named for {query:?}");
    }
}

/// A session counts as named only when the trimmed name is non-empty.
#[test]
fn session_name_detection_matches_senpi() {
    let golden = golden();
    let sessions = sessions_from_golden(&golden);
    for case in golden["helpers"]["hasSessionName"].as_array().expect("hasSessionName") {
        let id = case[0].as_str().unwrap_or_default();
        let expected = case[1].as_bool().unwrap_or_default();
        let mut session = sessions.iter().find(|session| session.id == id).cloned().expect("session");
        if case[0].as_str() == Some("s1") && !expected {
            session.name = Some("   ".to_owned());
        }
        assert_eq!(has_session_name(&session), expected, "{id}");
    }
}

/// Phrase tokens, regex mode and a broken regex behave like senpi's parser.
#[test]
fn session_search_parser_modes_match_senpi() {
    let sessions = sessions_from_golden(&golden());
    let phrase = parse_search_query("\"node cve\"");
    assert_eq!(phrase.tokens.len(), 1);
    assert!(match_session(&sessions[0], &phrase).matches);
    assert!(!match_session(&sessions[1], &phrase).matches);

    let regex = parse_search_query("re:beta");
    assert!(regex.regex.is_some());
    assert_eq!(
        filter_and_sort_sessions(&sessions, "re:beta", SortMode::Recent, NameFilter::All)
            .into_iter()
            .map(|session| session.id)
            .collect::<Vec<_>>(),
        vec!["s3".to_owned()]
    );

    let broken = parse_search_query("re:[");
    assert!(broken.error.is_some());
    assert!(filter_and_sort_sessions(&sessions, "re:[", SortMode::Recent, NameFilter::All).is_empty());
}

/// The favorite-model id helpers match the pinned senpi results.
#[test]
fn favorite_model_helpers_match_pinned_senpi() {
    let golden = golden();
    let expected = &golden["favorites"];
    let all_ids: Vec<String> = models_from_golden(&golden)
        .iter()
        .map(ModelEntry::full_id)
        .collect();
    let favorite_ids = vec!["openai/gpt-5.2".to_owned()];

    assert_eq!(
        toggle_favorite_model(&None, &all_ids, "openai/gpt-5.2"),
        Some(expected_ids(&expected["toggleFromAll"]))
    );
    assert_eq!(
        toggle_favorite_model(&Some(favorite_ids.clone()), &all_ids, "openai/gpt-5.2"),
        Some(expected_ids(&expected["toggleOff"]))
    );
    assert_eq!(
        toggle_favorite_model(&Some(Vec::new()), &all_ids, "zai/glm-5.2"),
        Some(expected_ids(&expected["toggleOn"]))
    );
    assert_eq!(favorite_models(&Some(Vec::new()), &all_ids, None), None);
    assert_eq!(
        clear_favorite_models(&Some(favorite_ids.clone()), &all_ids, Some(&["openai/gpt-5.2".to_owned()])),
        Some(expected_ids(&expected["clearFiltered"]))
    );
    assert_eq!(
        clear_favorite_models(&None, &all_ids, None),
        Some(expected_ids(&expected["clearAll"]))
    );
    assert_eq!(
        move_favorite_model(&Some(vec!["a".to_owned(), "b".to_owned(), "c".to_owned()]), "b", -1),
        Some(expected_ids(&expected["moveUp"]))
    );
    assert_eq!(
        get_sorted_favorite_model_ids(&Some(vec!["zai/glm-5.2".to_owned()]), &all_ids),
        expected_ids(&expected["sorted"])
    );
}

/// The favorite-models selector keeps the frozen display order and toggles membership.
#[test]
fn favorite_models_selector_keeps_frozen_row_order() {
    let golden = golden();
    let models = models_from_golden(&golden);
    let theme = theme();
    let selected = Rc::new(std::cell::RefCell::new(Vec::<String>::new()));
    let changed = Rc::clone(&selected);
    let persisted = Rc::clone(&selected);
    let mut component = FavoriteModelsSelectorComponent::new(
        &theme,
        full_keybindings(),
        FavoriteModelsConfig {
            all_models: models.clone(),
            favorite_model_ids: Some(vec!["openai/gpt-5.2".to_owned()]),
            current_model: Some(models[2].clone()),
        },
        FavoriteModelsCallbacks {
            on_change: Box::new(move |ids| *changed.borrow_mut() = ids.unwrap_or_default()),
            on_persist: Box::new(move |ids| *persisted.borrow_mut() = ids.unwrap_or_default()),
            on_select: Box::new(|_| {}),
            on_cancel: Box::new(|| {}),
        },
    );
    let initial = component.filtered_ids();
    assert_eq!(initial.first().map(String::as_str), Some("openai/gpt-5.2"));
    assert!(!component.is_dirty());

    // Ctrl+F toggles the selected row's membership and marks the surface dirty.
    component.handle_input("\u{6}");
    assert!(component.is_dirty());
    assert_eq!(component.favorite_ids(), &Some(Vec::new()));
    assert_eq!(component.filtered_ids(), initial, "row order stays frozen");

    component.handle_input("\u{13}");
    assert_eq!(*selected.borrow(), Vec::<String>::new());
}

/// A three-branch session renders senpi's tree glyphs and keeps the active path marked.
#[test]
fn tree_selector_renders_senpi_branch_glyphs() {
    let theme = theme();
    let tree = three_branch_tree();
    let mut selector = TreeSelectorComponent::new(
        &theme,
        full_keybindings(),
        tree,
        Some("leaf-b"),
        24,
        Box::new(|_| {}),
        Box::new(|| {}),
        None,
        None,
        None,
        None,
    );
    let rendered = selector.render(80).join("\n");
    assert!(rendered.contains("Session Tree"), "{rendered}");
    assert!(rendered.contains("├─ ") || rendered.contains("└─ "), "{rendered}");
    assert!(rendered.contains("│"), "{rendered}");
    assert!(rendered.contains("• "), "{rendered}");
    assert!(rendered.contains("assistant: "), "{rendered}");
    assert!(rendered.contains("user: "), "{rendered}");

    let tree_list = selector.tree_list();
    let ids = tree_list.borrow().filtered_entry_ids();
    assert!(ids.contains(&"leaf-b".to_owned()));
    assert_eq!(tree_list.borrow().filter_mode(), FilterMode::Default);
}

/// The tree list's filter modes change which entries are visible.
#[test]
fn tree_selector_filter_modes_narrow_entries() {
    let theme = theme();
    let selector = TreeSelectorComponent::new(
        &theme,
        full_keybindings(),
        three_branch_tree(),
        Some("leaf-b"),
        24,
        Box::new(|_| {}),
        Box::new(|| {}),
        None,
        None,
        None,
        None,
    );
    let all = selector.tree_list().borrow().filtered_entry_ids();
    assert_eq!(all.len(), 5);

    // app.tree.filter.userOnly is ctrl+u in the default keybindings.
    selector.tree_list().borrow_mut().handle_input("\u{15}");
    let user_only = selector.tree_list().borrow().filtered_entry_ids();
    assert_eq!(user_only, vec!["root".to_owned(), "branch-c".to_owned()]);
    assert_eq!(selector.tree_list().borrow().filter_mode(), FilterMode::UserOnly);

    // ctrl+d returns to the default view.
    selector.tree_list().borrow_mut().handle_input("\u{4}");
    assert_eq!(selector.tree_list().borrow().filtered_entry_ids(), all);
}

/// The session selector builds senpi's parent/child tree and flattens it with tree metadata.
#[test]
fn session_selector_builds_and_flattens_the_session_tree() {
    let sessions = vec![
        session("root", "/s/root.jsonl", None, 3_000),
        session("child", "/s/child.jsonl", Some("/s/root.jsonl"), 2_000),
        session("grandchild", "/s/grandchild.jsonl", Some("/s/child.jsonl"), 1_000),
        session("sibling", "/s/sibling.jsonl", Some("/s/root.jsonl"), 500),
    ];
    let roots = build_session_tree(&sessions);
    assert_eq!(roots.len(), 1);
    assert_eq!(roots[0].session.id, "root");
    assert_eq!(roots[0].children.len(), 2);
    // Sorted by latest subtree activity: child (grandchild at 1000) before sibling (500).
    assert_eq!(roots[0].children[0].session.id, "child");
    assert_eq!(roots[0].children[1].session.id, "sibling");
    assert_eq!(roots[0].latest_activity, 3_000);

    let flat = flatten_session_tree(&roots);
    let shapes: Vec<(String, usize, String)> = flat
        .iter()
        .map(|node| (node.session.id.clone(), node.depth, build_tree_prefix(node)))
        .collect();
    assert_eq!(
        shapes,
        vec![
            ("root".to_owned(), 0, String::new()),
            ("child".to_owned(), 1, "   ├─ ".to_owned()),
            ("grandchild".to_owned(), 2, "   │  └─ ".to_owned()),
            ("sibling".to_owned(), 1, "   └─ ".to_owned()),
        ]
    );
}

/// The session list renders the tree prefix, the age column and the scope empty-state.
#[test]
fn session_list_renders_tree_rows_and_empty_state() {
    let theme = theme();
    let sessions = vec![
        session("root", "/s/root.jsonl", None, 3_000),
        session("child", "/s/child.jsonl", Some("/s/root.jsonl"), 2_000),
    ];
    let mut list = SessionList::new(
        &theme,
        sessions,
        false,
        SortMode::Threaded,
        NameFilter::All,
        full_keybindings(),
        Some("/s/root.jsonl"),
        None,
    );
    let rendered = list.render(100).join("\n");
    assert!(rendered.contains("├─ ") || rendered.contains("└─ "), "{rendered}");
    assert!(rendered.contains("› "), "{rendered}");

    let mut empty = SessionList::new(
        &theme,
        Vec::new(),
        false,
        SortMode::Threaded,
        NameFilter::All,
        full_keybindings(),
        None,
        None,
    );
    assert!(empty.render(100).join("\n").contains("No sessions in current folder"));
}

/// The session selector header shows the scope, sort and name-filter state.
#[test]
fn session_selector_header_and_scope_toggle() {
    let theme = theme();
    let loaded = Rc::new(std::cell::Cell::new(0));
    let loader_counter = Rc::clone(&loaded);
    let all_sessions = vec![session("a", "/s/a.jsonl", None, 1_000)];
    let mut component = SessionSelectorComponent::new(
        &theme,
        full_keybindings(),
        Box::new(move |_| {
            loader_counter.set(loader_counter.get() + 1);
            vec![session("a", "/s/a.jsonl", None, 1_000)]
        }),
        Box::new(move |_| all_sessions.clone()),
        Box::new(|_| {}),
        Box::new(|| {}),
        Box::new(|| {}),
        Box::new(|| {}),
        None,
        None,
        Some("/s/a.jsonl"),
        None,
    );
    assert_eq!(loaded.get(), 1, "the current-folder loader ran once on construction");
    assert_eq!(component.scope(), SessionScope::Current);
    let current = component.render(120).join("\n");
    assert!(current.contains("Resume Session (Current Folder)"), "{current}");
    assert!(current.contains("◉ Current Folder"), "{current}");

    component.toggle_scope();
    assert_eq!(component.scope(), SessionScope::All);
    let all = component.render(120).join("\n");
    assert!(all.contains("Resume Session (All)"), "{all}");
    assert!(all.contains("◉ All"), "{all}");

    component.toggle_sort_mode();
    assert_eq!(component.sort_mode(), SortMode::Recent);
    assert!(component.render(120).join("\n").contains("Sort: "));
    component.toggle_name_filter();
    let named = component.render(120).join("\n");
    assert!(named.contains("Name: "), "{named}");
    assert!(named.contains("Named"), "{named}");
}

/// The session selector's rename mode swaps the list for a labelled input.
#[test]
fn session_selector_rename_mode_round_trip() {
    let theme = theme();
    let renamed = Rc::new(std::cell::RefCell::new(Vec::<(String, String)>::new()));
    let sink = Rc::clone(&renamed);
    let mut component = SessionSelectorComponent::new(
        &theme,
        full_keybindings(),
        Box::new(|_| Vec::new()),
        Box::new(|_| Vec::new()),
        Box::new(|_| {}),
        Box::new(|| {}),
        Box::new(|| {}),
        Box::new(|| {}),
        Some(Box::new(move |path, name| {
            sink.borrow_mut().push((path.to_owned(), name.unwrap_or_default().to_owned()));
        })),
        None,
        None,
        None,
    );
    assert!(component.can_rename());
    component.enter_rename_mode("/s/a.jsonl", Some("old"));
    assert!(component.render(80).join("\n").contains("Rename Session"));
    component.rename_input_mut().set_value("new name");
    let value = component.rename_input().get_value().to_owned();
    component.confirm_rename(&value);
    assert_eq!(*renamed.borrow(), vec![("/s/a.jsonl".to_owned(), "new name".to_owned())]);
    assert!(component.render(80).join("\n").contains("Resume Session"));
}

/// The settings selector lists every setting id senpi ships, in senpi's order.
#[test]
fn settings_selector_lists_senpi_settings_in_order() {
    let theme = theme();
    let config = SettingsConfig {
        available_themes: vec!["dark".to_owned(), "light".to_owned()],
        ..SettingsConfig::default()
    };
    let mut selector = SettingsSelectorComponent::new(&theme, config, Default::default(), false);

    // The window is ten rows and follows the selection; select the first id senpi ships.
    selector.settings_list_mut().select_item("autocompact");
    let head = selector.render(200).join("\n");
    assert!(head.contains("Auto-compact"), "{head}");
    assert!(head.contains("Block images"), "{head}");

    // The last id senpi ships is the theme submenu.
    selector.settings_list_mut().select_item("theme");
    let tail = selector.render(200).join("\n");
    assert!(tail.contains("Theme"), "{tail}");
}

/// The settings selector reports changes for the settings it can change without a submenu.
#[test]
fn settings_selector_dispatches_scalar_changes() {
    let theme = theme();
    let seen = Rc::new(std::cell::RefCell::new(Vec::<String>::new()));
    let sink = Rc::clone(&seen);
    let callbacks = maho_interactive::components::settings_selector::SettingsCallbacks {
        on_auto_compact_change: Some(Box::new({
            let sink = Rc::clone(&sink);
            move |value| sink.borrow_mut().push(format!("autocompact={value}"))
        })),
        on_tui_mode_change: Some(Box::new({
            let sink = Rc::clone(&sink);
            move |mode| sink.borrow_mut().push(format!("tui={}", mode.as_str()))
        })),
        ..Default::default()
    };
    let mut selector = SettingsSelectorComponent::new(&theme, SettingsConfig::default(), callbacks, true);
    let rendered = selector.render(200).join("\n");
    assert!(rendered.contains("Show images"), "{rendered}");
    assert!(rendered.contains("Image width"), "{rendered}");
    assert!(seen.borrow().is_empty(), "no change before a key is sent");

    // Enter on the first row (Auto-compact) cycles the value and reports it.
    selector.handle_input("\r");
    assert_eq!(seen.borrow().len(), 1, "{:?}", seen.borrow());
    assert!(seen.borrow()[0].starts_with("autocompact="), "{:?}", seen.borrow());
}

/// The config selector groups resources by origin/scope and toggles a top-level resource.
#[test]
fn config_selector_groups_resources_and_toggles_them() {
    use maho_core::package_manager::{PathMetadata, ResolvedPaths, ResolvedResource};
    use maho_core::source_info::{SourceOrigin, SourceScope};

    let resolved = ResolvedPaths {
        skills: vec![
            ResolvedResource {
                path: "/home/u/.maho/agent/skills/alpha/SKILL.md".to_owned(),
                enabled: true,
                metadata: PathMetadata {
                    source: "auto".to_owned(),
                    scope: SourceScope::User,
                    origin: SourceOrigin::TopLevel,
                    base_dir: Some("/home/u/.maho/agent/skills".to_owned()),
                },
            },
            ResolvedResource {
                path: "/home/u/.maho/agent/skills/beta/SKILL.md".to_owned(),
                enabled: false,
                metadata: PathMetadata {
                    source: "auto".to_owned(),
                    scope: SourceScope::User,
                    origin: SourceOrigin::TopLevel,
                    base_dir: Some("/home/u/.maho/agent/skills".to_owned()),
                },
            },
        ],
        ..ResolvedPaths::default()
    };
    let groups = build_groups(&resolved, "/home/u/.maho/agent", "/home/u", ".maho");
    assert_eq!(groups.len(), 1);
    assert_eq!(groups[0].label, "User (~/.maho/agent/skills/)");
    assert_eq!(groups[0].subgroups.len(), 1);
    let names: Vec<&str> = groups[0].subgroups[0]
        .items
        .iter()
        .map(|item| item.display_name.as_str())
        .collect();
    assert_eq!(names, vec!["alpha", "beta"]);

    let theme = theme();
    let mut scopes = std::collections::BTreeMap::new();
    scopes.insert(ConfigWriteScope::Global, resolved);
    scopes.insert(ConfigWriteScope::Project, ResolvedPaths::default());
    let settings = RecordingSettings::default();
    let mut selector = ConfigSelectorComponent::new(
        &theme,
        scopes,
        Box::new(settings),
        "/home/u/project",
        "/home/u/.maho/agent",
        ".maho",
        Box::new(|| {}),
        Box::new(|| {}),
        Box::new(|| {}),
        Some(30),
        ConfigWriteScope::Global,
        true,
    );
    let rendered = selector.render(120).join("\n");
    assert!(rendered.contains("Global Resources"), "{rendered}");
    assert!(rendered.contains("Skills"), "{rendered}");
    assert!(rendered.contains("alpha"), "{rendered}");
    assert!(rendered.contains("[x]"), "{rendered}");
    assert!(rendered.contains("[ ]"), "{rendered}");

    // Space toggles the first item and records the disable pattern.
    selector.handle_input(" ");
    let list = selector.resource_list();
    let first: ResourceItem = list
        .filtered_items()
        .iter()
        .find_map(|entry| match entry {
            maho_interactive::components::config_selector::FlatEntry::Item(item) => Some(item.clone()),
            _ => None,
        })
        .expect("at least one resource item");
    assert_eq!(first.display_name, "alpha");
    // Selection starts on the first item, not the group header.
    assert!(matches!(
        list.filtered_items()[list.selected_index()],
        maho_interactive::components::config_selector::FlatEntry::Item(_)
    ));

    selector.switch_write_scope();
    let project = selector.render(120).join("\n");
    assert!(project.contains("Project Local Resources"), "{project}");
}

/// A recording ConfigSettingsHost that keeps the arrays the selector writes.
#[derive(Default)]
struct RecordingSettings {
    state: std::cell::RefCell<std::collections::BTreeMap<String, Vec<String>>>,
}

impl maho_interactive::components::config_selector::ConfigSettingsHost for RecordingSettings {
    fn get_global_settings(&self) -> Value {
        let state = self.state.borrow();
        let mut map = serde_json::Map::new();
        for (key, values) in state.iter() {
            map.insert(
                key.clone(),
                Value::Array(values.iter().cloned().map(Value::String).collect()),
            );
        }
        Value::Object(map)
    }

    fn get_project_settings(&self) -> Value {
        self.get_global_settings()
    }

    fn set_packages(&mut self, _packages: &[Value]) {}
    fn set_project_packages(&mut self, _packages: &[Value]) {}

    fn set_extension_paths(&mut self, paths: &[String]) {
        self.state.borrow_mut().insert("extensions".to_owned(), paths.to_vec());
    }
    fn set_project_extension_paths(&mut self, paths: &[String]) {
        self.set_extension_paths(paths);
    }
    fn set_skill_paths(&mut self, paths: &[String]) {
        self.state.borrow_mut().insert("skills".to_owned(), paths.to_vec());
    }
    fn set_project_skill_paths(&mut self, paths: &[String]) {
        self.set_skill_paths(paths);
    }
    fn set_prompt_template_paths(&mut self, paths: &[String]) {
        self.state.borrow_mut().insert("prompts".to_owned(), paths.to_vec());
    }
    fn set_project_prompt_template_paths(&mut self, paths: &[String]) {
        self.set_prompt_template_paths(paths);
    }
    fn set_theme_paths(&mut self, paths: &[String]) {
        self.state.borrow_mut().insert("themes".to_owned(), paths.to_vec());
    }
    fn set_project_theme_paths(&mut self, paths: &[String]) {
        self.set_theme_paths(paths);
    }
}

/// The theme selector preselects the current theme and renders both borders.
#[test]
fn theme_selector_preselects_current_theme() {
    let theme = theme();
    let selected = Rc::new(std::cell::RefCell::new(String::new()));
    let previewed = Rc::new(std::cell::RefCell::new(String::new()));
    let sink = Rc::clone(&selected);
    let preview_sink = Rc::clone(&previewed);
    let mut selector = ThemeSelectorComponent::new(
        &theme,
        "light",
        &["dark".to_owned(), "light".to_owned()],
        Box::new(move |name| *sink.borrow_mut() = name.to_owned()),
        Box::new(|| {}),
        Box::new(move |name| *preview_sink.borrow_mut() = name.to_owned()),
    );
    let rendered = selector.render(60).join("\n");
    assert!(rendered.contains("(current)"), "{rendered}");
    assert!(rendered.contains("light"), "{rendered}");
    selector.handle_input("\r");
    assert_eq!(*selected.borrow(), "light");
}

/// The extension selector windows long lists and reports the picked option.
#[test]
fn extension_selector_windows_and_selects() {
    let theme = theme();
    let options: Vec<String> = (0..20).map(|index| format!("option-{index}")).collect();
    let picked = Rc::new(std::cell::RefCell::new(String::new()));
    let sink = Rc::clone(&picked);
    let mut selector = ExtensionSelectorComponent::new(
        &theme,
        full_keybindings(),
        "Pick",
        options,
        Box::new(move |option| *sink.borrow_mut() = option.to_owned()),
        Box::new(|| {}),
        ExtensionSelectorOptions {
            terminal_rows: Some(20),
            ..ExtensionSelectorOptions::default()
        },
    );
    let rendered = selector.render(60).join("\n");
    assert!(rendered.contains("more below"), "{rendered}");
    assert!(rendered.contains("navigate"), "{rendered}");
    assert!(rendered.contains("Pick"), "{rendered}");
    selector.handle_input("j");
    assert_eq!(selector.selected_index(), 1);
    selector.handle_input("\r");
    assert_eq!(*picked.borrow(), "option-1");
}

/// The extension input prefills by typing, so the cursor lands after the initial value.
#[test]
fn extension_input_prefills_with_cursor_at_end() {
    let theme = theme();
    let submitted = Rc::new(std::cell::RefCell::new(String::new()));
    let sink = Rc::clone(&submitted);
    let mut component = ExtensionInputComponent::new(
        &theme,
        "Name",
        Box::new(move |value| *sink.borrow_mut() = value.to_owned()),
        Box::new(|| {}),
        ExtensionInputOptions {
            initial_value: Some("abc".to_owned()),
            ..ExtensionInputOptions::default()
        },
    );
    assert_eq!(component.input().get_value(), "abc");
    component.handle_input("d");
    assert_eq!(component.input().get_value(), "abcd");
    let rendered = component.render(60).join("\n");
    assert!(rendered.contains("Name"), "{rendered}");
    assert!(rendered.contains("submit"), "{rendered}");
    component.handle_input("\r");
    assert_eq!(*submitted.borrow(), "abcd");
}

/// The OAuth selector labels provider auth types and filters by the search input.
#[test]
fn oauth_selector_labels_and_filters_providers() {
    let theme = theme();
    let providers = vec![
        AuthSelectorProvider {
            id: "anthropic".to_owned(),
            name: "Anthropic".to_owned(),
            auth_type: AuthSelectorAuthType::OAuth,
            method_name: Some("Claude Pro".to_owned()),
            status: None,
        },
        AuthSelectorProvider {
            id: "openai".to_owned(),
            name: "OpenAI".to_owned(),
            auth_type: AuthSelectorAuthType::ApiKey,
            method_name: None,
            status: None,
        },
    ];
    assert_eq!(format_auth_selector_provider_type(AuthSelectorAuthType::OAuth), "subscription");
    assert_eq!(format_auth_selector_provider_type(AuthSelectorAuthType::ApiKey), "API key");

    let picked = Rc::new(std::cell::RefCell::new(Vec::<String>::new()));
    let sink = Rc::clone(&picked);
    let mut selector = OAuthSelectorComponent::new(
        &theme,
        AuthSelectorMode::Login,
        providers,
        Box::new(move |id, auth_type| {
            sink.borrow_mut().push(format!("{id}:{}", format_auth_selector_provider_type(auth_type)))
        }),
        Box::new(|| {}),
        None,
    );
    let rendered = selector.render(80).join("\n");
    assert!(rendered.contains("Select provider to configure:"), "{rendered}");
    assert!(rendered.contains("[subscription]"), "{rendered}");
    assert!(rendered.contains("unconfigured"), "{rendered}");

    for ch in "openai".chars() {
        selector.handle_input(&ch.to_string());
    }
    assert_eq!(selector.filtered_providers().len(), 1);
    assert_eq!(selector.filtered_providers()[0].id, "openai");
    selector.handle_input("\r");
    assert_eq!(*picked.borrow(), vec!["openai:API key".to_owned()]);
}

/// Keybinding hints render the pinned senpi key aliases and capitalization.
#[test]
fn keybinding_hints_format_like_senpi() {
    let golden = golden();
    for case in golden["helpers"]["formatKeyText"].as_array().expect("formatKeyText") {
        let key = case[0].as_str().unwrap_or_default();
        assert_eq!(format_key_text(key, false), case[1].as_str().unwrap_or_default(), "{key}");
        assert_eq!(format_key_text(key, true), case[2].as_str().unwrap_or_default(), "{key}");
    }
    let theme = theme();
    assert_eq!(
        key_hint("tui.select.confirm", "select", &theme),
        format!(
            "{}{}",
            theme.fg(ThemeColor::Dim, "enter"),
            theme.fg(ThemeColor::Muted, " select")
        )
    );
    assert_eq!(
        raw_key_hint("↑↓", "navigate", &theme),
        format!(
            "{}{}",
            theme.fg(ThemeColor::Dim, "↑↓"),
            theme.fg(ThemeColor::Muted, " navigate")
        )
    );
}

/// The auth-type label and the idle-timeout labels match pinned senpi.
#[test]
fn provider_type_and_idle_timeout_labels_match_senpi() {
    let golden = golden();
    for case in golden["helpers"]["formatAuthSelectorProviderType"]
        .as_array()
        .expect("formatAuthSelectorProviderType")
    {
        let auth_type = match case[0].as_str() {
            Some("oauth") => AuthSelectorAuthType::OAuth,
            Some("api_key") => AuthSelectorAuthType::ApiKey,
            other => panic!("unexpected auth type {other:?}"),
        };
        assert_eq!(
            format_auth_selector_provider_type(auth_type),
            case[1].as_str().unwrap_or_default()
        );
    }
    for case in golden["helpers"]["formatHttpIdleTimeoutMs"]
        .as_array()
        .expect("formatHttpIdleTimeoutMs")
    {
        let timeout_ms = case[0].as_u64().expect("timeout ms");
        assert_eq!(format_http_idle_timeout_ms(timeout_ms), case[1].as_str().unwrap_or_default());
    }
}

/// Session ages use senpi's compact units.
#[test]
fn session_dates_use_senpi_units() {
    let now = 1_700_000_000_000;
    assert_eq!(format_session_date(now - 30_000, now), "now");
    assert_eq!(format_session_date(now - 5 * 60_000, now), "5m");
    assert_eq!(format_session_date(now - 3 * 3_600_000, now), "3h");
    assert_eq!(format_session_date(now - 2 * 86_400_000, now), "2d");
    assert_eq!(format_session_date(now - 10 * 86_400_000, now), "1w");
    assert_eq!(format_session_date(now - 60 * 86_400_000, now), "2mo");
    assert_eq!(format_session_date(now - 400 * 86_400_000, now), "1y");
}

fn session(id: &str, path: &str, parent: Option<&str>, modified_ms: i64) -> SessionInfo {
    SessionInfo {
        path: path.to_owned(),
        id: id.to_owned(),
        cwd: "/work".to_owned(),
        name: None,
        parent_session_path: parent.map(str::to_owned),
        modified_ms,
        message_count: 1,
        first_message: format!("message from {id}"),
        all_messages_text: format!("message from {id}"),
    }
}

/// A root with two branches; the first branch has two leaves, so the tree shows
/// a continuation gutter, a non-last connector and a last connector.
fn three_branch_tree() -> Vec<SessionTreeNode> {
    let root = entry("root", None, "user", "root question");
    let mut branch_a = entry("branch-a", Some("root"), "assistant", "assistant: answer a");
    branch_a.children = vec![
        entry("leaf-a", Some("branch-a"), "assistant", "assistant: answer a1"),
        entry("leaf-b", Some("branch-a"), "assistant", "assistant: answer b1"),
    ];
    let branch_c = entry("branch-c", Some("root"), "user", "user: follow up");
    vec![SessionTreeNode {
        entry: root.entry,
        children: vec![branch_a, branch_c],
        label: None,
        label_timestamp: None,
    }]
}

fn entry(id: &str, parent_id: Option<&str>, role: &str, text: &str) -> SessionTreeNode {
    SessionTreeNode {
        entry: serde_json::json!({
            "id": id,
            "parentId": parent_id,
            "type": "message",
            "message": { "role": role, "content": [{ "type": "text", "text": text }] }
        }),
        children: Vec::new(),
        label: None,
        label_timestamp: None,
    }
}
