use maho_omo_config_watch::validate::*;
#[test] fn directory_changes_and_sibling_deletion_attributed()->Result<(),std::io::Error> {let root=tempfile::tempdir()?;let project=root.path().join("project");std::fs::create_dir(&project)?;let env=std::collections::BTreeMap::from([("HOME".into(),root.path().to_string_lossy().into_owned())]);let mut validator=OmoConfigValidator::new(project.to_string_lossy().into_owned(),env);let dir=project.join(".omo");std::fs::create_dir(&dir)?;let jsonc=dir.join("omo.jsonc");let json=dir.join("omo.json");std::fs::write(&jsonc,"{")?;assert!(matches!(validator.validate(std::slice::from_ref(&dir)),ConfigWatchValidation::Rejected{..}));std::fs::write(&jsonc,"{}")?;assert!(matches!(validator.validate(std::slice::from_ref(&jsonc)),ConfigWatchValidation::Ok));std::fs::write(&json,"{")?;std::fs::remove_file(&jsonc)?;assert!(matches!(validator.validate(&[jsonc]),ConfigWatchValidation::Rejected{..}));Ok(())}
#[test] fn catalog_cycle_and_unreadable_file_rejected()->Result<(),std::io::Error> {let root=tempfile::tempdir()?;let project=root.path().join("project");let config=project.join(".omo/omo.jsonc");std::fs::create_dir_all(config.parent().expect("parent"))?;std::fs::write(&config,"{}")?;let env=std::collections::BTreeMap::from([("HOME".into(),root.path().to_string_lossy().into_owned())]);let mut validator=OmoConfigValidator::new(project.to_string_lossy().into_owned(),env);std::fs::write(&config,r#"{"models":{"loop":{"model":"loop"}},"[senpi]":{"categories":{"quick":{"model":"loop"}}}}"#)?;assert!(matches!(validator.validate(std::slice::from_ref(&config)),ConfigWatchValidation::Rejected{..}));std::fs::remove_file(&config)?;std::fs::create_dir(&config)?;assert!(matches!(validator.validate(&[config]),ConfigWatchValidation::Rejected{..}));Ok(())}
#[test] fn schema_error_rejected_and_valid_change_accepted()->Result<(),std::io::Error> {let root=tempfile::tempdir()?;let config=root.path().join(".omo/omo.jsonc");std::fs::create_dir_all(config.parent().expect("parent"))?;std::fs::write(&config,"{\"task\":{\"default_concurrency\":3}}")?;let env=std::collections::BTreeMap::from([("HOME".into(),root.path().parent().expect("home boundary").to_string_lossy().into_owned())]);let mut validator=OmoConfigValidator::new(root.path().to_string_lossy().into_owned(),env);std::fs::write(&config,"{\"task\":{\"default_concurrency\":\"three\"}}")?;assert!(matches!(validator.validate(std::slice::from_ref(&config)),ConfigWatchValidation::Rejected{..}));std::fs::write(&config,"{\"task\":{\"default_concurrency\":4}}")?;assert!(matches!(validator.validate(&[config]),ConfigWatchValidation::Ok));Ok(())}
#[test] fn missing_optional_user_config_accepted()->Result<(),std::io::Error> {let root=tempfile::tempdir()?;let env=std::collections::BTreeMap::from([("HOME".into(),root.path().parent().expect("home boundary").to_string_lossy().into_owned())]);let mut validator=OmoConfigValidator::new(root.path().to_string_lossy().into_owned(),env);assert!(matches!(validator.validate(&[root.path().join(".maho/omo.jsonc")]),ConfigWatchValidation::Ok));Ok(())}
#[test] fn baseline_errors_do_not_reject_unrelated_changes()->Result<(),std::io::Error> {let root=tempfile::tempdir()?;let config=root.path().join(".omo/omo.jsonc");std::fs::create_dir_all(config.parent().expect("parent"))?;std::fs::write(&config,"{")?;let env=std::collections::BTreeMap::from([("HOME".into(),root.path().parent().expect("home boundary").to_string_lossy().into_owned())]);let mut validator=OmoConfigValidator::new(root.path().to_string_lossy().into_owned(),env);assert!(matches!(validator.validate(&[root.path().join("other")]),ConfigWatchValidation::Ok));Ok(())}
#[test]
fn rejects_parse_error_and_stays_sticky_until_repair()->Result<(),std::io::Error> {
    let root=tempfile::tempdir()?;let home=root.path().join("home");let project=home.join("project");let config=project.join(".omo/omo.jsonc");std::fs::create_dir_all(config.parent().expect("test path"))?;std::fs::write(&config,"{}")?;
    let env=std::collections::BTreeMap::from([("HOME".into(),home.to_string_lossy().into_owned())]);
    let mut validator=OmoConfigValidator::new(project.to_string_lossy().into_owned(),env);
    std::fs::write(&config,"{\"task\":")?;
    assert!(matches!(validator.validate(std::slice::from_ref(&config)),ConfigWatchValidation::Rejected{..}));
    assert!(matches!(validator.validate(&[project.join("other")]),ConfigWatchValidation::Rejected{..}));
    std::fs::write(&config,"{}")?;
    assert!(matches!(validator.validate(&[config]),ConfigWatchValidation::Ok));Ok(())
}
