[package]
name = "maho-ext-hooks"
version.workspace = true
edition.workspace = true
publish.workspace = true
license = "MIT"

[dependencies]
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = { version = "=1.0.149", features = ["preserve_order"] }
sha2 = "=0.10.9"
thiserror = "=2.0.18"
fancy-regex = "=0.16.2"
maho-core = { path = "../../maho-core" }
tempfile = "=3.27.0"
tokio = { version = "=1.52.3", features = ["process", "io-util", "time", "macros", "rt-multi-thread"] }
maho-tools = { path = "../../maho-tools" }
futures = "=0.3.34"

[target.'cfg(unix)'.dependencies]
nix = { version = "=0.28.0", features = ["signal", "process"] }

[lints]
workspace = true
