use maho_ext_permission_system::external_dir::{expand_home,is_external_path,extract_external_paths};
use std::path::Path;
#[test]
fn home_expansions(){let home=Path::new("/home/user");for (input,expected) in [("~","/home/user"),("~/projects/app","/home/user/projects/app"),("~\\projects\\app","/home/user/projects\\app"),("$HOME","/home/user"),("$HOME/projects/app","/home/user/projects/app"),("$HOME\\projects\\app","/home/user/projects\\app"),("/usr/local/bin","/usr/local/bin"),("./src/file.ts","./src/file.ts")]{assert_eq!(expand_home(input,home),Path::new(expected));}}
#[test]
fn containment_cases(){let cwd=Path::new("/home/user/project");let home=Path::new("/home/user");for (input,external) in [("/home/user/project/src/file.ts",false),("./src/file.ts",false),("src/file.ts",false),("/home/other/project",true),("../sibling",true),("../../other/project",true),("/home/user/project",false),(".",false),("~/project/src/file.ts",false),("~/other-project",true),("$HOME/project/src/file.ts",false),("$HOME/other-project",true),("/home/user/project/src/../config",false)]{assert_eq!(is_external_path(input,cwd,home),external,"{input}");}}
#[test]
fn command_cases(){let cwd=Path::new("/home/user/project");let home=Path::new("/home/user");for (command,expected) in [
    ("ls -la",vec![]),("cat /home/other/project/file.txt",vec!["/home/other/project/file.txt"]),("cat ../sibling/file.txt",vec!["../sibling/file.txt"]),("cat ./src/file.ts src/utils.ts",vec![]),("cat ~/other-project/file.txt",vec!["~/other-project/file.txt"]),("cat $HOME/other-project/file.txt",vec!["$HOME/other-project/file.txt"]),("cat \"/home/other/file with spaces.txt\"",vec!["/home/other/file with spaces.txt"]),("cp /home/other/file1 /home/other/file2 .",vec!["/home/other/file1","/home/other/file2"]),("ls -la --color=auto /home/other/project",vec!["/home/other/project"]),("ENV_VAR=value cat file.txt",vec![]),("cp ./internal.txt /home/external/file.txt",vec!["/home/external/file.txt"]),("cat /etc/passwd | grep root > /home/other/output.txt",vec!["/etc/passwd","/home/other/output.txt"]),("mkdir -p /home/other/new-dir",vec!["/home/other/new-dir"]),("touch /home/other/file.txt",vec!["/home/other/file.txt"]),
]{assert_eq!(extract_external_paths(command,cwd,home),expected,"{command}");}}
