use super::*;
fn scheduler()->LoopScheduler { LoopScheduler::new("s",None,&BTreeMap::new()) }
fn dynamic()->CreateDynamicRequest { CreateDynamicRequest { original_args:"check".into(),reentry_prompt:"/loop check".into(),payload:LoopPayload::Prompt { prompt:"check".into() } } }
fn fixed()->CreateFixedRequest { CreateFixedRequest { base:dynamic(),requested_interval:RequestedInterval { value:1.0,unit:RequestedIntervalUnit::Minutes,raw:"1m".into() },effective_interval:EffectiveInterval { value:1.0,unit:EffectiveIntervalUnit::Minutes,human:"1 minute".into(),rounded:false,rounding_notice:None },cron_expression:"* * * * *".into(),interval_ms:60000.0 } }
fn wake(id:&str)->ScheduleWakeupInput { ScheduleWakeupInput { loop_id:id.into(),delay_seconds:60.0,requested_delay_seconds:60.0,reason:"wait".into(),prompt:"/loop check".into(),noop:false } }
#[test] fn upstream_fixed_creation_arms_from_now() { let mut s=scheduler(); s.create_fixed(fixed(),"f".into(),1000.0); assert_eq!(s.armed_timers["f"],61000.0); assert_eq!(fields(&s.state.entries["f"]).expires_at,1000.0+LOOP_EXPIRY_MS); }
#[test] fn upstream_fixed_fire_recomputes_from_actual_now() { let mut s=scheduler(); s.create_fixed(fixed(),"f".into(),0.0); assert!(matches!(s.on_due("f",65000.0,false,"d".into()),DueResult::Dispatch(_))); assert_eq!(s.armed_timers["f"],125000.0); }
#[test] fn upstream_sixth_loop_cap_preserves_existing_timers() { let mut s=scheduler(); for i in 0..5 { s.create_fixed(fixed(),i.to_string(),0.0); } let timers=s.armed_timers.clone(); assert!(matches!(s.create_fixed(fixed(),"six".into(),0.0),CreateResult::Cap { .. })); assert_eq!(s.armed_timers,timers); assert_eq!(s.state.entries.len(),5); }
#[test] fn upstream_dynamic_starts_credit_without_timer() { let mut s=scheduler(); s.create_dynamic(dynamic(),"d".into(),0.0); assert!(s.armed_timers.is_empty()); assert!(matches!(&s.state.entries["d"],CronEntry::Dynamic { keepalive_credit:1,pending_wakeup:None,.. })); }
#[test] fn upstream_clock_jump_coalesces_single_fire() { let mut s=scheduler(); s.create_fixed(fixed(),"f".into(),0.0); let now=3.0*86400000.0; assert!(matches!(s.on_due("f",now,false,"d".into()),DueResult::Dispatch(_))); assert_eq!(fields(&s.state.entries["f"]).tick_count,1.0); assert_eq!(s.armed_timers["f"],now+60000.0); }
#[test] fn upstream_expired_due_never_dispatches() { let mut s=scheduler(); s.create_dynamic(dynamic(),"d".into(),0.0); assert_eq!(s.on_due("d",LOOP_EXPIRY_MS,false,"unused".into()),DueResult::Expire); assert_eq!(lifecycle(&s.state.entries["d"]).end_reason,Some(LoopEndReason::Expired)); }
#[test] fn upstream_post_expiry_fixed_arm_ends() { let mut s=scheduler(); let mut request=fixed(); request.interval_ms=LOOP_EXPIRY_MS; s.create_fixed(request,"f".into(),0.0); assert!(s.armed_timers.is_empty()); assert_eq!(lifecycle(&s.state.entries["f"]).end_reason,Some(LoopEndReason::Expired)); }
#[test] fn upstream_restore_overdue_expiry_has_no_recovery() { let mut s=scheduler(); s.create_fixed(fixed(),"f".into(),0.0); let result=s.restore(LOOP_EXPIRY_MS,&[],||panic!("expired recovery")); assert_eq!(result.expired_loop_ids,["f"]); assert!(result.recovery_ticks.is_empty()); }
#[test] fn upstream_successful_model_schedule_replenishes_credit() { let mut s=scheduler(); s.create_dynamic(dynamic(),"d".into(),0.0); assert!(matches!(s.on_turn_ended_without_schedule("d","k".into(),1.0),KeepaliveResult::Armed { .. })); s.on_schedule_wakeup(wake("d"),"w".into(),2.0); assert!(matches!(s.on_turn_ended_without_schedule("d","k2".into(),3.0),KeepaliveResult::Armed { .. })); }
#[test] fn upstream_fixed_never_consumes_keepalive() { let mut s=scheduler(); s.create_fixed(fixed(),"f".into(),0.0); assert_eq!(s.on_turn_ended_without_schedule("f","unused".into(),1.0),KeepaliveResult::Ignored); }
#[test] fn upstream_provider_error_is_not_terminal() { let mut s=scheduler(); s.create_dynamic(dynamic(),"d".into(),0.0); s.on_due("d",1.0,false,"delivery".into()); assert_eq!(s.on_tick_settled("d","delivery",TickOutcome::Error,2.0,"unused".into()),SettledResult::Idle); assert_eq!(lifecycle(&s.state.entries["d"]).phase,LoopPhase::Waiting); assert!(matches!(s.on_turn_ended_without_schedule("d","wake".into(),2.0),KeepaliveResult::Armed { .. })); }
#[test] fn upstream_resume_fixed_recomputes_from_now() { let mut s=scheduler(); s.create_fixed(fixed(),"f".into(),0.0); s.pause("f",1.0); assert!(s.armed_timers.is_empty()); s.resume("f",100000.0); assert_eq!(s.armed_timers["f"],160000.0); }
#[test] fn upstream_pause_resume_all_preserves_both_kinds() { let mut s=scheduler(); s.create_fixed(fixed(),"f".into(),0.0); s.create_dynamic(dynamic(),"d".into(),0.0); assert_eq!(s.pause("all",1.0),["f","d"]); assert_eq!(s.resume("all",2.0),["f","d"]); }
#[test] fn upstream_stop_is_idempotent_and_cannot_resurrect() { let mut s=scheduler(); s.create_fixed(fixed(),"f".into(),0.0); assert_eq!(s.stop("f","done",1.0),["f"]); assert!(s.stop("all","done",2.0).is_empty()); assert!(s.resume("all",3.0).is_empty()); assert_eq!(lifecycle(&s.state.entries["f"]).end_reason,Some(LoopEndReason::Stopped)); }
#[test] fn upstream_stopped_due_callback_is_inert() { let mut s=scheduler(); s.create_fixed(fixed(),"f".into(),0.0); s.stop("f","done",1.0); let revision=s.mutation_count; assert_eq!(s.on_due("f",60000.0,false,"stale".into()),DueResult::Coalesce); assert_eq!(s.mutation_count,revision); assert!(s.armed_timers.is_empty()); }
#[test] fn upstream_paused_due_callback_is_inert() { let mut s=scheduler(); s.create_fixed(fixed(),"f".into(),0.0); s.pause("f",1.0); assert_eq!(s.on_due("f",60000.0,false,"stale".into()),DueResult::Coalesce); assert_eq!(fields(&s.state.entries["f"]).tick_count,0.0); }
#[test] fn upstream_shutdown_has_no_terminal_reason() { let mut s=scheduler(); s.create_fixed(fixed(),"f".into(),0.0); s.create_dynamic(dynamic(),"d".into(),0.0); s.on_shutdown(1.0); for entry in s.state.entries.values() { assert_eq!(lifecycle(entry).phase,LoopPhase::Suspended); assert!(lifecycle(entry).end_reason.is_none()); } assert!(s.armed_timers.is_empty()); }
#[test] fn upstream_restore_overdue_fixed_recovers_once() { let mut s=scheduler(); s.create_fixed(fixed(),"f".into(),0.0); let result=s.restore(100000.0,&[],||"recover".into()); assert_eq!(result.recovery_ticks.len(),1); assert_eq!(s.armed_timers["f"],160000.0); assert!(s.restore(100000.0,&[],||panic!("duplicate recovery")).recovery_ticks.is_empty()); }
#[test] fn upstream_restore_overdue_dynamic_drops_wakeup() { let mut s=scheduler(); s.create_dynamic(dynamic(),"d".into(),0.0); s.on_schedule_wakeup(wake("d"),"w".into(),0.0); let result=s.restore(60001.0,&[],||"recover".into()); assert_eq!(result.recovery_ticks.len(),1); assert!(matches!(&s.state.entries["d"],CronEntry::Dynamic { pending_wakeup:None,.. })); }
#[test] fn upstream_restore_stopped_stays_ended() { let mut s=scheduler(); s.create_fixed(fixed(),"f".into(),0.0); s.stop("f","done",1.0); assert!(s.restore(100000.0,&[],||panic!("stopped recovery")).recovery_ticks.is_empty()); assert_eq!(lifecycle(&s.state.entries["f"]).phase,LoopPhase::Ended); }
#[test] fn upstream_tick_budget_ends_without_rearm() { let mut s=LoopScheduler::new("s",None,&BTreeMap::from([(MAX_TICKS_ENV.into(),"1".into())])); s.create_fixed(fixed(),"f".into(),0.0); s.on_due("f",60000.0,false,"d".into()); assert_eq!(s.on_tick_settled("f","d",TickOutcome::Completed,60001.0,"unused".into()),SettledResult::Ended(LoopEndReason::TickBudgetExhausted)); assert!(s.armed_timers.is_empty()); }
#[test] fn upstream_max_ticks_default_and_subone_clamp() { assert_eq!(scheduler().max_ticks,DEFAULT_MAX_TICKS); assert_eq!(LoopScheduler::new("s",None,&BTreeMap::from([(MAX_TICKS_ENV.into(),"0".into())])).max_ticks,1.0); }
