//! Rust port of the `@oh-my-opencode/model-core` package (SUL-1.0, internal use only).
//!
//! Harness-neutral model resolution: model identity parsing, capability tables and lookup,
//! hardcoded fallback chains, the resolution pipeline, and runtime-fallback error classification.

mod connected_providers_cache;
mod context_limit_resolver;
mod fallback_chain_from_models;
mod fallback_model_object;
mod js_value;
mod model_availability;
mod model_capabilities;
mod model_capabilities_snapshot;
mod model_capability_aliases;
mod model_capability_guardrails;
mod model_capability_heuristics;
mod model_error_classifier;
mod model_family_detectors;
mod model_format_normalizer;
mod model_normalization;
mod model_requirement_types;
mod model_requirements;
mod model_resolution_pipeline;
mod model_resolver;
mod model_sanitizer;
mod model_settings_compatibility;
mod model_string_parser;
mod parse_model_suggestion;
mod provider_cache;
mod provider_exhaustion_fallback_policy;
mod provider_model_id_transform;
mod reasoning_level;
mod runtime_fallback_auto_retry_signal;
mod runtime_fallback_error_classifier;
mod runtime_fallback_error_shape;
mod runtime_fallback_model;
mod runtime_fallback_retryable_patterns;

pub use connected_providers_cache::*;
pub use context_limit_resolver::*;
pub use fallback_chain_from_models::*;
pub use fallback_model_object::*;
pub use model_availability::fuzzy_match_model;
pub use model_availability::is_model_available;
pub use model_capabilities::*;
pub use model_capabilities_snapshot::*;
pub use model_capability_aliases::*;
pub use model_capability_guardrails::*;
pub use model_capability_heuristics::*;
pub use model_error_classifier::*;
pub use model_family_detectors::*;
pub use model_format_normalizer::*;
pub use model_normalization::*;
pub use model_requirement_types::*;
pub use model_requirements::*;
pub use model_resolution_pipeline::_set_model_resolution_log_implementation_for_testing;
pub use model_resolution_pipeline::FuzzyMatchFn;
pub use model_resolution_pipeline::LogImplementation;
pub use model_resolution_pipeline::ModelResolutionDeps;
pub use model_resolution_pipeline::ModelResolutionProvenance;
pub use model_resolution_pipeline::ModelResolutionRequest;
pub use model_resolution_pipeline::ModelResolutionResult as PipelineModelResolutionResult;
pub use model_resolution_pipeline::ResolutionConstraints;
pub use model_resolution_pipeline::ResolutionIntent;
pub use model_resolution_pipeline::ResolutionPolicy;
pub use model_resolution_pipeline::resolve_model_pipeline;
pub use model_resolution_pipeline::resolve_model_pipeline_with;
pub use model_resolver::*;
pub use model_sanitizer::*;
pub use model_settings_compatibility::*;
pub use model_string_parser::ParsedModelString;
pub use model_string_parser::ParsedVariant;
pub use model_string_parser::parse_model_string;
pub use model_string_parser::parse_variant_from_model_id;
pub use parse_model_suggestion::*;
pub use provider_cache::*;
pub use provider_exhaustion_fallback_policy::*;
pub use provider_model_id_transform::*;
pub use reasoning_level::*;
pub use runtime_fallback_error_classifier::*;
pub use runtime_fallback_model::*;
