[package]
name = "maho-omo-telemetry"
version.workspace = true
edition.workspace = true
publish.workspace = true
license = "LicenseRef-SUL-1.0"

[lints]
workspace = true

[dependencies]
serde_json.workspace = true
maho-ext-api = { path = "../../../maho-ext-api" }
maho-telemetry-core = { path = "../../telemetry-core" }
maho-senpi-task = { path = "../../senpi-task" }
chrono = { workspace = true, features = ["clock", "std"] }
tokio = { workspace = true, features = ["rt", "time", "macros"] }
futures.workspace = true
sha2.workspace = true

[dev-dependencies]
tempfile.workspace = true
maho-test-support = { path = "../../../maho-test-support", features = ["sdk"] }
maho-ext-host = { path = "../../../maho-ext-host" }
