[package]
name = "maho-ext-ttsr"
version.workspace = true
edition.workspace = true
publish.workspace = true
license = "MIT"

[dependencies]
regex = "=1.12.3"
fancy-regex = "=0.16.2"
globset = "=0.4.20"
serde_yaml = "=0.9.34"
maho-ai = { path = "../../maho-ai" }
maho-ext-api = { path = "../../maho-ext-api" }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.149"

[dev-dependencies]
tempfile = "=3.27.0"

[lints]
workspace = true
