use std::{path::PathBuf,sync::{Arc,Mutex}};
use maho_ext_api::{BusSubscription,EventKind,EventResult,Extension,ExtensionApi,ExtensionEvent,SessionReason};
use crate::{index::SenpiTelemetryOptions,omo_native_parallel::ParallelTelemetryRegistry,omo_native_parallel_summary::{SummaryCapture,register_omo_native_parallel_summary},product_identity::{get_omo_native_state_dir,hash_session_id}};
pub type ConfigEnabled=Arc<dyn Fn(&std::path::Path)->bool+Send+Sync>;
pub struct OmoNativeTelemetryComponent {
    pub options:SenpiTelemetryOptions,
    pub skills_root:PathBuf,
    pub is_config_enabled:ConfigEnabled,
    pub clock:Arc<dyn Fn()->f64+Send+Sync>,
    subscriptions:Mutex<Vec<BusSubscription>>,
}
impl OmoNativeTelemetryComponent {pub fn new(options:SenpiTelemetryOptions,skills_root:PathBuf,is_config_enabled:ConfigEnabled)->Self {Self {options,skills_root,is_config_enabled,clock:Arc::new(||std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap_or_default().as_secs_f64()*1000.0),subscriptions:Mutex::default()}}}
impl Extension for OmoNativeTelemetryComponent {
    fn register(&self,api:&mut ExtensionApi) {
        if api.runtime.get_flag("omo-senpi-telemetry-disabled")==Some(maho_ext_api::FlagValue::Boolean(true)) {return;}
        let env=self.options.env.clone().unwrap_or_else(||std::env::vars().collect());
        let state_dir=self.options.state_dir.clone().unwrap_or_else(||get_omo_native_state_dir(&env));
        let notice_state_dir=state_dir.clone();
        let shared:Arc<Mutex<Option<telemetry_core::EventTelemetryClient>>>=Arc::default();
        let client=Arc::clone(&shared);
        let capture:SummaryCapture=Arc::new(move |name,properties| {if let Some(client)=client.lock().unwrap_or_else(std::sync::PoisonError::into_inner).as_ref() && let Some(properties)=properties.as_object() {client.capture_event(name,properties);}});
        let identity_client=Arc::clone(&shared);
        let hash:Arc<dyn Fn(&str)->String+Send+Sync>=Arc::new(move |id| {
            if identity_client.lock().unwrap_or_else(std::sync::PoisonError::into_inner).is_none() {return String::new();}
            hash_session_id(id,&state_dir).unwrap_or_else(|error| {eprintln!("omo-native session identity failed: {error}");String::new()})
        });
        let registry=Arc::new(Mutex::new(ParallelTelemetryRegistry::default()));
        let now=Arc::clone(&self.clock);
        let subscription=register_omo_native_parallel_summary(api,registry,now,Arc::clone(&hash),Arc::clone(&capture));
        self.subscriptions.lock().unwrap_or_else(std::sync::PoisonError::into_inner).push(subscription);
        let options=self.options.clone();let enabled=Arc::clone(&self.is_config_enabled);let client=Arc::clone(&shared);
        api.on(EventKind::SessionStart,Arc::new(move |event,ctx| {let result=if enabled(&ctx.cwd) && let ExtensionEvent::SessionStart(event)=event {
            let reason=match event.reason {SessionReason::Startup=>"startup",SessionReason::Reload=>"reload",SessionReason::New=>"new",SessionReason::Resume=>"resume",SessionReason::Fork=>"fork",SessionReason::Quit=>"startup"};
            crate::omo_native_session::start_native_session(&options,ctx.session_manager.session_id(),&serde_json::json!({"reason":reason}),&ctx.agent_dir).map(|session|{*client.lock().unwrap_or_else(std::sync::PoisonError::into_inner)=session;})
        } else {Ok(())};Box::pin(async move {if let Err(error)=result {eprintln!("telemetry_capture_failed: omo-native-session: {error}");}Ok(EventResult::None)})}));
        api.on(EventKind::SessionShutdown,Arc::new(move |_,_| {let client=shared.lock().unwrap_or_else(std::sync::PoisonError::into_inner).take();Box::pin(async move {if let Some(client)=client {client.shutdown().await;}Ok(EventResult::None)})}));
        crate::omo_native_turns::register_omo_native_turn_telemetry(api,Arc::clone(&hash),Arc::clone(&capture),Arc::new(||eprintln!("telemetry_event_property_rejected: turn_end assistant usage contained missing or invalid values")));
        crate::omo_native_tools::register_omo_native_tool_telemetry(api,self.skills_root.clone(),hash,capture,Some(Arc::new(|message,details|eprintln!("{message}: {details}"))));
        crate::omo_native_notice::register_omo_native_notice(api,env,notice_state_dir,Arc::clone(&self.is_config_enabled));
    }
}
#[cfg(test)]
mod tests {
    use super::*;use crate::telemetry_test_support::*;use telemetry_core::*;use futures::future::BoxFuture;
    struct Recorder(Arc<Mutex<Vec<TelemetryCaptureMessage>>>);
    impl TelemetryTransport for Recorder {fn capture(&self,m:&TelemetryCaptureMessage)->Result<(),TelemetryError> {self.0.lock().unwrap().push(m.clone());Ok(())}fn flush(&self)->Option<BoxFuture<'_,Result<(),TelemetryError>>> {None}fn shutdown(&self)->BoxFuture<'_,Result<(),TelemetryError>> {Box::pin(async {Ok(())})}}
    fn component(home:&std::path::Path)->(OmoNativeTelemetryComponent,Arc<Mutex<Vec<TelemetryCaptureMessage>>>) {std::fs::write(home.join("models.json"),"{\"providers\":{}}").unwrap();std::fs::write(home.join("settings.json"),"{}").unwrap();let messages=Arc::new(Mutex::new(Vec::new()));let captured=Arc::clone(&messages);let options=SenpiTelemetryOptions {env:Some(env(home)),state_dir:Some(home.join("native")),transport_factory:Some(Arc::new(move |_,_|Ok(Box::new(Recorder(Arc::clone(&captured)))))),..Default::default()};{let mut component=OmoNativeTelemetryComponent::new(options,home.join("skills"),Arc::new(|_|true));let clock=std::sync::atomic::AtomicU64::new(1000);component.clock=Arc::new(move || f64::from(u32::try_from(clock.fetch_add(1,std::sync::atomic::Ordering::SeqCst)).unwrap()));(component,messages)}}
    fn start()->ExtensionEvent {ExtensionEvent::SessionStart(maho_ext_api::SessionStartEvent {reason:SessionReason::Startup,initial_model_provenance:None,previous_session_file:None})}
    fn shutdown()->ExtensionEvent {ExtensionEvent::SessionShutdown(maho_ext_api::SessionShutdownEvent {reason:SessionReason::Quit,target_session_file:None,signal:None})}
    #[tokio::test] async fn corrupt_inventory_reports_once_omits_defaults() {let t=tempfile::tempdir().unwrap();let (mut component,messages)=component(t.path());std::fs::write(t.path().join("models.json"),"{not json").unwrap();std::fs::write(t.path().join("settings.json"),"{\"defaultProvider\":\"anthropic\",\"defaultModel\":\"claude-sonnet-5\"}").unwrap();let diagnostics=Arc::new(Mutex::new(Vec::new()));let observed=Arc::clone(&diagnostics);component.options.inventory_diagnostics=Some(Arc::new(move |d|observed.lock().unwrap().push((d.event,d.source))));let mut api=api();component.register(&mut api);let ctx=context(t.path(),"corrupt");dispatch(&api,start(),&ctx).await;dispatch(&api,shutdown(),&ctx).await;let messages=messages.lock().unwrap();let p=&messages.iter().find(|m|m.event=="session_started").unwrap().properties;assert_eq!(p["provider_count"],0);assert_eq!(p["model_count"],0);assert!(!p.contains_key("default_provider"));assert!(!p.contains_key("default_model"));assert_eq!(*diagnostics.lock().unwrap(),vec![("omo_native_inventory_read_failed","omo-native-session")]);}
    #[tokio::test] async fn absent_inventory_reports_once() {let t=tempfile::tempdir().unwrap();let (mut component,messages)=component(t.path());std::fs::remove_file(t.path().join("models.json")).unwrap();let diagnostics=Arc::new(std::sync::atomic::AtomicUsize::new(0));let observed=Arc::clone(&diagnostics);component.options.inventory_diagnostics=Some(Arc::new(move |_|{observed.fetch_add(1,std::sync::atomic::Ordering::SeqCst);}));let mut api=api();component.register(&mut api);let ctx=context(t.path(),"absent");dispatch(&api,start(),&ctx).await;dispatch(&api,shutdown(),&ctx).await;assert_eq!(diagnostics.load(std::sync::atomic::Ordering::SeqCst),1);let messages=messages.lock().unwrap();assert_eq!(messages.iter().find(|m|m.event=="session_started").unwrap().properties["providers"],"");}
    #[tokio::test] async fn session_inventory_privacy_exact_keys() {let t=tempfile::tempdir().unwrap();let (component,messages)=component(t.path());std::fs::write(t.path().join("models.json"),serde_json::json!({"providers":{"anthropic":{"models":[{"id":"claude-sonnet-5"},{"id":"private-model"}]},"private_cloud":{"models":[{"id":"secret-model"}]}}}).to_string()).unwrap();std::fs::write(t.path().join("settings.json"),"{\"defaultProvider\":\"anthropic\",\"defaultModel\":\"private-model\"}").unwrap();let mut api=api();component.register(&mut api);let ctx=context(t.path(),"inventory");dispatch(&api,start(),&ctx).await;dispatch(&api,shutdown(),&ctx).await;let messages=messages.lock().unwrap();let p=&messages.iter().find(|m|m.event=="session_started").unwrap().properties;assert_eq!(p["default_model"],"custom");assert_eq!(p["default_provider"],"anthropic");assert_eq!(p["model_count"],3);assert_eq!(p["provider_count"],2);assert_eq!(p["providers"],"anthropic");let mut expected:Vec<_>=crate::product_identity::EVENT_PROPERTY_ALLOWLISTS.iter().find(|(n,_)|*n=="session_started").unwrap().1.to_vec();expected.extend(["$process_person_profile","package_version","platform","product_name","schema_version"]);expected.sort();let mut actual:Vec<_>=p.keys().map(String::as_str).collect();actual.sort();assert_eq!(actual,expected);assert!(!serde_json::to_string(p).unwrap().contains("private"));}
    #[tokio::test] async fn disabled_component_flag_registers_nothing() {let t=tempfile::tempdir().unwrap();let (component,messages)=component(t.path());let mut api=api();api.runtime.set_flag("omo-senpi-telemetry-disabled",maho_ext_api::FlagValue::Boolean(true));component.register(&mut api);dispatch(&api,start(),&context(t.path(),"disabled")).await;assert!(messages.lock().unwrap().is_empty());assert!(api.registered.handlers.is_empty());}
    #[tokio::test] async fn injected_shutdown_bound() {let t=tempfile::tempdir().unwrap();let (mut component,_)=component(t.path());let delays=Arc::new(Mutex::new(Vec::new()));let recorded=Arc::clone(&delays);component.options.set_timeout_fn=Some(Arc::new(move |delay| {recorded.lock().unwrap().push(delay);Box::pin(futures::future::pending())}));let mut api=api();component.register(&mut api);let ctx=context(t.path(),"s");dispatch(&api,start(),&ctx).await;dispatch(&api,shutdown(),&ctx).await;assert_eq!(*delays.lock().unwrap(),vec![std::time::Duration::from_millis(1000)]);}
    #[tokio::test] async fn native_feature_event_stream() {
        let t=tempfile::tempdir().unwrap();let (component,messages)=component(t.path());let mut api=api();component.register(&mut api);let ctx=context(t.path(),"stream");
        dispatch(&api,start(),&ctx).await;
        dispatch(&api,ExtensionEvent::ToolResult(maho_ext_api::ToolResultEvent {tool_call_id:"goal".into(),tool_name:"create_goal".into(),input:serde_json::json!({}),content:Vec::new(),details:None,is_error:false,usage:None}),&ctx).await;
        dispatch(&api,shutdown(),&ctx).await;
        let messages=messages.lock().unwrap();let native:Vec<_>=messages.iter().filter(|m|m.event!="omo_senpi_daily_active").collect();assert_eq!(native.iter().map(|m|m.event.as_str()).collect::<Vec<_>>(),vec!["daily_active","session_started","feature_used"]);
        assert_eq!(native[2].properties["feature"],"goal_tool");assert!(!native[2].properties.contains_key("input"));assert!(!t.path().join("native/last-payloads.json").exists());
    }
    #[tokio::test] async fn daily_once_per_utc_day() {let t=tempfile::tempdir().unwrap();let (mut component,messages)=component(t.path());let day=chrono::DateTime::parse_from_rfc3339("2026-07-03T04:05:06Z").unwrap().with_timezone(&chrono::Utc);component.options.now=Some(day);for (id,now) in [("first",day),("stale",day),("tomorrow",day+chrono::Duration::days(1))] {component.options.now=Some(now);let mut api=api();component.register(&mut api);let ctx=context(t.path(),id);dispatch(&api,start(),&ctx).await;dispatch(&api,shutdown(),&ctx).await;}let messages=messages.lock().unwrap();let days:Vec<_>=messages.iter().filter(|m|m.event=="daily_active").map(|m|m.properties["day_utc"].as_str().unwrap()).collect();assert_eq!(days,vec!["2026-07-03","2026-07-04"]);}
    #[tokio::test] async fn optout_does_not_create_marker() {let t=tempfile::tempdir().unwrap();let (mut component,messages)=component(t.path());component.options.env.as_mut().unwrap().insert("DO_NOT_TRACK".into(),"1".into());let mut api=api();component.register(&mut api);dispatch(&api,start(),&context(t.path(),"s")).await;assert!(messages.lock().unwrap().is_empty());assert!(!t.path().join("native").exists());}
    #[tokio::test] async fn empty_inventory_valid_session() {let t=tempfile::tempdir().unwrap();let (component,messages)=component(t.path());let mut api=api();component.register(&mut api);let ctx=context(t.path(),"s");dispatch(&api,start(),&ctx).await;dispatch(&api,shutdown(),&ctx).await;let messages=messages.lock().unwrap();let m=messages.iter().find(|m|m.event=="session_started").unwrap();assert_eq!(m.properties["provider_count"],0);assert_eq!(m.properties["model_count"],0);assert_eq!(m.properties["providers"],"");assert!(!m.properties.contains_key("default_model"));}
    #[tokio::test] async fn shutdown_summary_precedes_client_teardown() {let t=tempfile::tempdir().unwrap();let (component,messages)=component(t.path());let mut api=api();component.register(&mut api);let ctx=context(t.path(),"ordering-session");dispatch(&api,start(),&ctx).await;for id in ["a","b"] {dispatch(&api,ExtensionEvent::ToolExecutionStart {tool_call_id:id.into(),tool_name:"bash".into(),args:serde_json::json!({})},&ctx).await;}for id in ["a","b"] {dispatch(&api,ExtensionEvent::ToolExecutionEnd {tool_call_id:id.into(),tool_name:"bash".into(),result:serde_json::json!(1),is_error:false},&ctx).await;}dispatch(&api,shutdown(),&ctx).await;dispatch(&api,shutdown(),&ctx).await;let messages=messages.lock().unwrap();let summaries:Vec<_>=messages.iter().filter(|m|m.event=="parallelism_summary").collect();assert_eq!(summaries.len(),1);assert_eq!(summaries[0].properties["non_eval_joined_calls"],2);}
    #[tokio::test] async fn disabled_config_captures_nothing() {let t=tempfile::tempdir().unwrap();let (mut component,messages)=component(t.path());component.is_config_enabled=Arc::new(|_|false);let mut api=api();component.register(&mut api);dispatch(&api,start(),&context(t.path(),"disabled")).await;assert!(messages.lock().unwrap().is_empty());assert!(!t.path().join("native/notice-shown").exists());}
    #[tokio::test] async fn restart_refreshes_session_client() {let t=tempfile::tempdir().unwrap();let (component,messages)=component(t.path());let mut api=api();component.register(&mut api);for id in ["first","second"] {let ctx=context(t.path(),id);dispatch(&api,start(),&ctx).await;dispatch(&api,shutdown(),&ctx).await;dispatch(&api,shutdown(),&ctx).await;}let messages=messages.lock().unwrap();let sessions:Vec<_>=messages.iter().filter(|m|m.event=="session_started").collect();assert_eq!(sessions.len(),2);assert_ne!(sessions[0].properties["$session_id"],sessions[1].properties["$session_id"]);}
}
