use serde_json::{Value,json};
use crate::{omo_native_parallel::ParallelTelemetryRegistry,omo_native_parallel_summary::build_parallelism_summary};
fn event()->Value {json!({"version":1,"detailLevel":"full","cellId":"eval","language":"js","ok":true,"startedAt":1000,"completedAt":1030,"durationMs":30,"kernelDurationMs":24,"detached":false,"toolCallCount":2,"pendingToolCallCount":0,"toolCalls":[],"distinctToolsCalled":["read","bash"],"toolAggregates":{"read":{"count":1,"totalDurationMs":12,"okCount":1,"errorCount":0,"pendingCount":0},"bash":{"count":1,"totalDurationMs":18,"okCount":1,"errorCount":0,"pendingCount":0}},"toolAggregatesTruncated":false})}
fn record(r:&mut ParallelTelemetryRegistry,kind:&str,id:&str,name:&str,at:u32) {r.record("s",json!({"kind":kind,"toolCallId":id,"toolName":name,"atMs":at}));}
fn summary(r:&ParallelTelemetryRegistry)->Value {build_parallelism_summary(&r.snapshot("s").unwrap(),"hashed:s").unwrap()}
#[test] fn nested_counts_outside_wave_savings() {let mut r=ParallelTelemetryRegistry::default();r.set_eval_execution_event_bus_available(true);record(&mut r,"start","eval","eval",1000);r.record_eval_execution(&event());record(&mut r,"end","eval","eval",1030);let p=summary(&r);assert_eq!(p["eval_nested_tool_call_count"],2);assert_eq!(p["eval_outer_joined_calls"],1);assert_eq!(p["measured_eval_nested_tool_duration_ms_sum"],30.0);assert_eq!(p["modeled_wallclock_saved_ms"],0.0);assert_eq!(p["non_eval_saved_round_trips"],0.0);}
#[test] fn mixed_nested_and_outer_separate() {let mut r=ParallelTelemetryRegistry::default();record(&mut r,"start","eval","eval",1000);record(&mut r,"start","bash","bash",1001);r.record_eval_execution(&event());record(&mut r,"end","bash","bash",1020);record(&mut r,"end","eval","eval",1030);let p=summary(&r);assert_eq!(p["mixed_waves"],1);assert_eq!(p["eval_outer_joined_calls"],1);assert_eq!(p["mixed_non_eval_joined_calls"],1);assert_eq!(p["eval_nested_tool_call_count"],2);assert_eq!(p["modeled_wallclock_saved_ms"],0.0);}
#[test] fn unavailable_bus_explicit_zero() {let mut r=ParallelTelemetryRegistry::default();record(&mut r,"start","eval","eval",1000);record(&mut r,"end","eval","eval",1030);let p=summary(&r);assert_eq!(p["eval_execution_event_bus_available"],false);assert_eq!(p["eval_execution_event_count"],0);assert_eq!(p["eval_nested_tool_call_count"],0);assert_eq!(p["eval_outer_joined_calls"],1);}
#[test] fn rejection_no_partial_totals() {let mut r=ParallelTelemetryRegistry::default();record(&mut r,"start","eval","eval",1000);let mut e=event();e["version"]=json!(2);r.record_eval_execution(&e);record(&mut r,"end","eval","eval",1030);let p=summary(&r);assert_eq!(p["eval_execution_event_rejected_count"],1);assert_eq!(p["eval_execution_event_count"],0);assert_eq!(p["eval_nested_tool_call_count"],0);}
#[test] fn valid_eval_event_justifies_incomplete_wrapper() {let mut r=ParallelTelemetryRegistry::default();record(&mut r,"start","eval","eval",1000);r.record_eval_execution(&event());let p=summary(&r);assert_eq!(p["incomplete_calls"],1);assert_eq!(p["eval_execution_event_count"],1);assert_eq!(p["eval_outer_joined_calls"],0);assert_eq!(p["eval_nested_tool_call_count"],2);}
