pub const PARALLELISM_SUMMARY_SCHEMA: &[(&str, &str)] = &[
    ("$session_id", "string"),
    ("clock_anomalies", "number"),
    ("dropped_calls", "number"),
    ("eval_execution_detached_count", "number"),
    ("eval_execution_event_bus_available", "boolean"),
    ("eval_execution_event_count", "number"),
    ("eval_execution_event_rejected_count", "number"),
    ("eval_execution_ok_count", "number"),
    ("eval_nested_tool_call_count", "number"),
    ("eval_nested_tool_call_error_count", "number"),
    ("eval_nested_tool_call_ok_count", "number"),
    ("eval_nested_tool_call_pending_count", "number"),
    ("eval_only_duration_ms", "number"),
    ("eval_only_waves", "number"),
    ("eval_outer_joined_calls", "number"),
    ("eval_tool_aggregate_truncated_execution_count", "number"),
    ("incomplete_calls", "number"),
    ("measured_eval_execution_duration_ms_sum", "number"),
    ("measured_eval_nested_tool_duration_ms_sum", "number"),
    ("measured_turn_duration_ms_total", "number"),
    ("mixed_non_eval_joined_calls", "number"),
    ("mixed_waves", "number"),
    ("modeled_wallclock_saved_ms", "number"),
    ("non_eval_joined_calls", "number"),
    ("non_eval_saved_round_trips", "number"),
    ("non_eval_wave_size_histogram", "string"),
    ("non_eval_waves_multi", "number"),
    ("non_eval_waves_total", "number"),
    ("upper_bound_saved_ms", "number"),
    ("schema_kind", "string"),
];
pub const SCHEMA_KINDS: &[&str] = &["parallelism_v1", "parallelism_v2"];
