use serde_json::{Value,json};
use lsp_core::{lsp::config_loader::get_merged_servers,request_context::run_with_request_context};
fn fixture(project:Value,user:Option<Value>)->Vec<lsp_core::lsp::config_loader::ServerWithSource> {let t=tempfile::tempdir().unwrap();let root=t.path().join("project");std::fs::create_dir_all(root.join(".pi")).unwrap();std::fs::write(root.join(".pi/lsp-client.json"),project.to_string()).unwrap();std::fs::create_dir(t.path().join(".pi")).unwrap();if let Some(user)=user {std::fs::write(t.path().join(".pi/lsp-client.json"),user.to_string()).unwrap();}let context=crate::daemon_tool_client::current_senpi_request_context(&root,t.path()).unwrap();run_with_request_context(context,||get_merged_servers().unwrap())}
#[test] fn arbitrary_project_command_not_selected() {let servers=fixture(json!({"lsp":{"project-sentinel":{"command":["sh","-c","printf owned"],"extensions":[".sentinel"],"priority":1000}}}),None);assert!(!servers.iter().any(|s|s.server.id=="project-sentinel"));}
#[test] fn builtin_command_survives_override() {let servers=fixture(json!({"lsp":{"typescript":{"command":["sh","-c","printf owned"],"extensions":[".ts"],"priority":1000}}}),None);let server=servers.iter().find(|s|s.server.id=="typescript").unwrap();assert_eq!(server.server.command,vec!["typescript-language-server","--stdio"]);}
#[test] fn project_custom_server_ignored() {let servers=fixture(json!({"lsp":{"trusted-project-server":{"command":["trusted-lsp","--stdio"],"extensions":[".trusted"],"priority":1000}}}),None);assert!(!servers.iter().any(|s|s.server.id=="trusted-project-server"));}
#[test] fn safe_fields_keep_builtin_command_env() {let servers=fixture(json!({"lsp":{"typescript":{"command":["sh","-c","printf owned"],"env":{"OWNED":"1"},"extensions":[".tsx"],"priority":2000,"initialization":{"test":true}}}}),None);let server=&servers[0];assert_eq!(server.server.id,"typescript");assert_eq!(server.server.command,vec!["typescript-language-server","--stdio"]);assert_eq!(server.server.extensions,vec![".tsx"]);assert!(server.server.env.is_none());}
#[test] fn user_command_and_environment_preserved() {let servers=fixture(json!({}),Some(json!({"lsp":{"user-custom":{"command":["user-lsp","--stdio"],"env":{"USER_SAFE":"1"},"extensions":[".user"],"priority":500}}})));let server=&servers[0];assert_eq!(server.server.id,"user-custom");assert_eq!(server.server.command,vec!["user-lsp","--stdio"]);assert_eq!(server.server.env.as_ref().unwrap()["USER_SAFE"],"1");}
#[test] fn unsafe_configs_one_notice() {let t=tempfile::tempdir().unwrap();std::fs::create_dir(t.path().join(".pi")).unwrap();std::fs::write(t.path().join(".pi/lsp-client.json"),json!({"lsp":{"alpha":{"command":["alpha-ls"]},"beta":{"command":["beta-ls"]}}}).to_string()).unwrap();let notices=crate::adapter::migration_notices::get_config_notices(t.path(),t.path());assert_eq!(notices.len(),1);assert_eq!(notices[0].server_ids,vec!["alpha","beta"]);}
