use maho_ext_pi_rules::rules::{cache::*, types::*};
fn rule(path: &str, hash: &str) -> LoadedRule { LoadedRule { candidate: RuleCandidate { path:path.into(),real_path:path.into(),source:".omo/rules".into(),distance:0,is_global:false,is_single_file:false,relative_path:path.into() },frontmatter:RuleFrontmatter::default(),body:"body".into(),content_hash:hash.into(),match_reason:MatchReason::AlwaysApply } }
#[test] fn fresh_state_empty() { let s=create_session_state(None); assert!(s.cwd.is_none()); assert!(s.static_dedup.is_empty()); assert!(s.dynamic_dedup.is_empty()); assert!(s.loaded_rules.is_empty()); assert!(s.diagnostics.is_empty()); }
#[test] fn cwd_set_on_creation() { let s=create_session_state(Some("/workspace/project".into())); assert_eq!(s.cwd.as_deref(),Some("/workspace/project")); }
#[test] fn first_static_mark_true() { let mut s=create_session_state(None); let r=rule("a","hash"); let result=mark_static_injected(&mut s,&r); assert!(result); }
#[test] fn repeated_static_false() { let mut s=create_session_state(None); let r=rule("a","hash"); assert!(mark_static_injected(&mut s,&r)); let result=mark_static_injected(&mut s,&r); assert!(!result); }
#[test] fn different_paths_marked() { let mut s=create_session_state(None); assert!(mark_static_injected(&mut s,&rule("a","hash"))); let result=mark_static_injected(&mut s,&rule("b","hash")); assert!(result); }
#[test] fn changed_hash_marked() { let mut s=create_session_state(None); assert!(mark_static_injected(&mut s,&rule("a","first"))); let result=mark_static_injected(&mut s,&rule("a","second")); assert!(result); }
#[test] fn static_key_includes_cwd() { let mut s=create_session_state(Some("cwd".into())); let result=mark_static_injected(&mut s,&rule("a","hash")); assert!(result); assert!(s.static_dedup.contains("cwd::a::hash")); assert!(!s.static_dedup.contains("::a::hash")); }
#[test] fn first_dynamic_true() { let mut s=create_session_state(None); let result=mark_dynamic_injected(&mut s,"target",&rule("a","hash")); assert!(result); }
#[test] fn repeated_dynamic_false() { let mut s=create_session_state(None); let r=rule("a","hash"); assert!(mark_dynamic_injected(&mut s,"target",&r)); let result=mark_dynamic_injected(&mut s,"target",&r); assert!(!result); }
#[test] fn different_target_marked() { let mut s=create_session_state(None); let r=rule("a","hash"); assert!(mark_dynamic_injected(&mut s,"target",&r)); let result=mark_dynamic_injected(&mut s,"other",&r); assert!(result); }
#[test] fn dynamic_lookup() { let mut s=create_session_state(None); let r=rule("a","hash"); mark_dynamic_injected(&mut s,"target",&r); let result=is_dynamic_injected(&s,"target",&r); assert!(result); }
#[test] fn static_lookup() { let mut s=create_session_state(None); let r=rule("a","hash"); mark_static_injected(&mut s,&r); let result=is_static_injected(&s,&r); assert!(result); }
#[test] fn clear_removes_entries() { let mut s=create_session_state(None); let r=rule("a","hash"); mark_static_injected(&mut s,&r); mark_dynamic_injected(&mut s,"target",&r); s.loaded_rules.push(r); s.diagnostics.push(RuleDiagnostic{severity:Severity::Warning,source:"a".into(),message:"warning".into()}); s.dynamic_target_fingerprints.insert("target".into(),"fingerprint".into()); clear_session(&mut s); assert!(s.static_dedup.is_empty()); assert!(s.dynamic_dedup.is_empty()); assert!(s.loaded_rules.is_empty()); assert!(s.diagnostics.is_empty()); assert!(s.dynamic_target_fingerprints.is_empty()); }
#[test] fn clear_preserves_cwd() { let mut s=create_session_state(Some("cwd".into())); clear_session(&mut s); assert_eq!(s.cwd.as_deref(),Some("cwd")); }
#[test] fn static_key_deterministic() { let result=static_dedup_key("cwd","path","hash"); assert_eq!(result,"cwd::path::hash"); }
#[test] fn dynamic_key_deterministic() { let result=dynamic_dedup_key("target","path","hash"); assert_eq!(result,"target::path::hash"); }
