use std::collections::BTreeMap;
use maho_ext_pi_rules::rules::{engine::*,finder::FinderOptions,types::*};
struct Deps{candidates:Vec<RuleCandidate>,files:BTreeMap<String,String>,root_calls:usize,candidate_calls:usize,read_calls:usize,match_calls:usize,fingerprint:String}
impl EngineDeps for Deps{
    fn find_candidates(&mut self,_:FinderOptions<'_>)->Vec<RuleCandidate>{self.candidate_calls+=1;self.candidates.clone()}
    fn read_file(&mut self,path:&str)->Option<String>{self.read_calls+=1;self.files.get(path).cloned()}
    fn find_project_root(&mut self,_:&str)->Option<String>{self.root_calls+=1;Some("/workspace/project".into())}
    fn file_fingerprint(&mut self,_:&str)->String{self.fingerprint.clone()}
    fn match_rule(&mut self,matcher:&mut maho_ext_pi_rules::rules::matcher::Matcher,input:maho_ext_pi_rules::rules::matcher::MatcherInput<'_>)->Result<maho_ext_pi_rules::rules::matcher::MatchResult,globset::Error>{self.match_calls+=1;matcher.match_rule(input)}
}
fn candidate(source:&str,single:bool)->RuleCandidate{let path=format!("/workspace/project/{source}");RuleCandidate{path:path.clone(),real_path:path,source:source.into(),distance:0,is_global:false,is_single_file:single,relative_path:source.into()}}
fn engine(config:PiRulesConfig,entries:Vec<(RuleCandidate,Option<&str>)>)->Engine<Deps>{let files=entries.iter().filter_map(|(candidate,body)|body.map(|body|(candidate.path.clone(),body.into()))).collect();Engine::new(config,Deps{candidates:entries.into_iter().map(|(c,_)|c).collect(),files,root_calls:0,candidate_calls:0,read_calls:0,match_calls:0,fingerprint:"stable".into()})}
#[test]fn defaults(){let config=default_config();assert!(!config.disabled);assert_eq!(config.mode,Mode::Both);assert_eq!(config.max_rule_chars,12000);assert_eq!(config.max_result_chars,40000);assert_eq!(config.enabled_sources,EnabledSources::Auto);}
#[test]fn disabled_static(){let mut config=default_config();config.disabled=true;assert_eq!(engine(config,vec![]).load_static_rules("/workspace/project"),LoadResult::default());}
#[test]fn off_static(){let mut config=default_config();config.mode=Mode::Off;assert_eq!(engine(config,vec![]).load_static_rules("/workspace/project"),LoadResult::default());}
#[test]fn dynamic_static(){let mut config=default_config();config.mode=Mode::Dynamic;assert_eq!(engine(config,vec![]).load_static_rules("/workspace/project"),LoadResult::default());}
#[test]fn single_file(){let r=engine(default_config(),vec![(candidate("AGENTS.md",true),Some("rules"))]).load_static_rules("/workspace/project");assert_eq!(r.rules.len(),1);assert_eq!(r.rules[0].match_reason,MatchReason::SingleFile);}
#[test]fn always_apply(){let r=engine(default_config(),vec![(candidate(".omo/rules/sample.md",false),Some("---\nalwaysApply: true\n---\nbody"))]).load_static_rules("/workspace/project");assert_eq!(r.rules.len(),1);assert_eq!(r.rules[0].match_reason,MatchReason::AlwaysApply);}
#[test]fn glob_only_not_static(){let r=engine(default_config(),vec![(candidate(".omo/rules/sample.md",false),Some("---\nglobs: src/**/*.ts\n---\nbody"))]).load_static_rules("/workspace/project");assert!(r.rules.is_empty());}
#[test]fn root_first_wins(){let r=engine(default_config(),vec![(candidate("CLAUDE.md",true),Some("claude")),(candidate("AGENTS.md",true),Some("agents"))]).load_static_rules("/workspace/project");assert_eq!(r.rules.len(),1);assert_eq!(r.rules[0].candidate.source,"AGENTS.md");}
#[test]fn nested_single_not_deduped(){let mut nested=candidate("AGENTS.md",true);nested.path="/workspace/project/packages/app/AGENTS.md".into();nested.real_path=nested.path.clone();nested.relative_path="packages/app/AGENTS.md".into();nested.distance=1;let r=engine(default_config(),vec![(candidate("AGENTS.md",true),Some("root")),(nested,Some("nested"))]).load_static_rules("/workspace/project");assert_eq!(r.rules.len(),2);}
#[test]fn malformed_warns_and_continues(){let r=engine(default_config(),vec![(candidate(".omo/rules/bad.md",false),Some("---\nglobs: [unclosed\n---\nbody")),(candidate("AGENTS.md",true),Some("valid"))]).load_static_rules("/workspace/project");assert_eq!(r.diagnostics.len(),1);assert_eq!(r.rules.len(),1);}
#[test]fn unreadable_warns_and_continues(){let r=engine(default_config(),vec![(candidate(".omo/rules/missing.md",false),None),(candidate("AGENTS.md",true),Some("valid"))]).load_static_rules("/workspace/project");assert_eq!(r.diagnostics.len(),1);assert_eq!(r.diagnostics[0].message,"Unable to read rule file");assert_eq!(r.rules.len(),1);}
#[test]fn escapes_root_before_read(){let mut c=candidate(".omo/rules/leak.md",false);c.real_path="/Users/example/.ssh/id_rsa".into();let r=engine(default_config(),vec![(c,Some("---\nalwaysApply: true\n---\nsecret"))]).load_static_rules("/workspace/project");assert!(r.rules.is_empty());assert_eq!(r.diagnostics[0].message,"Rule file resolves outside project root");}
#[test]fn static_mode_no_dynamic(){let mut config=default_config();config.mode=Mode::Static;let r=engine(config,vec![(candidate("AGENTS.md",true),Some("body"))]).load_dynamic_rules("/workspace/project",&["/workspace/project/src/index.ts".into()]).unwrap();assert_eq!(r,LoadResult::default());}
#[test]fn no_targets_no_dynamic(){let r=engine(default_config(),vec![(candidate("AGENTS.md",true),Some("body"))]).load_dynamic_rules("/workspace/project",&[]).unwrap();assert_eq!(r,LoadResult::default());}
#[test]fn dynamic_glob(){let r=engine(default_config(),vec![(candidate(".omo/rules/sample.md",false),Some("---\nglobs: src/**/*.ts\n---\nbody"))]).load_dynamic_rules("/workspace/project",&["/workspace/project/src/index.ts".into()]).unwrap();assert_eq!(r.rules.len(),1);assert_eq!(r.rules[0].match_reason,MatchReason::Glob{pattern:"src/**/*.ts".into()});}
#[test]fn dynamic_glob_miss(){let r=engine(default_config(),vec![(candidate(".omo/rules/sample.md",false),Some("---\nglobs: docs/**/*.md\n---\nbody"))]).load_dynamic_rules("/workspace/project",&["/workspace/project/src/index.ts".into()]).unwrap();assert!(r.rules.is_empty());}
#[test]fn dynamic_always(){let r=engine(default_config(),vec![(candidate(".omo/rules/sample.md",false),Some("---\nalwaysApply: true\n---\nbody"))]).load_dynamic_rules("/workspace/project",&["/workspace/project/src/index.ts".into()]).unwrap();assert_eq!(r.rules.len(),1);assert_eq!(r.rules[0].match_reason,MatchReason::AlwaysApply);}
#[test]fn dynamic_root_first_wins(){let r=engine(default_config(),vec![(candidate("CLAUDE.md",true),Some("claude")),(candidate("AGENTS.md",true),Some("agents"))]).load_dynamic_rules("/workspace/project",&["/workspace/project/src/index.ts".into()]).unwrap();assert_eq!(r.rules.len(),1);assert_eq!(r.rules[0].candidate.source,"AGENTS.md");}
#[test]fn dynamic_multiple_targets_dedup(){let r=engine(default_config(),vec![(candidate(".omo/rules/sample.md",false),Some("---\nglobs: src/**/*.ts\n---\nbody"))]).load_dynamic_rules("/workspace/project",&["/workspace/project/src/first.ts".into(),"/workspace/project/src/second.ts".into()]).unwrap();assert_eq!(r.rules.len(),1);}
fn dynamic_engine()->Engine<Deps>{engine(default_config(),vec![(candidate(".omo/rules/sample.md",false),Some("---\nglobs: src/**/*.ts\n---\nbody"))])}
#[test]fn duplicate_targets_avoid_work(){let mut e=dynamic_engine();e.load_dynamic_rules("/workspace/project",&vec!["/workspace/project/src/app.ts".into();3]).unwrap();assert_eq!((e.deps.root_calls,e.deps.candidate_calls,e.deps.read_calls),(1,1,1));}
#[test]fn directory_root_reused(){let mut e=dynamic_engine();e.load_dynamic_rules("/workspace/project",&["/workspace/project/src/a.ts".into(),"/workspace/project/src/b.ts".into()]).unwrap();assert_eq!(e.deps.root_calls,1);}
#[test]fn directory_discovery_reused(){let mut e=dynamic_engine();e.load_dynamic_rules("/workspace/project",&["/workspace/project/src/a.ts".into(),"/workspace/project/src/b.ts".into()]).unwrap();assert_eq!(e.deps.candidate_calls,1);}
#[test]fn unchanged_match_reused(){let mut e=dynamic_engine();for _ in 0..2{e.load_dynamic_rules("/workspace/project",&["/workspace/project/src/app.ts".into()]).unwrap();}assert_eq!(e.deps.match_calls,1);}
#[test]fn changed_body_rechecks(){let mut e=dynamic_engine();e.load_dynamic_rules("/workspace/project",&["/workspace/project/src/app.ts".into()]).unwrap();e.deps.files.insert("/workspace/project/.omo/rules/sample.md".into(),"---\nglobs: src/**/*.ts\n---\nchanged".into());e.load_dynamic_rules("/workspace/project",&["/workspace/project/src/app.ts".into()]).unwrap();assert_eq!(e.deps.match_calls,2);}
#[test]fn changed_frontmatter_rechecks(){let mut e=dynamic_engine();e.load_dynamic_rules("/workspace/project",&["/workspace/project/src/app.ts".into()]).unwrap();e.deps.files.insert("/workspace/project/.omo/rules/sample.md".into(),"---\nglobs: docs/**/*.md\n---\nbody".into());let r=e.load_dynamic_rules("/workspace/project",&["/workspace/project/src/app.ts".into()]).unwrap();assert!(r.rules.is_empty());assert_eq!(e.deps.match_calls,2);}
#[test]fn fingerprint_current_after_commit(){let mut e=dynamic_engine();let first=e.fingerprint_dynamic_targets("/workspace/project",&["/workspace/project/src/app.ts".into()]);assert!(!e.is_dynamic_target_fingerprint_current(&first[0]));e.commit_dynamic_target_fingerprints(&first);let second=e.fingerprint_dynamic_targets("/workspace/project",&["/workspace/project/src/app.ts".into()]);assert!(e.is_dynamic_target_fingerprint_current(&second[0]));assert_eq!(e.deps.candidate_calls,2);}
#[test]fn fingerprint_change_invalidates(){let mut e=dynamic_engine();let first=e.fingerprint_dynamic_targets("/workspace/project",&["/workspace/project/src/app.ts".into()]);e.commit_dynamic_target_fingerprints(&first);e.deps.fingerprint="version-b".into();let second=e.fingerprint_dynamic_targets("/workspace/project",&["/workspace/project/src/app.ts".into()]);assert!(!e.is_dynamic_target_fingerprint_current(&second[0]));}
#[test]fn reset_clears_fingerprints(){let mut e=dynamic_engine();e.commit_dynamic_target_fingerprints(&[DynamicTargetFingerprint{target_path:"/x/y.ts".into(),cache_key:"/x/y.ts".into(),fingerprint:"abc".into()}]);e.reset_session(Some("/workspace/project"));assert!(e.state.dynamic_target_fingerprints.is_empty());}
#[test]fn early_return_clears_state(){let mut e=engine(default_config(),vec![(candidate("AGENTS.md",true),Some("body"))]);e.load_static_rules("/workspace/project");assert_eq!(e.state.loaded_rules.len(),1);e.config.mode=Mode::Dynamic;assert_eq!(e.load_static_rules("/workspace/project"),LoadResult::default());assert!(e.state.loaded_rules.is_empty());assert!(e.state.diagnostics.is_empty());}
fn loaded_single(e:&mut Engine<Deps>)->LoadedRule{e.load_static_rules("/workspace/project").rules.remove(0)}
fn single_engine()->Engine<Deps>{engine(default_config(),vec![(candidate("AGENTS.md",true),Some("body"))])}
#[test]fn static_format_delegate(){let mut e=single_engine();let rule=loaded_single(&mut e);assert_eq!(e.format_static(std::slice::from_ref(&rule)),maho_ext_pi_rules::rules::formatter::format_static_block(&[rule],&maho_ext_pi_rules::rules::formatter::FormatOptions{max_rule_chars:12000,max_result_chars:40000}));}
#[test]fn dynamic_format_delegate(){let mut e=single_engine();let rule=loaded_single(&mut e);assert_eq!(e.format_dynamic(std::slice::from_ref(&rule),"src/index.ts"),maho_ext_pi_rules::rules::formatter::format_dynamic_block(&[rule],"src/index.ts",&maho_ext_pi_rules::rules::formatter::FormatOptions{max_rule_chars:12000,max_result_chars:40000}));}
#[test]fn reset_injection_state(){let mut e=single_engine();let rule=loaded_single(&mut e);e.mark_static_injected(&rule);e.mark_dynamic_injected("scope",&rule);e.reset_session(Some("/workspace/other"));assert!(e.state.static_dedup.is_empty());assert!(e.state.dynamic_dedup.is_empty());assert_eq!(e.state.cwd.as_deref(),Some("/workspace/other"));}
#[test]fn static_mark_twice(){let mut e=single_engine();let rule=loaded_single(&mut e);assert!(e.mark_static_injected(&rule));assert!(!e.mark_static_injected(&rule));}
#[test]fn static_mark_visible(){let mut e=single_engine();let rule=loaded_single(&mut e);e.mark_static_injected(&rule);assert!(e.is_static_injected(&rule));}
#[test]fn dynamic_mark_twice(){let mut e=single_engine();let rule=loaded_single(&mut e);assert!(e.mark_dynamic_injected("scope",&rule));assert!(!e.mark_dynamic_injected("scope",&rule));}
#[test]fn target_paths_separate_matches(){let mut e=dynamic_engine();e.deps.files.insert("/workspace/project/.omo/rules/sample.md".into(),"---\nglobs: [\"src/**/*.ts\", \"!src/**/*.test.ts\"]\n---\nbody".into());assert_eq!(e.load_dynamic_rules("/workspace/project",&["/workspace/project/src/app.ts".into()]).unwrap().rules.len(),1);assert!(e.load_dynamic_rules("/workspace/project",&["/workspace/project/src/app.test.ts".into()]).unwrap().rules.is_empty());assert_eq!(e.deps.match_calls,2);}
#[test]fn sorted_dynamic_rules(){let mut root=candidate(".omo/rules/root.md",false);root.distance=3;let mut nested=candidate(".omo/rules/nested.md",false);nested.distance=1;let r=engine(default_config(),vec![(root,Some("---\nalwaysApply: true\n---\nroot")),(nested,Some("---\nalwaysApply: true\n---\nnested"))]).load_dynamic_rules("/workspace/project",&["/workspace/project/src/index.ts".into()]).unwrap();assert_eq!(r.rules[0].candidate.distance,1);assert_eq!(r.rules[1].candidate.distance,3);}
#[test]fn shared_discovery_cache(){struct CacheDeps{seen:Vec<usize>}impl EngineDeps for CacheDeps{fn find_candidates(&mut self,o:FinderOptions<'_>)->Vec<RuleCandidate>{self.seen.push(o.cache.map(|cache|std::ptr::from_mut(cache).addr()).unwrap_or(0));vec![]}fn read_file(&mut self,_:&str)->Option<String>{None}fn find_project_root(&mut self,_:&str)->Option<String>{Some("/workspace/project".into())}}let mut e=Engine::new(default_config(),CacheDeps{seen:vec![]});e.load_dynamic_rules("/workspace/project",&["/workspace/project/src/a.ts".into(),"/workspace/project/test/b.ts".into()]).unwrap();assert_eq!(e.deps.seen.len(),2);assert_ne!(e.deps.seen[0],0);assert_eq!(e.deps.seen[0],e.deps.seen[1]);}
#[test]fn nested_project_root_from_target(){struct Nested{calls:Vec<String>}impl EngineDeps for Nested{fn find_candidates(&mut self,o:FinderOptions<'_>)->Vec<RuleCandidate>{assert_eq!(o.project_root,Some(std::path::Path::new("/workspace/project/packages/app")));let mut c=candidate(".omo/rules/sample.md",false);c.path="/workspace/project/packages/app/.omo/rules/sample.md".into();c.real_path=c.path.clone();vec![c]}fn read_file(&mut self,_:&str)->Option<String>{Some("---\nglobs: src/**/*.ts\n---\nbody".into())}fn find_project_root(&mut self,path:&str)->Option<String>{self.calls.push(path.into());Some("/workspace/project/packages/app".into())}}let mut e=Engine::new(default_config(),Nested{calls:vec![]});let target="/workspace/project/packages/app/src/index.ts";let r=e.load_dynamic_rules("/workspace/project",&[target.into()]).unwrap();assert_eq!(r.rules.len(),1);assert_eq!(e.deps.calls,vec![target]);}
#[test]fn symlink_project_containment(){struct SymlinkDeps{root:String,candidate:RuleCandidate}impl EngineDeps for SymlinkDeps{fn find_candidates(&mut self,_:FinderOptions<'_>)->Vec<RuleCandidate>{vec![self.candidate.clone()]}fn read_file(&mut self,_:&str)->Option<String>{Some("---\nalwaysApply: true\n---\nbody".into())}fn find_project_root(&mut self,_:&str)->Option<String>{Some(self.root.clone())}}let temp=tempfile::tempdir().unwrap();let real=temp.path().join("real");std::fs::create_dir(&real).unwrap();let linked=temp.path().join("linked");std::os::unix::fs::symlink(&real,&linked).unwrap();let path=linked.join("rule.md");std::fs::write(&path,"body").unwrap();let mut c=candidate("rule.md",false);c.path=path.to_string_lossy().into();c.real_path=path.canonicalize().unwrap().to_string_lossy().into();let root=linked.to_string_lossy().into_owned();let mut e=Engine::new(default_config(),SymlinkDeps{root:root.clone(),candidate:c});let r=e.load_static_rules(&root);assert!(r.diagnostics.is_empty());assert_eq!(r.rules.len(),1);}
