use maho_ext_pi_rules::rules::{finder::*,types::RuleCandidate};
use std::{path::{Path,PathBuf},collections::BTreeSet};
fn write(root:&Path,name:&str)->PathBuf{let p=root.join(name);let parent=p.parent().unwrap_or_else(||panic!("fixture parent"));std::fs::create_dir_all(parent).unwrap_or_else(|e|panic!("mkdir: {e}"));std::fs::write(&p,"rule").unwrap_or_else(|e|panic!("write: {e}"));p}
fn find(root:Option<&Path>,target:Option<&Path>,home:&Path)->Vec<RuleCandidate>{find_rule_candidates(FinderOptions{project_root:root,target_file:target,home_dir:Some(home),disabled_sources:None,skip_user_home:false,cache:None})}
fn by<'a>(r:&'a[RuleCandidate],path:&str)->&'a RuleCandidate{r.iter().find(|r|r.relative_path==path).unwrap_or_else(||panic!("missing {path}"))}
#[test]
fn dotdot_named_child_uses_root_only(){
    let d=tempfile::tempdir().unwrap();
    write(d.path(),"repo/.omo/rules/root.md");
    write(d.path(),"repo/..foo/.omo/rules/child.md");
    let target=write(d.path(),"repo/..foo/file.ts");
    let rules=find(Some(&d.path().join("repo")),Some(&target),&d.path().join("home"));
    assert_eq!(rules.iter().map(|rule|rule.relative_path.as_str()).collect::<Vec<_>>(),vec![".omo/rules/root.md"]);
}
#[test]fn project_core(){let d=tempfile::tempdir().unwrap();let p=write(d.path(),"repo/.omo/rules/core.md");let r=find(Some(&d.path().join("repo")),None,&d.path().join("home"));let c=by(&r,".omo/rules/core.md");assert_eq!(c.path,p.to_string_lossy());assert_eq!(c.source,".omo/rules");assert_eq!(c.distance,0);assert!(!c.is_global);assert!(!c.is_single_file);}
#[test]fn nested_distances(){let d=tempfile::tempdir().unwrap();write(d.path(),"repo/.omo/rules/root.md");write(d.path(),"repo/packages/app/.omo/rules/nested.md");let t=write(d.path(),"repo/packages/app/src/index.ts");let r=find(Some(&d.path().join("repo")),Some(&t),&d.path().join("home"));assert_eq!(by(&r,".omo/rules/root.md").distance,3);assert_eq!(by(&r,"packages/app/.omo/rules/nested.md").distance,1);}
#[test]fn agents_single(){let d=tempfile::tempdir().unwrap();write(d.path(),"repo/AGENTS.md");let r=find(Some(&d.path().join("repo")),None,&d.path().join("home"));assert!(by(&r,"AGENTS.md").is_single_file);}
#[test]fn all_root_single_files(){let d=tempfile::tempdir().unwrap();for n in ["AGENTS.md","CLAUDE.md","CONTEXT.md"]{write(d.path(),&format!("repo/{n}"));}let r=find(Some(&d.path().join("repo")),None,&d.path().join("home"));assert_eq!(r.len(),3);}
#[test]fn cursor_mdc(){let d=tempfile::tempdir().unwrap();write(d.path(),"repo/.cursor/rules/ui.mdc");let r=find(Some(&d.path().join("repo")),None,&d.path().join("home"));assert_eq!(by(&r,".cursor/rules/ui.mdc").source,".cursor/rules");}
#[test]fn github_instructions(){let d=tempfile::tempdir().unwrap();write(d.path(),"repo/.github/instructions/foo.instructions.md");let r=find(Some(&d.path().join("repo")),None,&d.path().join("home"));assert_eq!(by(&r,".github/instructions/foo.instructions.md").source,".github/instructions");}
#[test]fn copilot_single(){let d=tempfile::tempdir().unwrap();write(d.path(),"repo/.github/copilot-instructions.md");let r=find(Some(&d.path().join("repo")),None,&d.path().join("home"));assert!(by(&r,".github/copilot-instructions.md").is_single_file);}
#[test]fn home_omo(){let d=tempfile::tempdir().unwrap();write(d.path(),"home/.omo/rules/global.md");let r=find(None,None,&d.path().join("home"));assert_eq!(r.len(),1);assert!(r[0].is_global);assert_eq!(r[0].distance,9999);assert_eq!(r[0].source,"~/.omo/rules");}
#[test]fn home_opencode(){let d=tempfile::tempdir().unwrap();write(d.path(),"home/.config/opencode/AGENTS.md");let r=find(None,None,&d.path().join("home"));assert_eq!(r[0].source,"~/.config/opencode/AGENTS.md");assert!(r[0].is_single_file);}
#[test]fn home_first_single_wins(){let d=tempfile::tempdir().unwrap();write(d.path(),"home/.config/opencode/AGENTS.md");write(d.path(),"home/.claude/CLAUDE.md");let r=find(None,None,&d.path().join("home"));assert_eq!(r.len(),1);assert_eq!(r[0].source,"~/.config/opencode/AGENTS.md");}
#[test]fn disabled_cursor(){let d=tempfile::tempdir().unwrap();write(d.path(),"repo/.cursor/rules/ui.mdc");write(d.path(),"repo/.omo/rules/core.md");let disabled=BTreeSet::from([".cursor/rules".into()]);let r=find_rule_candidates(FinderOptions{project_root:Some(&d.path().join("repo")),target_file:None,home_dir:Some(&d.path().join("home")),disabled_sources:Some(&disabled),skip_user_home:false,cache:None});assert_eq!(r.len(),1);assert_eq!(r[0].source,".omo/rules");}
#[test]fn skip_home(){let d=tempfile::tempdir().unwrap();write(d.path(),"home/.omo/rules/global.md");let r=find_rule_candidates(FinderOptions{project_root:Some(d.path()),target_file:None,home_dir:Some(&d.path().join("home")),disabled_sources:None,skip_user_home:true,cache:None});assert!(!r.iter().any(|c|c.is_global));}
#[test]fn null_root_skip_home(){let d=tempfile::tempdir().unwrap();let r=find_rule_candidates(FinderOptions{project_root:None,target_file:None,home_dir:Some(d.path()),disabled_sources:None,skip_user_home:true,cache:None});assert!(r.is_empty());}
#[test]fn null_root_home_claude(){let d=tempfile::tempdir().unwrap();write(d.path(),"home/.claude/rules/global.md");let r=find(None,None,&d.path().join("home"));assert_eq!(r.len(),1);assert_eq!(r[0].source,"~/.claude/rules");}
#[test]fn each_ancestor(){let d=tempfile::tempdir().unwrap();for n in [".omo/rules/root.md","packages/.omo/rules/packages.md","packages/app/.omo/rules/app.md"]{write(d.path(),&format!("repo/{n}"));}let t=write(d.path(),"repo/packages/app/src/file.ts");let r=find(Some(&d.path().join("repo")),Some(&t),&d.path().join("home"));assert_eq!(by(&r,"packages/app/.omo/rules/app.md").distance,1);assert_eq!(by(&r,"packages/.omo/rules/packages.md").distance,2);assert_eq!(by(&r,".omo/rules/root.md").distance,3);}
#[test]fn closest_directory(){let d=tempfile::tempdir().unwrap();write(d.path(),"repo/.omo/rules/root.md");write(d.path(),"repo/src/.omo/rules/src.md");let t=write(d.path(),"repo/src/file.ts");let r=find(Some(&d.path().join("repo")),Some(&t),&d.path().join("home"));assert_eq!(by(&r,"src/.omo/rules/src.md").distance,0);assert_eq!(by(&r,".omo/rules/root.md").distance,1);}
#[test]fn symlink_realpath(){let d=tempfile::tempdir().unwrap();let target=write(d.path(),"repo/shared/target.md");std::fs::create_dir_all(d.path().join("repo/.omo/rules")).unwrap();std::os::unix::fs::symlink(&target,d.path().join("repo/.omo/rules/linked.md")).unwrap();let r=find(Some(&d.path().join("repo")),None,&d.path().join("home"));assert_eq!(by(&r,".omo/rules/linked.md").real_path,target.canonicalize().unwrap().to_string_lossy());}
#[test]fn above_root_excluded(){let d=tempfile::tempdir().unwrap();write(d.path(),"outer/.omo/rules/outside.md");write(d.path(),"outer/packages/app/.omo/rules/inside.md");let t=write(d.path(),"outer/packages/app/src/index.ts");let r=find(Some(&d.path().join("outer/packages/app")),Some(&t),&d.path().join("home"));assert_eq!(r.len(),1);assert_eq!(r[0].relative_path,".omo/rules/inside.md");}
