use maho_ext_pi_rules::rules::{formatter::*, types::*};
fn rule(path:&str, relative:&str, body:&str)->LoadedRule { LoadedRule{candidate:RuleCandidate{path:path.into(),real_path:path.into(),source:".omo/rules".into(),distance:0,is_global:false,is_single_file:false,relative_path:relative.into()},frontmatter:RuleFrontmatter::default(),body:body.into(),content_hash:"hash".into(),match_reason:MatchReason::AlwaysApply} }
fn options(rule:usize,result:usize)->FormatOptions { FormatOptions{max_rule_chars:rule,max_result_chars:result} }
#[test] fn static_empty() { assert_eq!(format_static_block(&[],&options(100,100)),""); }
#[test] fn static_header() { let result=format_static_block(&[rule("/project/AGENTS.md","AGENTS.md","body")],&options(100,100)); assert!(result.starts_with("\n\n## Project Instructions\n")); }
#[test] fn static_source_path() { let result=format_static_block(&[rule("/project/AGENTS.md","AGENTS.md","body")],&options(100,100)); assert!(result.contains("Instructions from: /project/AGENTS.md")); }
#[test] fn static_body() { let result=format_static_block(&[rule("/project/a","a","Use strict TypeScript.")],&options(100,100)); assert!(result.contains("Use strict TypeScript.")); }
#[test] fn static_separator() { let result=format_static_block(&[rule("/project/AGENTS.md","AGENTS.md","First rule."),rule("/project/.omo/rules/test.md",".omo/rules/test.md","Second rule.")],&options(100,500)); assert!(result.contains("\n\nInstructions from: /project/.omo/rules/test.md\nSecond rule.")); }
#[test] fn static_per_rule_cap() { let path=".omo/rules/large.md"; let notice=format!("\n\n[Rule truncated. Read full rule: {path}]"); let result=format_static_block(&[rule("/project/a",path,&"a".repeat(100))],&options(notice.len()+5,200)); assert!(result.ends_with(&notice)); }
#[test] fn later_rules_excluded() { let expected="\n\n## Project Instructions\nInstructions from: /project/first.md\nfirst"; let result=format_static_block(&[rule("/project/first.md","first.md","first"),rule("/project/second.md","second.md","second")],&options(100,expected.len())); assert_eq!(result,expected); }
#[test] fn static_framing_in_budget() { let result=format_static_block(&[rule("/project/a","a",&"a".repeat(200))],&options(200,200)); assert!(result.contains("Instructions from:")); assert!(result.len()<=200); }
#[test] fn multiline_body_preserved() { let body="Line one.\nLine two.\nLine three."; let result=format_static_block(&[rule("/project/a","a",body)],&options(100,500)); assert!(result.contains(body)); }
#[test] fn static_append_separator() { let result=format_static_block(&[rule("/project/a","a","body")],&options(100,100)); assert!(result.starts_with("\n\n")); }
#[test] fn dynamic_empty() { assert_eq!(format_dynamic_block(&[],"src/index.ts",&options(100,100)),""); }
#[test] fn dynamic_target_header() { let result=format_dynamic_block(&[rule("/project/a","a","body")],"src/index.ts",&options(100,500)); assert!(result.starts_with("\n\nAdditional project instructions matched for src/index.ts:")); }
#[test] fn dynamic_source_headers() { let result=format_dynamic_block(&[rule("/project/first.md","first.md","First."),rule("/project/second.md","second.md","Second.")],"src/index.ts",&options(100,500)); assert_eq!(result.matches("Instructions from:").count(),2); assert!(result.contains("Instructions from: /project/first.md\nFirst.")); assert!(result.contains("Instructions from: /project/second.md\nSecond.")); }
#[test] fn dynamic_notice_present() { let path=".omo/rules/dynamic.md"; let notice=format!("\n\n[Rule truncated. Read full rule: {path}]"); let result=format_dynamic_block(&[rule("/project/a",path,&"d".repeat(100))],"src/index.ts",&options(notice.len()+4,200)); assert!(result.contains(&notice)); }
#[test] fn dynamic_framing_in_budget() { let result=format_dynamic_block(&[rule("/project/a","a",&"d".repeat(200))],"src/index.ts",&options(200,200)); assert!(result.contains("Instructions from:")); assert!(result.len()<=200); }
#[test] fn dynamic_append_separator() { let result=format_dynamic_block(&[rule("/project/a","a","body")],"src/index.ts",&options(100,500)); assert!(result.starts_with("\n\n")); }
