use maho_cli::cli::args::*;
fn parse(values: &[&str]) -> Args { parse_args(&values.iter().map(|s| (*s).to_owned()).collect::<Vec<_>>(), false).expect("parse") }
#[test] fn consumes_frontmatter_prompt_when_print_precedes_it() { let value = parse(&["-p", "---\ntitle: hello\n---\nSay hi."]); assert!(value.print); assert_eq!(value.messages.len(), 1); assert!(value.unknown_flags.is_empty()); }
#[test] fn preserves_options_when_print_precedes_provider() { let value = parse(&["-p", "--provider", "openai", "Say hi."]); assert_eq!(value.provider.as_deref(), Some("openai")); assert_eq!(value.messages, ["Say hi."]); }
#[test] fn separator_preserves_dash_messages_and_file_arguments() { let value = parse(&["--", "-message", "@image.png"]); assert_eq!(value.messages, ["-message"]); assert_eq!(value.file_args, ["image.png"]); }
#[test] fn missing_theme_does_not_consume_following_flag() { let value = parse(&["--use-theme", "--print"]); assert!(value.print); assert!(value.use_theme.is_none()); assert!(value.diagnostics[0].error); }
#[test] fn runtime_defaults_to_in_process_when_socket_is_requested() { let value = parse(&["--mode", "rpc", "--listen", "unix:///tmp/socket"]); assert!(value.multi_session); assert!(resolve_session_runtime(&value) == SessionRuntime::InProcess); }
#[test] fn runtime_override_wins_when_socket_is_requested() { let value = parse(&["--mode", "rpc", "--listen", "unix:///tmp/socket", "--session-runtime", "worker"]); assert!(resolve_session_runtime(&value) == SessionRuntime::Worker); }
#[test] fn listen_remains_extension_flag_when_rpc_mode_is_not_yet_selected() { let value = parse(&["--listen", "unix://", "--mode", "rpc"]); assert!(value.listen.is_none()); assert!(value.unknown_flags.contains_key("listen")); }
#[test] fn unknown_values_preserve_equals_and_boolean_forms() { let value = parse(&["--one=value", "--two", "@file", "--three", "string"]); assert!(value.unknown_flags.get("one") == Some(&FlagValue::String("value".to_owned()))); assert!(value.unknown_flags.get("two") == Some(&FlagValue::Boolean(true))); assert!(value.unknown_flags.get("three") == Some(&FlagValue::String("string".to_owned()))); }
#[test] fn legacy_provider_ids_are_rejected_when_typed() { for id in ["openai-codex", "claude-sdk-oauth"] { assert!(parse_args(&["--provider".to_owned(), id.to_owned()], false).is_err()); } }
#[test] fn grok_flag_requires_explicit_gate() { let argv = ["--grok-neo".to_owned()]; assert!(parse_args(&argv, false).expect("parse").unknown_flags.contains_key("grok-neo")); assert!(parse_args(&argv, true).expect("parse").grok_neo); }
#[test] fn repeated_resources_and_prompts_accumulate_when_given_multiple_times() { let value = parse(&["-e", "a", "--extension", "b", "--skill", "s", "--skill", "t", "--append-system-prompt", "x", "--append-system-prompt", "y"]); assert_eq!(value.extensions, ["a", "b"]); assert_eq!(value.skills, ["s", "t"]); assert_eq!(value.append_system_prompt, ["x", "y"]); }
#[test] fn comma_lists_drop_empty_tools_but_keep_empty_model_patterns() { let value = parse(&["--tools", " read,, bash ", "--models", "a,, b"]); assert_eq!(value.tools, Some(vec!["read".to_owned(), "bash".to_owned()])); assert_eq!(value.models, Some(vec!["a".to_owned(), "".to_owned(), "b".to_owned()])); }
#[test] fn name_normalization_rejects_whitespace_when_validated() { assert_eq!(normalize_session_name("  named  "), Some("named")); assert_eq!(normalize_session_name("   "), None); assert_eq!(parse(&["--name", ""]).name.as_deref(), Some("")); }
#[test] fn invalid_thinking_reports_warning_when_value_is_unknown() { let value = parse(&["--thinking", "other"]); assert!(value.thinking.is_none()); assert!(!value.diagnostics[0].error); }
