use serde_json::{Value,json};
pub struct LifecycleInputContext<'a> {pub cwd:&'a str,pub session_id:&'a str,pub transcript_path:Option<&'a str>}
fn base(event:&str,context:&LifecycleInputContext<'_>)->Value {let mut input=json!({"cwd":context.cwd,"event":event,"hook_event_name":event,"session_id":context.session_id});if let Some(path)=context.transcript_path {input["transcript_path"]=json!(path);}input}
pub fn build_session_start_hook_input(reason:&str,context:&LifecycleInputContext<'_>)->Value {let mut input=base("SessionStart",context);input["reason"]=json!(reason);input["sessionId"]=json!(context.session_id);input}
pub fn build_pre_compact_hook_input(reason:&str,request_id:&str,will_retry:bool,custom_instructions:Option<&str>,context:&LifecycleInputContext<'_>)->Value {let mut input=base("PreCompact",context);input["reason"]=json!(reason);input["request_id"]=json!(request_id);input["will_retry"]=json!(will_retry);if let Some(instructions)=custom_instructions {input["custom_instructions"]=json!(instructions);}input}
pub fn build_post_compact_hook_input(reason:&str,request_id:&str,will_retry:bool,accepted:bool,context:&LifecycleInputContext<'_>)->Value {let mut input=base("PostCompact",context);input["reason"]=json!(reason);input["request_id"]=json!(request_id);input["will_retry"]=json!(will_retry);input["accepted"]=json!(accepted);input}
pub struct NotificationHookInput<'a> {pub message:&'a str,pub kind:&'a str,pub title:Option<&'a str>,pub source:Option<&'a str>,pub request_id:Option<&'a str>,pub status:Option<&'a str>}
pub fn build_notification_hook_input(notification:NotificationHookInput<'_>,context:&LifecycleInputContext<'_>)->Value {let mut input=base("Notification",context);input["kind"]=json!(notification.kind);input["message"]=json!(notification.message);for (key,value) in [("title",notification.title),("notification_source",notification.source),("request_id",notification.request_id),("status",notification.status)] {if let Some(value)=value {input[key]=json!(value);}}input}
#[cfg(test)]
mod tests {use super::*;#[test] fn builds_lifecycle_wire_with_optional_fields() {let context=LifecycleInputContext {cwd:"/repo",session_id:"s",transcript_path:None};let start=build_session_start_hook_input("startup",&context);assert_eq!(start["sessionId"],start["session_id"]);assert!(start.get("transcript_path").is_none());let compact=build_pre_compact_hook_input("manual","r",true,Some("brief"),&context);assert_eq!(compact["will_retry"],true);assert_eq!(compact["custom_instructions"],"brief");let post=build_post_compact_hook_input("manual","r",false,true,&context);assert_eq!(post["accepted"],true);}}
