use std::sync::Arc;
use maho_core::{agent_session::{AgentSession,AgentSessionConfig},model_runtime::{ModelRuntime,CreateModelRuntimeOptions},session_manager::SessionManager,settings_manager::{SettingsManager,InMemorySettingsStorage}};
use maho_rpc::{connection_handler::handle_session_command,rpc_types::RpcCommand};
#[tokio::test]async fn real_session_queue_commands_preserve_recovery_order(){
    let temp=tempfile::tempdir().unwrap();let cwd=temp.path().to_string_lossy().into_owned();
    let runtime=ModelRuntime::create_sync(CreateModelRuntimeOptions{models_path:Some(temp.path().join("models.json")),auth_path:Some(temp.path().join("auth.json")),providers:Some(vec![]),..Default::default()});
    let session=AgentSession::new(AgentSessionConfig{
        agent:maho_agent::Agent::new(maho_agent::AgentOptions{stream_fn:Some(Arc::new(|_,_,_|maho_ai::types::AssistantMessageEventStream::assistant())),..Default::default()}),
        session_manager:SessionManager::in_memory(&cwd,None,None),settings_manager:SettingsManager::from_storage(Box::new(InMemorySettingsStorage::default()),false),
        cwd:cwd.clone(),agent_dir:Some(cwd),fallback_now:None,retry_random:None,scoped_models:vec![],favorite_models:vec![],flag_values:Default::default(),custom_tools:vec![],model_runtime:Some(runtime),model_registry:None,uses_default_stream_function:Some(false),initial_active_tool_names:None,default_tool_names:None,eval_only_tool_names:None,allowed_tool_names:None,excluded_tool_names:None,base_tools_override:None,session_start_event:None,auto_title_sessions:Some(false),
    }).unwrap();
    for kind in ["set_auto_compaction","set_auto_retry","abort_retry","abort_compaction","abort_bash"]{let mut value=serde_json::json!({"type":kind});if kind.starts_with("set_"){value["enabled"]=false.into();}let command:RpcCommand=serde_json::from_value(value).unwrap();let response=serde_json::to_value(handle_session_command(&session,&command).await.unwrap()).unwrap();assert_eq!(response["command"],kind);assert_eq!(response["success"],true);}
    assert!(!session.auto_compaction_enabled());assert!(!session.auto_retry_enabled());
    for kind in ["get_session_stats","get_fork_messages"]{let command:RpcCommand=serde_json::from_value(serde_json::json!({"type":kind})).unwrap();let response=serde_json::to_value(handle_session_command(&session,&command).await.unwrap()).unwrap();assert_eq!(response["success"],true);if kind=="get_session_stats"{assert_eq!(response["data"]["totalMessages"],0);assert_eq!(response["data"]["tokens"]["cacheRead"],0);assert!(response["data"].get("sessionFile").is_none());}else{assert_eq!(response["data"]["messages"],serde_json::json!([]));}}
    for(name,expected)in [("   ",false),("  trimmed  ",true)]{let command:RpcCommand=serde_json::from_value(serde_json::json!({"type":"set_session_name","name":name})).unwrap();let response=serde_json::to_value(handle_session_command(&session,&command).await.unwrap()).unwrap();assert_eq!(response["success"],expected);}assert_eq!(session.session_name().as_deref(),Some("trimmed"));
    let command:RpcCommand=serde_json::from_value(serde_json::json!({"type":"cycle_model"})).unwrap();let response=serde_json::to_value(handle_session_command(&session,&command).await.unwrap()).unwrap();assert_eq!(response["success"],true);assert!(response["data"].is_null());
    let previous_model=session.model();let command:RpcCommand=serde_json::from_value(serde_json::json!({"type":"set_model","provider":"missing-provider","modelId":"missing-model"})).unwrap();let response=serde_json::to_value(handle_session_command(&session,&command).await.unwrap()).unwrap();assert_eq!(response["success"],false);assert_eq!(response["error"],"Model not found: missing-provider/missing-model");assert_eq!(session.model(),previous_model);
    let command:RpcCommand=serde_json::from_value(serde_json::json!({"type":"get_available_models"})).unwrap();let response=serde_json::to_value(handle_session_command(&session,&command).await.unwrap()).unwrap();assert_eq!(response["data"]["models"].as_array().unwrap().len(),session.model_registry().get_available().len());
    let previous=session.thinking_level();let unsupported=["off","minimal","low","medium","high","xhigh","max"].into_iter().find(|level|!session.get_available_thinking_levels().contains(&serde_json::from_value::<maho_ai::types::ModelThinkingLevel>((*level).into()).unwrap())).unwrap();let command:RpcCommand=serde_json::from_value(serde_json::json!({"type":"set_thinking_level","level":unsupported,"scope":"turn"})).unwrap();let response=serde_json::to_value(handle_session_command(&session,&command).await.unwrap()).unwrap();assert_eq!(response["success"],false);assert_eq!(session.thinking_level(),previous);
    let command:RpcCommand=serde_json::from_value(serde_json::json!({"type":"get_available_thinking_levels"})).unwrap();let response=serde_json::to_value(handle_session_command(&session,&command).await.unwrap()).unwrap();assert_eq!(response["data"]["levels"],serde_json::json!(session.get_available_thinking_levels()));
    for(kind,field)in [("get_messages","messages"),("get_last_assistant_text","text")]{let command:RpcCommand=serde_json::from_value(serde_json::json!({"id":kind,"type":kind})).unwrap();let response=serde_json::to_value(handle_session_command(&session,&command).await.unwrap()).unwrap();assert_eq!(response["id"],kind);if field=="messages"{assert_eq!(response["data"][field],serde_json::json!([]));}else{assert!(response["data"].get(field).is_none());}}
    for value in [serde_json::json!({"id":"1","type":"follow_up","message":"later","enqueueOrder":2}),serde_json::json!({"id":"2","type":"steer","message":"first","enqueueOrder":1})]{let command:RpcCommand=serde_json::from_value(value).unwrap();let response=handle_session_command(&session,&command).await.unwrap();assert_eq!(serde_json::to_value(response).unwrap()["success"],true);}
    let command:RpcCommand=serde_json::from_value(serde_json::json!({"id":"3","type":"clear_queue"})).unwrap();let response=serde_json::to_value(handle_session_command(&session,&command).await.unwrap()).unwrap();assert_eq!(response["data"]["ordered"][0]["text"],"first");assert_eq!(response["data"]["ordered"][1]["text"],"later");assert_eq!(session.pending_message_count(),0);
    let scope=maho_ai::node::provider_scope::ProviderScope::new();let observed=Arc::new(std::sync::atomic::AtomicBool::new(false));let observed_hook=Arc::clone(&observed);let scope_hook=scope.clone();let registry=session.model_registry().clone();let services=maho_core::agent_session_services::AgentSessionServices{cwd:temp.path().to_string_lossy().into_owned(),agent_dir:temp.path().to_string_lossy().into_owned(),auth_storage:Arc::clone(&registry.auth_storage),model_registry:registry,settings_manager:SettingsManager::from_storage(Box::new(InMemorySettingsStorage::default()),false),diagnostics:vec![]};let mut runtime=maho_core::agent_session_runtime::AgentSessionRuntime::new(session,services,vec![],None,None);runtime.set_before_session_invalidate(Some(Box::new(move||{assert_eq!(scope_hook.state(),maho_ai::node::provider_scope::ScopeState::Active);assert!(maho_ai::node::provider_scope::active_provider_scope().is_some());observed_hook.store(true,std::sync::atomic::Ordering::SeqCst);})));maho_rpc::session_teardown::dispose_runtime(&runtime,&scope).await.unwrap();assert!(observed.load(std::sync::atomic::Ordering::SeqCst));assert_eq!(scope.state(),maho_ai::node::provider_scope::ScopeState::Closed);
}
