use maho_rpc::{host_daemon_paths::*,host_daemon_registration::*};
#[test]
fn registration_publishes_complete_pointer_with_writer_guard(){
    let temp=tempfile::tempdir().unwrap();let paths=create_host_daemon_paths("socket",temp.path());create_daemon_directories(&paths).unwrap();
    let registration=HostRegistration{pid:std::process::id(),process_start_time:maho_rpc::host_reservations::read_process_start_time(std::process::id()),socket:"socket".into(),instance_id:"one".into(),generation:4.,launch_profile_id:"profile".into()};
    write_host_registration(&paths,&registration).unwrap();let registered=read_host_registration(&paths).unwrap().unwrap();assert_eq!(registered.instance_id,"one");assert!(written_by_this_process(registered.writer.as_ref()));assert!(proven_owner(Some(&registered),"socket").is_some());
    let pointer:serde_json::Value=serde_json::from_str(&std::fs::read_to_string(&paths.pointer_file).unwrap()).unwrap();assert_eq!(pointer["layout"],2);assert_eq!(pointer["generation_dir"],"generations/one");assert!(pointer.get("pid").is_none());assert!(pointer.get("processStartTime").is_none());assert!(!paths.legacy_pid_file.exists());
}
#[test]fn clearing_registration_removes_only_pointed_generation_and_is_idempotent(){let temp=tempfile::tempdir().unwrap();let paths=create_host_daemon_paths("socket",temp.path());create_daemon_directories(&paths).unwrap();for id in ["current","other"]{create_generation_directory(&generation_paths(&paths,id)).unwrap();}std::fs::write(&paths.pointer_file,r#"{"instance_id":"current"}"#).unwrap();std::fs::write(&paths.settings_file,"{}").unwrap();std::fs::write(&paths.legacy_pid_file,"legacy").unwrap();clear_host_registration(&paths).unwrap();clear_host_registration(&paths).unwrap();assert!(!generation_paths(&paths,"current").dir.exists());assert!(generation_paths(&paths,"other").dir.exists());assert!(paths.legacy_pid_file.exists());assert!(!paths.settings_file.exists());assert!(!paths.pointer_file.exists());}
