[package]
name = "maho-ext-terminal"
version.workspace = true
edition.workspace = true
publish.workspace = true
license = "MIT"

[dependencies]
sha2 = "=0.10.9"
fancy-regex = "=0.16.2"
serde_json = "=1.0.149"
regex = "=1.12.3"
maho-ai = { path = "../../maho-ai" }
maho-tools = { path = "../../maho-tools" }

[dev-dependencies]
tempfile = "=3.27.0"

[lints]
workspace = true
