use super::*;
fn rule(name:&str)->TtsrRule { TtsrRule { name:name.into(),path:None,content:format!("content of {name}"),description:None,globs:None,condition:vec!["needle".into()],scope:TtsrScope { allow_text:true,allow_thinking:true,tool_scopes:vec![] },interrupt_mode:TtsrInterruptMode::Always,source:RuleSource::Project } }
fn ctx(source:TtsrStreamSource,key:&str)->TtsrMatchContext { TtsrMatchContext { source,stream_key:key.into(),tool_name:None,file_paths:None } }
fn text()->TtsrMatchContext { ctx(TtsrStreamSource::Text,"main") }
fn manager()->TtsrManager { TtsrManager::new(Default::default()) }
#[test] fn upstream_duplicate_name_keeps_first_registration() { let mut m=manager(); let mut first=rule("dup"); first.condition=vec!["first".into()]; let mut second=rule("dup"); second.condition=vec!["second".into()]; assert!(m.add_rule(first.clone())); assert!(!m.add_rule(second)); assert_eq!(m.rules(),[first]); assert_eq!(m.check_delta("first",&text()).len(),1); assert!(m.check_delta("second",&ctx(TtsrStreamSource::Text,"other")).is_empty()); }
#[test] fn upstream_invalid_sibling_condition_keeps_valid_condition() { let mut m=manager(); let mut r=rule("mixed"); r.condition=vec!["([".into(),"needle".into()]; assert!(m.add_rule(r)); assert_eq!(m.check_delta("needle",&text()).len(),1); }
#[test] fn upstream_unreachable_scope_rejects_rule() { let mut m=manager(); let mut r=rule("deaf"); r.scope=TtsrScope { allow_text:false,allow_thinking:false,tool_scopes:vec![] }; assert!(!m.add_rule(r)); assert!(!m.has_rules()); }
#[test] fn upstream_disabled_manager_rejects_registration_and_matching() { let mut m=TtsrManager::new(TtsrSettings { enabled:false,..Default::default() }); assert!(!m.add_rule(rule("off"))); assert!(m.check_delta("needle",&text()).is_empty()); assert!(m.rules().is_empty()); }
#[test] fn upstream_source_and_key_buffers_are_isolated() { let mut m=manager(); m.add_rule(rule("iso")); assert!(m.check_delta("nee",&ctx(TtsrStreamSource::Text,"a")).is_empty()); assert!(m.check_delta("dle",&ctx(TtsrStreamSource::Thinking,"a")).is_empty()); assert!(m.check_delta("dle",&ctx(TtsrStreamSource::Text,"b")).is_empty()); assert_eq!(m.check_delta("dle",&ctx(TtsrStreamSource::Text,"a")).len(),1); }
#[test] fn upstream_tool_call_id_buffers_are_isolated() { let mut m=manager(); let mut r=rule("tool"); r.scope=crate::scope::parse_scope(&["tool:edit".into()]); m.add_rule(r); let mut a=ctx(TtsrStreamSource::Tool,"a"); a.tool_name=Some("edit".into()); let mut b=ctx(TtsrStreamSource::Tool,"b"); b.tool_name=Some("edit".into()); assert!(m.check_delta("nee",&a).is_empty()); assert!(m.check_delta("dle",&b).is_empty()); assert_eq!(m.check_delta("dle",&a).len(),1); }
#[test] fn upstream_reset_prevents_cross_turn_match() { let mut m=manager(); m.add_rule(rule("split")); m.check_delta("nee",&text()); m.reset_buffers(); assert!(m.check_delta("dle",&text()).is_empty()); }
#[test] fn upstream_tail_window_scales_above_longest_pattern() { let mut m=manager(); let mut r=rule("long"); r.condition=vec!["x".repeat(300)]; m.add_rule(r); m.check_delta(&"a".repeat(5000),&text()); assert_eq!(m.stream_buffer_lengths()["text:main"],1200); }
#[test] fn upstream_tail_window_still_matches_final_pattern() { let mut m=manager(); m.add_rule(rule("tail")); assert_eq!(m.check_delta(&format!("{}needle","a".repeat(5000)),&text()).len(),1); assert_eq!(m.stream_buffer_lengths()["text:main"],1024); }
#[test] fn upstream_thinking_only_ignores_text() { let mut m=manager(); let mut r=rule("thinking"); r.scope=crate::scope::parse_scope(&["thinking".into()]); m.add_rule(r); assert!(m.check_delta("needle",&text()).is_empty()); assert_eq!(m.check_delta("needle",&ctx(TtsrStreamSource::Thinking,"main")).len(),1); }
#[test] fn upstream_tool_scope_gates_name_and_glob() { let mut m=manager(); let mut r=rule("edit"); r.scope=crate::scope::parse_scope(&["tool:edit(*.ts)".into()]); m.add_rule(r); let mut c=ctx(TtsrStreamSource::Tool,"main"); c.tool_name=Some("write".into()); c.file_paths=Some(vec!["src/a.ts".into()]); assert!(m.check_delta("needle",&c).is_empty()); c.tool_name=Some("edit".into()); c.file_paths=Some(vec!["src/a.rs".into()]); assert!(m.check_delta("needle",&c).is_empty()); c.file_paths=Some(vec!["src/a.ts".into()]); assert_eq!(m.check_delta("needle",&c).len(),1); }
#[test] fn upstream_wildcard_tool_matches_any_name() { let mut m=manager(); let mut r=rule("any"); r.scope=crate::scope::parse_scope(&["tool".into()]); m.add_rule(r); let mut c=ctx(TtsrStreamSource::Tool,"main"); c.tool_name=Some("arbitrary".into()); assert_eq!(m.check_delta("needle",&c).len(),1); }
#[test] fn upstream_global_globs_gate_paths_with_basename_fallback() { let mut m=manager(); let mut r=rule("paths"); r.globs=Some(vec!["*.ts".into()]); m.add_rule(r); assert!(m.check_delta("needle",&text()).is_empty()); let mut c=text(); c.file_paths=Some(vec!["src/a.rs".into()]); assert!(m.check_delta("needle",&c).is_empty()); c.file_paths=Some(vec!["src/a.ts".into()]); assert_eq!(m.check_delta("needle",&c).len(),1); }
#[test] fn upstream_restore_once_injection_suppresses_fresh_manager() { let mut original=manager(); original.add_rule(rule("once")); original.mark_injected_by_names(&["once".into()]); let mut restored=manager(); restored.add_rule(rule("once")); restored.restore_injected(&original.injected_rule_names()); assert!(restored.check_delta("needle",&text()).is_empty()); }
#[test] fn upstream_rules_and_settings_preserve_registration_order() { let mut m=manager(); m.add_rule(rule("b")); m.add_rule(rule("a")); assert_eq!(m.rules().iter().map(|r|r.name.as_str()).collect::<Vec<_>>(),["b","a"]); assert_eq!(m.settings(),&TtsrSettings::default()); }
