//! Compares maho-tui's width and wrap utilities with senpi goldens generated by
//! `bun tools/golden/run.mjs --case tui-width-corpus --case tui-wrap-cjk-emoji-7`.

use maho_tui::utils::{truncate_to_width, visible_width, wrap_text_with_ansi};
use serde_json::Value;

fn golden(name: &str) -> Vec<Value> {
    let path = format!("{}/tests/golden/{name}.json", env!("CARGO_MANIFEST_DIR"));
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{path}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("{path}: {e}"))
}

fn str_arg(call: &Value, index: usize) -> &str {
    call["args"][index].as_str().expect("string argument")
}

fn usize_of(value: &Value) -> usize {
    usize::try_from(value.as_u64().expect("unsigned number")).expect("fits usize")
}

#[test]
fn visible_width_matches_senpi_over_the_corpus_and_every_scalar_value() {
    let mut mismatches = Vec::new();
    let mut checked = 0usize;
    for call in golden("tui-width-corpus") {
        assert_eq!(call["export"], "visibleWidth");
        if let Some(runs) = call["runs"].as_array() {
            for run in runs {
                let (start, end, expected) = (
                    run[0].as_u64().expect("start"),
                    run[1].as_u64().expect("end"),
                    usize_of(&run[2]),
                );
                for cp in start..=end {
                    let c = char::from_u32(u32::try_from(cp).expect("u32")).expect("scalar value");
                    checked += 1;
                    let actual = visible_width(&c.to_string());
                    if actual != expected {
                        mismatches.push(format!("U+{cp:04X}: senpi {expected}, maho {actual}"));
                    }
                }
            }
        } else {
            let input = str_arg(&call, 0);
            let expected = usize_of(&call["result"]);
            checked += 1;
            let actual = visible_width(input);
            if actual != expected {
                mismatches.push(format!("{input:?}: senpi {expected}, maho {actual}"));
            }
        }
    }
    assert!(checked > 200_000, "corpus unexpectedly small: {checked}");
    assert!(
        mismatches.is_empty(),
        "{} of {checked} width mismatches:\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
}

#[test]
fn wrapping_cjk_and_emoji_at_width_7_matches_senpi_byte_for_byte() {
    for call in golden("tui-wrap-cjk-emoji-7") {
        let input = str_arg(&call, 0);
        let width = usize_of(&call["args"][1]);
        match call["export"].as_str() {
            Some("wrapTextWithAnsi") => {
                let expected: Vec<&str> = call["result"]
                    .as_array()
                    .expect("lines")
                    .iter()
                    .map(|l| l.as_str().expect("line"))
                    .collect();
                assert_eq!(
                    wrap_text_with_ansi(input, width),
                    expected,
                    "wrap {input:?} at {width}"
                );
            }
            Some("truncateToWidth") => {
                assert_eq!(
                    truncate_to_width(input, width, "...", false),
                    call["result"].as_str().expect("string"),
                    "truncate {input:?} at {width}"
                );
            }
            other => panic!("unexpected export {other:?}"),
        }
    }
}
